### ISSUE TITLE
ApproximateReceiveCount cannot be passed to AttribureNames array in SQS ConsumeMessageCommandInput

### ISSUE THREAD

**Issue by dormesica** [aws/aws-sdk-js-v3#5480] opened 2023-11-12 10:42 UTC
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

In the documentation of `ReceiveMessageCommandInput` ([here](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/sqs/command/ReceiveMessageCommand/)) it is stated that `ApproximateReceiveCount` can be used in `AttributeNames` (we used it until recently).

When we upgraded to client-sqs version 3.449.0, we started receiving TS error `Type '"ApproximateReceiveCount"' is not assignable to type 'QueueAttributeName'.ts(2322)`. This is probably due to a change in [this PR](https://github.com/aws/aws-sdk-js-v3/pull/5356) and to the fact that `ApproximateReceiveCount` is not a part of `QueueAttributeName`.

### SDK version number

@aws-sdk/client-sqs@3.449.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18.18.2

### Reproduction Steps

Try to create a `ReceiveMessageCommantInput` instance with `AttributeName: ['ApproximateReceiveCount'].

### Observed Behavior

Getting TS error `Type '"ApproximateReceiveCount"' is not assignable to type 'QueueAttributeName'.ts(2322)`

### Expected Behavior

No error.

### Possible Solution

Add `ApproximateReceiveCount` and the other properties documented [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/sqs/command/ReceiveMessageCommand/) to QueueAttributeName.

**Comment by kuhe** [comment] 2023-11-13 17:29
is this a duplicate of https://github.com/aws/aws-sdk-js-v3/issues/5403?

**Comment by dormesica** [comment] 2023-11-13 17:31
@kuhe It looks like my problem indeed. Sorry, I missed it.

**Comment by aBurmeseDev** [comment] 2023-11-14 22:43
Hi @dormesica - I just posted an update on the original [issue](https://github.com/aws/aws-sdk-js-v3/issues/5403#issuecomment-1811500337) and followed up with the service team. Please refer to that issue for updates going forward as we'll close this one as duplicate. 
Thank you again for reporting this,
John

**Closed by aBurmeseDev** 2023-11-14 22:43 UTC
Labels: duplicate, service-api, bug
