### ISSUE TITLE
Inconsistent client naming for StepFunctions

### ISSUE THREAD

**Issue by ljacobsson** [aws/aws-sdk-js-v3#4750] opened 2023-05-23 20:09 UTC
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

All service clients are resolved via `@aws-sdk/client-<fullservicename>`, but StepFunctions is abbreviated as `@aws-sdk/client-sfn`

For example, 
* EventBridge is `@aws-sdk/client-eventbridge`, not `@aws-sdk/client-evb`
* CloudFormation is `@aws-sdk/client-cloudformation`, not `@aws-sdk/client-cfn`
* etc

StepFunctions should be `@aws-sdk/client-stepfunctions`, not `@aws-sdk/client-sfn`

There are clients for services like SNS, SQS, SES etc that are fien to be abbreviated since nobody says "simple queue service" instead of SQS

### SDK version number

@aws-sdk/client-sfn@3.338.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.13.0

### Reproduction Steps

n/a

### Observed Behavior

n/a

### Expected Behavior

Would expect `npm install @aws-sdk/client-stepfunctions` to work

**Comment by RanVaknin** [comment] 2023-05-23 20:31
Hi @ljacobsson,

Thanks for opening up this bug report.

The client name is driven from the name of the API model published by the various AWS service teams. In this case the step functions service has defined their model file as `sfn.json` so it wil get generated as `client-<model-name>` as described in our [codgen readme](https://github.com/aws/aws-sdk-js-v3/tree/main/codegen).

> All service clients are resolved via `@aws-sdk/client-<fullservicename>`, but StepFunctions is abbreviated as @aws-sdk/client-sfn

There are many service names that are abbreviated for example `client-ses` (instead of "simple-email-service"), `client-sqs` ("simple-queue-service"), `client-ecr`, `client-ecs`, `client-ec2` , and the list goes on..
___
Since this is not an outlier, but one of many, and is documented we can conclude that this is not a bug.

Additionally, we cannot change the names of those packages for 2 reasons:
- The AWS service itself decides on what to name the model file, which is generated from an upstream source (the SDK team cannot influence / change that)

- Changing the name of a package would break existing implementations and is considered backwards incompatible.

Since it doesn't seem like you are blocked in any way, but this reads more like a concern / feature request I believe we can close this issue.

If you have any additional questions feel free to [open a discussion](https://github.com/aws/aws-sdk-js-v3/discussions/new?category=q-a).
Thanks,
Ran~

**Closed by RanVaknin** 2023-05-23 20:31 UTC
Labels: bug
