### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by DrillableBit** [aws/aws-sdk-js-v3#5135] opened 2023-08-19 16:31 UTC
### Describe the bug

Start a fresh next.js application ( create-next-app myApp) - use app router. 

 npm install @aws-sdk/client-s3 @aws-sdk/s3-request-presigner
 
 
 import into a file (don't use): 
 import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";

### Expected Behavior

- warn ./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/SignatureV4MultiRegion.js
Module not found: Can't resolve '@aws-sdk/signature-v4-crt' in 'C:\Users\aapli\Desktop\Programming\help-s3\node_modules\@aws-sdk\signature-v4-multi-region\dist-cjs'

Import trace for requested module:
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/SignatureV4MultiRegion.js
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/index.js
./node_modules/@aws-sdk/s3-request-presigner/dist-cjs/presigner.js
./node_modules/@aws-sdk/s3-request-presigner/dist-cjs/index.js
./src/_lib/afile.jsx
./src/app/page.tsx

in the console

### Current Behavior

- warn ./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/SignatureV4MultiRegion.js
Module not found: Can't resolve '@aws-sdk/signature-v4-crt' in 'C:\Users\aapli\Desktop\Programming\help-s3\node_modules\@aws-sdk\signature-v4-multi-region\dist-cjs'

Import trace for requested module:
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/SignatureV4MultiRegion.js
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/index.js
./node_modules/@aws-sdk/s3-request-presigner/dist-cjs/presigner.js
./node_modules/@aws-sdk/s3-request-presigner/dist-cjs/index.js
./src/_lib/afile.jsx
./src/app/page.tsx

### Reproduction Steps

npx create-next-app 
typescript, tailwind, approuter

 npm install @aws-sdk/client-s3 @aws-sdk/s3-request-presigner

 import into a file (don't use): 
 import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";

### SDK version used

3.395.0

### Environment details (OS name and version, etc.)

windows

**Comment by davincios** [comment] 2023-09-05 03:25
I can confirm that I have the same issue. It is there already for quite a while and resurfaces now and then.

**Comment by davincios** [comment] 2023-09-05 03:47
The bug was introduced about 2 years ago I believe. 

PLEASE DO NOT CLOSE THIS ISSUE AS HAPPENDS ALL THE TIME.


But how to do a fix for yourself [DrillableBit](https://github.com/DrillableBit):
- use the same dependency version for @aws-sdk client-s3 and s3-request presigner. 
- use a version earlier than 3.3 

what works in my next.js typescript project is this:

  "@aws-sdk/client-s3": "3.3.0",
  "@aws-sdk/s3-request-presigner": "3.3.0",

**Comment by yenfryherrerafeliz** [comment] 2023-09-05 04:52
Hi @DrillableBit, @davincios, I will investigate this issue and I will get back to you.

Thanks!

**Comment by davincios** [comment] 2023-09-05 17:16
> Hi @DrillableBit, @davincios, I will investigate this issue and I will get back to you.
> 
> Thanks!

I would really appreciate it, and am happy to provide any information possible. There is a lot of libraries that are depending on these two packages and all have to encounter the build error warnings or security code smells of this issue (when using the 3.3 or earlier versions to remove the build error warning).  

It affects must affect thousands of people. 

I am also happy to provide you an example repository with the issue to replicate the error or jump with you on a call.

**Comment by davincios** [comment] 2023-09-05 17:24
> The bug was introduced about 2 years ago I believe.
> 
> PLEASE DO NOT CLOSE THIS ISSUE AS HAPPENDS ALL THE TIME.
> 
> But how to do a fix for yourself @DrillableBit
> 
> * use the same dependency version for @aws-sdk client-s3 and s3-request presigner.
> * use a version earlier than 3.3
> 
> what works in my next.js typescript project is this:
> 
> "@aws-sdk/client-s3": "3.3.0", "@aws-sdk/s3-request-presigner": "3.3.0",

This unfortunately is not a solution for me because it doesn't pass our code security scanner. 

So I probably will have to create a custom lib as a hot fix before it is fixed by Amazon. As this issue is there already for 5 months. So if you find any additional information as well then that would be super helpful @yenfryherrerafeliz

**Comment by lutfi-haslab** [comment] 2023-10-05 03:52
Hello, i have the same issue, this is weird. I only want to import @aws-sdk/client-s3 and it's just working find. However i got error when building next app version 13.

here the output:
```
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/load-crt.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted 

Import trace for requested module:
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/load-crt.js
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/SignatureV4MultiRegion.js
./node_modules/@aws-sdk/signature-v4-multi-region/dist-cjs/index.js
./node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.shared.js
./node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.js
./node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js
./node_modules/@aws-sdk/client-s3/dist-cjs/index.js
./src/components/modal.component.tsx
./src/app/projects/[id]/applications/page.tsx
```
In dev mode, i can hide the message by configure the next config as below:
```
  webpack: (config, { isServer, nextRuntime, webpack }) => {
    // Avoid AWS SDK Node.js require issue
    if (isServer && nextRuntime === "nodejs")
      config.plugins.push(
        new webpack.IgnorePlugin({ resourceRegExp: /^aws-crt$/ })
      );
    return config;
  },
  ```
  Everything works fine, but the message is annoying and can't trace the error. I would'nt install aws-sdk since the bundle really big.

**Closed** 2023-10-26 15:22 UTC
Labels: investigating, bug, p2
