### ISSUE TITLE
"Error: Expected SignatureV4 signer" when using Transcribe audio transcription on CRA production bundle

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#2002] opened 2021-02-05 23:11 UTC
## Describe the bug
The following error is thrown on trying real-time audio transcription on production bundle:
```console
Error: Expected SignatureV4 signer, please check the client constructor.
```
Details in https://github.com/aws-samples/aws-sdk-js-notes-app/issues/20

#### SDK version number
`@aws-sdk/middleware-sdk-transcribe-streaming@npm:3.4.1`

#### Is the issue in the browser/Node.js/ReactNative?
Browser

#### Details of the browser/Node.js/ReactNative version
`Chrome: 88.0.4324.146`

## Steps to reproduce
Steps detailed in https://github.com/aws-samples/aws-sdk-js-notes-app/issues/20

#### Observed behavior
The following error is thrown when trying to use Transcribe:
```console
Error: Expected SignatureV4 signer, please check the client constructor.
```

#### Expected behavior
Error shouldn't be thrown, and Transcribe Streaming Transcription should work

## Additional context
This issue was noticed in the demo app https://github.com/aws-samples/aws-sdk-js-notes-app/issues/20

**Comment by AllanZhengYP** [comment] 2021-02-10 21:51
Related to https://github.com/aws/aws-sdk-js-v3/issues/1918

**Comment by davidpene** [comment] 2021-02-11 23:22
Hi @trivikr did you find a workaround for this issue? (besides using the dev build 😅 )

**Comment by trivikr** [comment] 2021-02-12 01:33
> Hi @trivikr did you find a workaround for this issue? (besides using the dev build 😅 )

No. We'll be prioritizing fixing this issue in the SDK in upcoming releases.

**Comment by davidpene** [comment] 2021-02-15 20:29
Hey @trivikr is there a rough timeline on this? It's holding up our release to production.

**Comment by trivikr** [comment] 2021-02-15 20:59
> is there a rough timeline on this? It's holding up our release to production.

There is no timeline on this as of now, as team is working on other higher priority tasks.

**Comment by davidpene** [comment] 2021-02-15 21:04
Are you able to give me an idea of the root cause and maybe I can pull this down and submit a PR?

**Comment by trivikr** [comment] 2021-02-15 21:12
> Are you able to give me an idea of the root cause and maybe I can pull this down and submit a PR?

The root cause was discussed in notes-app repo https://github.com/aws-samples/aws-sdk-js-notes-app/issues/20#issuecomment-774201320

Here are contributing guidelines to submit PR 👍 https://github.com/aws/aws-sdk-js-v3/blob/master/CONTRIBUTING.md

**Comment by davidpene** [comment] 2021-04-18 21:25
Hey @trivikr has there been any updates on this?

**Comment by davidpene** [comment] 2021-07-20 01:36
Hey @trivikr has there been any updates on this? Can we downgrade or upgrade the version to avoid this?

**Comment by markbrouch** [comment] 2021-08-14 02:01
@davidpene I went ahead and forked the repo and implemented my own fix since it looks like this is a very low priority for the team: https://github.com/aws/aws-sdk-js-v3/pull/2676

**Comment by AllanZhengYP** [comment] 2021-08-19 17:18
@markbrouch @davidpene 

The fix has been merged! It will be released very soon.

**Closed by AllanZhengYP** 2021-08-19 17:18 UTC
Labels: duplicate, bug
