### ISSUE TITLE
Parameters whose objects only contain optional parameters should they themselves be optional

### ISSUE THREAD

**Issue by MrSwayne** [aws/aws-sdk-js-v3#2414] opened 2021-05-21 14:19 UTC
## Describe the bug
Parameters whose objects only contain optional parameters should they themselves be optional

## Your environment
Windows 10 x64

#### SDK version number
`@aws-sdk/client-XXX@^3.16.0`
(This applies to every client I have tested, such as client-cloudwatch, client-kinesis and client-sqs) on ^3.16

#### Is the issue in the browser/Node.js/ReactNative?
Nod.js

#### Details of the browser/Node.js/ReactNative version
v14.15.4

## Steps to reproduce
1. Create a client or create a command whose parameters are all optional
2. Notice a compilation error until you specify an empty js object ({}) to the constructor

#### Observed behavior
An example from creating the cloudwatch client
```
Expected 1 arguments, but got 0.ts(2554)
CloudWatchClient.d.ts(170, 17): An argument for 'configuration' was not provided.
```

#### Expected behavior
No compilation error, as the object should be optional

#### Screenshots

The following shows my example
![CompilationError](https://user-images.githubusercontent.com/14055257/119151614-79922f80-ba47-11eb-8fdb-742e643ee804.png)

The following is what is needed for it to work (notice the empty js objects)
![NoCompilationError](https://user-images.githubusercontent.com/14055257/119151788-a21a2980-ba47-11eb-8929-6a9deb54dd31.png)

## Additional context
I think for the command it is probably OK for the request to not be optional from a functional point of view, but the constructor to the client should be optional in my eyes (as it is now when you create a new instance of a service in V2)

**Comment by ajredniwja** [comment] 2021-05-25 21:18
Hey @MrSwayne thanks for opening this issue, this seems to be the expected behavior. Duplicate feature request: https://github.com/aws/aws-sdk-js-v3/issues/424

Closing this to be tracked with other issue.

**Closed by ajredniwja** 2021-05-25 21:18 UTC
Labels: guidance
