### ISSUE TITLE
Getting clients in CommonJS, expecting ES6

### ISSUE THREAD

**Issue by brmur** [aws/aws-sdk-js-v3#2781] opened 2021-09-13 14:44 UTC
## Describe the bug
Attempting to import s3-client yield via `import  { S3Client } from "@aws-sdk/client-s3";`  yields following error: 
```console
"SyntaxError: Named export 'S3Client' not found. The requested module '@aws-sdk/client-s3' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@aws-sdk/client-s3';
const { S3Client } = pkg;
'import  { S3Client } from "@aws-sdk/client-s3";"
```

## Your environment
Windows

#### SDK version number
```json
{
  "name": "aws-sdk-v3-iam-examples",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "@aws-sdk/client-s3": "3.31.0"
  },
  "type": "module"
}
```

(but happens also with client-dynamodb, and I assume others, although I haven't tested)

#### Is the issue in the browser/Node.js/ReactNative?
Node

#### Details of the browser/Node.js/ReactNative version
v16.3.0

## Steps to reproduce
package.json
```json
{
  "name": "aws-sdk-v3-iam-examples",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "@aws-sdk/client-s3": "3.31.0"
  },
  "type": "module"
}
```

client
```js
import  { S3Client } from "@aws-sdk/client-s3";
// Set the AWS Region.
const REGION = "eu-west-1"; //e.g. "us-east-1"
// Create an Amazon S3 service client object.
const s3Client = new S3Client({ region: REGION });
export { s3Client };`
```

script
```js
// Import required AWS SDK clients and commands for Node.js.
import { PutObjectCommand, CreateBucketCommand } from "@aws-sdk/client-s3";
import { s3Client } from "./s3Client.js";

// Set the parameters
const params = {
    Bucket: "anewbucketyes", // The name of the bucket. For example, 'sample_bucket_101'.
    Key: "newkey", // The name of the object. For example, 'sample_upload.txt'.
    Body: "ehll", // The content of the object. For example, 'Hello world!".
};

const run = async () => {
    // Create an Amazon S3 bucket.
    try {
        const data = await s3Client.send(
            new CreateBucketCommand({ Bucket: params.Bucket })
        );
        console.log(data);
        console.log("Successfully created a bucket called ", data.Location);
        return data; // For unit tests.
    } catch (err) {
        console.log("Error", err);
    }
    // Create an object and upload it to the Amazon S3 bucket.
    try {
        const results = await s3Client.send(new PutObjectCommand(params));
        console.log(
            "Successfully created " +
            params.Key +
            " and uploaded it to " +
            params.Bucket +
            "/" +
            params.Key
        );
        return results; // For unit tests.
    } catch (err) {
        console.log("Error", err);
    }
};
run();
```

#### Observed behavior
```console
"SyntaxError: Named export 'S3Client' not found. The requested module '@aws-sdk/client-s3' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
```

#### Expected behavior
Code to run without error

**Comment by trivikr** [comment] 2021-09-13 22:33
I'm able to reproduce the issue with the following simple code:
```js
// test.mjs
import { S3 } from "@aws-sdk/client-s3";
```

Output:
```console
$ node test.mjs
file:///Users/trivikr/workspace/test/test.mjs:1
import { S3 } from "@aws-sdk/client-s3";
         ^^
SyntaxError: Named export 'S3' not found. The requested module '@aws-sdk/client-s3' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@aws-sdk/client-s3';
const { S3 } = pkg;

    at ModuleJob._instantiate (internal/modules/esm/module_job.js:121:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:166:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

Environment:
```console
$ node -v
v14.17.6

$ cat package.json| grep @aws-sdk/client-s3
    "@aws-sdk/client-s3": "3.31.0"
```

**Comment by trivikr** [comment] 2021-09-13 22:35
On testing various versions of `@aws-sdk/client-s3`, I noticed that the issue is introduced in [`v3.29.0`](https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.29.0).

**Comment by trivikr** [comment] 2021-09-13 22:55
Diffs for several relevant files between versions `v3.28.0` and `v3.29.0`:

<details>
<summary>package.json</summary>

```console
$ diff test-3.28.0/node_modules/@aws-sdk/client-s3/package.json test-3.29.0/node_modules/@aws-sdk/client-s3/package.json
4c4
<   "version": "3.28.0",
---
>   "version": "3.29.0",
32,73c32,73
<     "@aws-sdk/client-sts": "3.28.0",
<     "@aws-sdk/config-resolver": "3.28.0",
<     "@aws-sdk/credential-provider-node": "3.28.0",
<     "@aws-sdk/eventstream-serde-browser": "3.25.0",
<     "@aws-sdk/eventstream-serde-config-resolver": "3.25.0",
<     "@aws-sdk/eventstream-serde-node": "3.25.0",
<     "@aws-sdk/fetch-http-handler": "3.25.0",
<     "@aws-sdk/hash-blob-browser": "3.25.0",
<     "@aws-sdk/hash-node": "3.25.0",
<     "@aws-sdk/hash-stream-node": "3.25.0",
<     "@aws-sdk/invalid-dependency": "3.25.0",
<     "@aws-sdk/md5-js": "3.25.0",
<     "@aws-sdk/middleware-apply-body-checksum": "3.25.0",
<     "@aws-sdk/middleware-bucket-endpoint": "3.28.0",
<     "@aws-sdk/middleware-content-length": "3.25.0",
<     "@aws-sdk/middleware-expect-continue": "3.25.0",
<     "@aws-sdk/middleware-host-header": "3.25.0",
<     "@aws-sdk/middleware-location-constraint": "3.25.0",
<     "@aws-sdk/middleware-logger": "3.25.0",
<     "@aws-sdk/middleware-retry": "3.28.0",
<     "@aws-sdk/middleware-sdk-s3": "3.25.0",
<     "@aws-sdk/middleware-serde": "3.25.0",
<     "@aws-sdk/middleware-signing": "3.28.0",
<     "@aws-sdk/middleware-ssec": "3.25.0",
<     "@aws-sdk/middleware-stack": "3.25.0",
<     "@aws-sdk/middleware-user-agent": "3.25.0",
<     "@aws-sdk/node-config-provider": "3.28.0",
<     "@aws-sdk/node-http-handler": "3.25.0",
<     "@aws-sdk/protocol-http": "3.25.0",
<     "@aws-sdk/smithy-client": "3.28.0",
<     "@aws-sdk/types": "3.25.0",
<     "@aws-sdk/url-parser": "3.25.0",
<     "@aws-sdk/util-base64-browser": "3.23.0",
<     "@aws-sdk/util-base64-node": "3.23.0",
<     "@aws-sdk/util-body-length-browser": "3.23.0",
<     "@aws-sdk/util-body-length-node": "3.23.0",
<     "@aws-sdk/util-user-agent-browser": "3.25.0",
<     "@aws-sdk/util-user-agent-node": "3.28.0",
<     "@aws-sdk/util-utf8-browser": "3.23.0",
<     "@aws-sdk/util-utf8-node": "3.23.0",
<     "@aws-sdk/util-waiter": "3.25.0",
<     "@aws-sdk/xml-builder": "3.23.0",
---
>     "@aws-sdk/client-sts": "3.29.0",
>     "@aws-sdk/config-resolver": "3.29.0",
>     "@aws-sdk/credential-provider-node": "3.29.0",
>     "@aws-sdk/eventstream-serde-browser": "3.29.0",
>     "@aws-sdk/eventstream-serde-config-resolver": "3.29.0",
>     "@aws-sdk/eventstream-serde-node": "3.29.0",
>     "@aws-sdk/fetch-http-handler": "3.29.0",
>     "@aws-sdk/hash-blob-browser": "3.29.0",
>     "@aws-sdk/hash-node": "3.29.0",
>     "@aws-sdk/hash-stream-node": "3.29.0",
>     "@aws-sdk/invalid-dependency": "3.29.0",
>     "@aws-sdk/md5-js": "3.29.0",
>     "@aws-sdk/middleware-apply-body-checksum": "3.29.0",
>     "@aws-sdk/middleware-bucket-endpoint": "3.29.0",
>     "@aws-sdk/middleware-content-length": "3.29.0",
>     "@aws-sdk/middleware-expect-continue": "3.29.0",
>     "@aws-sdk/middleware-host-header": "3.29.0",
>     "@aws-sdk/middleware-location-constraint": "3.29.0",
>     "@aws-sdk/middleware-logger": "3.29.0",
>     "@aws-sdk/middleware-retry": "3.29.0",
>     "@aws-sdk/middleware-sdk-s3": "3.29.0",
>     "@aws-sdk/middleware-serde": "3.29.0",
>     "@aws-sdk/middleware-signing": "3.29.0",
>     "@aws-sdk/middleware-ssec": "3.29.0",
>     "@aws-sdk/middleware-stack": "3.29.0",
>     "@aws-sdk/middleware-user-agent": "3.29.0",
>     "@aws-sdk/node-config-provider": "3.29.0",
>     "@aws-sdk/node-http-handler": "3.29.0",
>     "@aws-sdk/protocol-http": "3.29.0",
>     "@aws-sdk/smithy-client": "3.29.0",
>     "@aws-sdk/types": "3.29.0",
>     "@aws-sdk/url-parser": "3.29.0",
>     "@aws-sdk/util-base64-browser": "3.29.0",
>     "@aws-sdk/util-base64-node": "3.29.0",
>     "@aws-sdk/util-body-length-browser": "3.29.0",
>     "@aws-sdk/util-body-length-node": "3.29.0",
>     "@aws-sdk/util-user-agent-browser": "3.29.0",
>     "@aws-sdk/util-user-agent-node": "3.29.0",
>     "@aws-sdk/util-utf8-browser": "3.29.0",
>     "@aws-sdk/util-utf8-node": "3.29.0",
>     "@aws-sdk/util-waiter": "3.29.0",
>     "@aws-sdk/xml-builder": "3.29.0",
79c79
<     "@aws-sdk/client-documentation-generator": "3.23.0",
---
>     "@aws-sdk/client-documentation-generator": "3.29.0",
88c88
<     "typescript": "~4.3.2"
---
>     "typescript": "~4.4.2"
```

</details>

<details>
<summary>dist/cjs/index.js</summary>

```console
$ diff test-3.28.0/node_modules/@aws-sdk/client-s3/dist/cjs/index.js test-3.29.0/node_modules/@aws-sdk/client-s3/dist/cjs/index.js
4,105c4,105
< tslib_1.__exportStar(require("./S3Client"), exports);
< tslib_1.__exportStar(require("./S3"), exports);
< tslib_1.__exportStar(require("./commands/AbortMultipartUploadCommand"), exports);
< tslib_1.__exportStar(require("./commands/CompleteMultipartUploadCommand"), exports);
< tslib_1.__exportStar(require("./commands/CopyObjectCommand"), exports);
< tslib_1.__exportStar(require("./commands/CreateBucketCommand"), exports);
< tslib_1.__exportStar(require("./commands/CreateMultipartUploadCommand"), exports);
< tslib_1.__exportStar(require("./commands/DeleteBucketCommand"), exports);
< tslib_1.__exportStar(require("./commands/DeleteBucketAnalyticsConfigurationCommand"), exports);
< tslib_1.__exportStar(require("./commands/DeleteBucketCorsCommand"), exports);
< tslib_1.__exportStar(require("./commands/DeleteBucketEncryptionCommand"), exports);
< tslib_1.__exportStar(require("./commands/DeleteBucketIntelligentTieringConfigurationCommand"), exports);
< tslib_1.__exportStar(require("./commands/DeleteBucketInventoryConfigurationCommand"), exports);
< tslib_1.__exportStar(require("./commands/DeleteBucketLifecycleCommand"), exports);
< tslib_1.__exportStar(require("./commands/DeleteBucketMetricsConfigurationCommand"), exports);
< tslib_1.__exportStar(require("./commands/DeleteBucketOwnershipControlsCommand"), exports);
< tslib_1.__exportStar(require("./commands/DeleteBucketPolicyCommand"), exports);
< tslib_1.__exportStar(require("./commands/DeleteBucketReplicationCommand"), exports);
< tslib_1.__exportStar(require("./commands/DeleteBucketTaggingCommand"), exports);
< tslib_1.__exportStar(require("./commands/DeleteBucketWebsiteCommand"), exports);
< tslib_1.__exportStar(require("./commands/DeleteObjectCommand"), exports);
< tslib_1.__exportStar(require("./commands/DeleteObjectsCommand"), exports);
< tslib_1.__exportStar(require("./commands/DeleteObjectTaggingCommand"), exports);
< tslib_1.__exportStar(require("./commands/DeletePublicAccessBlockCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetBucketAccelerateConfigurationCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetBucketAclCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetBucketAnalyticsConfigurationCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetBucketCorsCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetBucketEncryptionCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetBucketIntelligentTieringConfigurationCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetBucketInventoryConfigurationCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetBucketLifecycleConfigurationCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetBucketLocationCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetBucketLoggingCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetBucketMetricsConfigurationCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetBucketNotificationConfigurationCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetBucketOwnershipControlsCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetBucketPolicyCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetBucketPolicyStatusCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetBucketReplicationCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetBucketRequestPaymentCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetBucketTaggingCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetBucketVersioningCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetBucketWebsiteCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetObjectCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetObjectAclCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetObjectLegalHoldCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetObjectLockConfigurationCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetObjectRetentionCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetObjectTaggingCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetObjectTorrentCommand"), exports);
< tslib_1.__exportStar(require("./commands/GetPublicAccessBlockCommand"), exports);
< tslib_1.__exportStar(require("./commands/HeadBucketCommand"), exports);
< tslib_1.__exportStar(require("./waiters/waitForBucketExists"), exports);
< tslib_1.__exportStar(require("./waiters/waitForBucketNotExists"), exports);
< tslib_1.__exportStar(require("./commands/HeadObjectCommand"), exports);
< tslib_1.__exportStar(require("./waiters/waitForObjectExists"), exports);
< tslib_1.__exportStar(require("./waiters/waitForObjectNotExists"), exports);
< tslib_1.__exportStar(require("./commands/ListBucketAnalyticsConfigurationsCommand"), exports);
< tslib_1.__exportStar(require("./commands/ListBucketIntelligentTieringConfigurationsCommand"), exports);
< tslib_1.__exportStar(require("./commands/ListBucketInventoryConfigurationsCommand"), exports);
< tslib_1.__exportStar(require("./commands/ListBucketMetricsConfigurationsCommand"), exports);
< tslib_1.__exportStar(require("./commands/ListBucketsCommand"), exports);
< tslib_1.__exportStar(require("./commands/ListMultipartUploadsCommand"), exports);
< tslib_1.__exportStar(require("./commands/ListObjectsCommand"), exports);
< tslib_1.__exportStar(require("./commands/ListObjectsV2Command"), exports);
< tslib_1.__exportStar(require("./pagination/ListObjectsV2Paginator"), exports);
< tslib_1.__exportStar(require("./commands/ListObjectVersionsCommand"), exports);
< tslib_1.__exportStar(require("./commands/ListPartsCommand"), exports);
< tslib_1.__exportStar(require("./pagination/ListPartsPaginator"), exports);
< tslib_1.__exportStar(require("./commands/PutBucketAccelerateConfigurationCommand"), exports);
< tslib_1.__exportStar(require("./commands/PutBucketAclCommand"), exports);
< tslib_1.__exportStar(require("./commands/PutBucketAnalyticsConfigurationCommand"), exports);
< tslib_1.__exportStar(require("./commands/PutBucketCorsCommand"), exports);
< tslib_1.__exportStar(require("./commands/PutBucketEncryptionCommand"), exports);
< tslib_1.__exportStar(require("./commands/PutBucketIntelligentTieringConfigurationCommand"), exports);
< tslib_1.__exportStar(require("./commands/PutBucketInventoryConfigurationCommand"), exports);
< tslib_1.__exportStar(require("./commands/PutBucketLifecycleConfigurationCommand"), exports);
< tslib_1.__exportStar(require("./commands/PutBucketLoggingCommand"), exports);
< tslib_1.__exportStar(require("./commands/PutBucketMetricsConfigurationCommand"), exports);
< tslib_1.__exportStar(require("./commands/PutBucketNotificationConfigurationCommand"), exports);
< tslib_1.__exportStar(require("./commands/PutBucketOwnershipControlsCommand"), exports);
< tslib_1.__exportStar(require("./commands/PutBucketPolicyCommand"), exports);
< tslib_1.__exportStar(require("./commands/PutBucketReplicationCommand"), exports);
< tslib_1.__exportStar(require("./commands/PutBucketRequestPaymentCommand"), exports);
< tslib_1.__exportStar(require("./commands/PutBucketTaggingCommand"), exports);
< tslib_1.__exportStar(require("./commands/PutBucketVersioningCommand"), exports);
< tslib_1.__exportStar(require("./commands/PutBucketWebsiteCommand"), exports);
< tslib_1.__exportStar(require("./commands/PutObjectCommand"), exports);
< tslib_1.__exportStar(require("./commands/PutObjectAclCommand"), exports);
< tslib_1.__exportStar(require("./commands/PutObjectLegalHoldCommand"), exports);
< tslib_1.__exportStar(require("./commands/PutObjectLockConfigurationCommand"), exports);
< tslib_1.__exportStar(require("./commands/PutObjectRetentionCommand"), exports);
< tslib_1.__exportStar(require("./commands/PutObjectTaggingCommand"), exports);
< tslib_1.__exportStar(require("./commands/PutPublicAccessBlockCommand"), exports);
< tslib_1.__exportStar(require("./commands/RestoreObjectCommand"), exports);
< tslib_1.__exportStar(require("./commands/SelectObjectContentCommand"), exports);
< tslib_1.__exportStar(require("./commands/UploadPartCommand"), exports);
< tslib_1.__exportStar(require("./commands/UploadPartCopyCommand"), exports);
< tslib_1.__exportStar(require("./commands/WriteGetObjectResponseCommand"), exports);
< tslib_1.__exportStar(require("./pagination/Interfaces"), exports);
< tslib_1.__exportStar(require("./models/index"), exports);
---
> (0, tslib_1.__exportStar)(require("./S3Client"), exports);
> (0, tslib_1.__exportStar)(require("./S3"), exports);
> (0, tslib_1.__exportStar)(require("./commands/AbortMultipartUploadCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/CompleteMultipartUploadCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/CopyObjectCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/CreateBucketCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/CreateMultipartUploadCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/DeleteBucketCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/DeleteBucketAnalyticsConfigurationCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/DeleteBucketCorsCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/DeleteBucketEncryptionCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/DeleteBucketIntelligentTieringConfigurationCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/DeleteBucketInventoryConfigurationCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/DeleteBucketLifecycleCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/DeleteBucketMetricsConfigurationCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/DeleteBucketOwnershipControlsCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/DeleteBucketPolicyCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/DeleteBucketReplicationCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/DeleteBucketTaggingCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/DeleteBucketWebsiteCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/DeleteObjectCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/DeleteObjectsCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/DeleteObjectTaggingCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/DeletePublicAccessBlockCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetBucketAccelerateConfigurationCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetBucketAclCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetBucketAnalyticsConfigurationCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetBucketCorsCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetBucketEncryptionCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetBucketIntelligentTieringConfigurationCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetBucketInventoryConfigurationCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetBucketLifecycleConfigurationCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetBucketLocationCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetBucketLoggingCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetBucketMetricsConfigurationCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetBucketNotificationConfigurationCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetBucketOwnershipControlsCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetBucketPolicyCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetBucketPolicyStatusCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetBucketReplicationCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetBucketRequestPaymentCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetBucketTaggingCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetBucketVersioningCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetBucketWebsiteCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetObjectCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetObjectAclCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetObjectLegalHoldCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetObjectLockConfigurationCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetObjectRetentionCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetObjectTaggingCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetObjectTorrentCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/GetPublicAccessBlockCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/HeadBucketCommand"), exports);
> (0, tslib_1.__exportStar)(require("./waiters/waitForBucketExists"), exports);
> (0, tslib_1.__exportStar)(require("./waiters/waitForBucketNotExists"), exports);
> (0, tslib_1.__exportStar)(require("./commands/HeadObjectCommand"), exports);
> (0, tslib_1.__exportStar)(require("./waiters/waitForObjectExists"), exports);
> (0, tslib_1.__exportStar)(require("./waiters/waitForObjectNotExists"), exports);
> (0, tslib_1.__exportStar)(require("./commands/ListBucketAnalyticsConfigurationsCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/ListBucketIntelligentTieringConfigurationsCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/ListBucketInventoryConfigurationsCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/ListBucketMetricsConfigurationsCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/ListBucketsCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/ListMultipartUploadsCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/ListObjectsCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/ListObjectsV2Command"), exports);
> (0, tslib_1.__exportStar)(require("./pagination/ListObjectsV2Paginator"), exports);
> (0, tslib_1.__exportStar)(require("./commands/ListObjectVersionsCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/ListPartsCommand"), exports);
> (0, tslib_1.__exportStar)(require("./pagination/ListPartsPaginator"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutBucketAccelerateConfigurationCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutBucketAclCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutBucketAnalyticsConfigurationCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutBucketCorsCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutBucketEncryptionCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutBucketIntelligentTieringConfigurationCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutBucketInventoryConfigurationCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutBucketLifecycleConfigurationCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutBucketLoggingCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutBucketMetricsConfigurationCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutBucketNotificationConfigurationCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutBucketOwnershipControlsCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutBucketPolicyCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutBucketReplicationCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutBucketRequestPaymentCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutBucketTaggingCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutBucketVersioningCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutBucketWebsiteCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutObjectCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutObjectAclCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutObjectLegalHoldCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutObjectLockConfigurationCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutObjectRetentionCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutObjectTaggingCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/PutPublicAccessBlockCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/RestoreObjectCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/SelectObjectContentCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/UploadPartCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/UploadPartCopyCommand"), exports);
> (0, tslib_1.__exportStar)(require("./commands/WriteGetObjectResponseCommand"), exports);
> (0, tslib_1.__exportStar)(require("./pagination/Interfaces"), exports);
> (0, tslib_1.__exportStar)(require("./models/index"), exports);
```

</details>

The issue appears to be with TypeScript ~4.4.2 bump.

**Comment by trivikr** [comment] 2021-09-13 23:01
Closing as duplicate of https://github.com/aws/aws-sdk-js-v3/issues/2754

**Closed by trivikr** 2021-09-13 23:01 UTC
Labels: bug
