### ISSUE TITLE
@aws-sdk/credential-provider-node doesn't provide @aws-sdk/client-sts

### ISSUE THREAD

**Issue by samuelcole** [aws/aws-sdk-js-v3#6049] opened 2024-05-02 14:33 UTC
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

After yarn install I get:

```
➤ YN0002: │ @aws-sdk/credential-provider-node@npm:3.567.0 doesn't provide @aws-sdk/client-sts (pd83b4), requested by @aws-sdk/credential-provider-web-identity
➤ YN0002: │ @aws-sdk/credential-provider-node@npm:3.567.0 doesn't provide @aws-sdk/client-sts (p294b1), requested by @aws-sdk/credential-provider-ini
➤ YN0002: │ @aws-sdk/credential-provider-sso@npm:3.567.0 doesn't provide @aws-sdk/client-sso-oidc (pb330e), requested by @aws-sdk/token-providers
```

additionally my [unimported](https://github.com/smeijer/unimported) tooling reports:

```
1 │ @aws-sdk/client-sso-oidc at ../../node_modules/@aws-sdk/token-providers/dist-cjs/index.js
2 │ @aws-sdk/client-sts at ../../node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js, ../../node_modules/@aws-sdk/credential-provider-web-identity/dist-cjs/fromWebToken.js
```

### SDK version number

@aws-sdk/credential-provider-node@npm:3.567.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node v20.9.0, yarn 3.5.0

### Reproduction Steps

`yarn install`

### Observed Behavior

reports warnings

### Expected Behavior

no warnings

### Possible Solution

add `@aws-sdk/client-sts` and `@aws-sdk/client-sso-oidc` as dependencies for `@aws-sdk/credential-provider-node`

**Comment by trivikr** [comment] 2024-05-02 19:56
If you have a minimal repro, please post it in the issue comments. I'll also post my attempts in reproducing.
It'll help identify in which version it was introduced. We suspect it was introduced in either v3.564.0 or v3.565.0

The current workaround is to pin your client dependency to `<3.564.0` in package.json as follows:
```
   "client-dynamodb": "<3.564.0",
```

**Comment by trivikr** [comment] 2024-05-02 20:00
I'm not able to repro with this simple commands in a new workspace, and dependencies are installed

```console
$ node -v
v20.12.2

$ corepack enable && yarn set version 4.2.1

$ yarn init -y && yarn add @aws-sdk/client-dynamodb@3.567.0 --exact
```

**Comment by trivikr** [comment] 2024-05-02 20:04
Minimal repro with `yarn@3.5.0` shows warnings

```console
$ corepack enable && yarn set version 3.5.0

$ yarn init -y && yarn add @aws-sdk/client-dynamodb@3.567.0 --exact
...
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @aws-sdk/credential-provider-node@npm:3.567.0 doesn't provide @aws-sdk/client-sts (pd83b4), requested by @aws-sdk/credential-provider-web-identity
➤ YN0002: │ @aws-sdk/credential-provider-node@npm:3.567.0 doesn't provide @aws-sdk/client-sts (p294b1), requested by @aws-sdk/credential-provider-ini
➤ YN0002: │ @aws-sdk/credential-provider-sso@npm:3.567.0 doesn't provide @aws-sdk/client-sso-oidc (pb330e), requested by @aws-sdk/token-providers
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 805ms
...
```

Not reproducible with `3.563.0`

**Comment by conico974** [comment] 2024-05-02 21:22
@trivikr It can also cause issue if you set `auto-install-peers=false` in `.npmrc`
Also in some cases in CI, it seems that `npx` also doesn't install peer dependencies which make CI fail.

**Comment by trivikr** [comment] 2024-05-02 22:37
> We're exploring re-adding the direct dependencies on clients.

PR posted at https://github.com/aws/aws-sdk-js-v3/pull/6055

**Comment by trivikr** [comment] 2024-05-02 23:23
> PR posted at https://github.com/aws/aws-sdk-js-v3/pull/6055

PR is merged, and the fix is expected to be published in https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.569.0 around 12:30 PM Pacific on Friday, May 3.

Reopening this issue for verification post publish.

**Comment by samuelcole** [comment] 2024-05-03 20:23
i can confirm it fixes my issue (which was `unimported` failing)!

**Comment by trivikr** [comment] 2024-05-03 20:32
Closing as original author confirmed the issue is fixed in their setup.

Do create a new [bug report](https://github.com/aws/aws-sdk-js-v3/issues/new?assignees=&labels=bug%2Cneeds-triage&projects=&template=bug-report.yml&title=TITLE+FOR+BUG+REPORT) if the issue is reproducible in your setup.

**Closed by trivikr** 2024-05-03 20:32 UTC
Labels: bug, p2

**Comment by robertfmurdock** [comment] 2024-05-04 16:23
Found this bug broke my service's ability to access DynamoDB in production today, updated the libraries to 3.569.0, and it was fixed. Guessing my toy app was broken for about 24 hours due to this.

Apparently locally testing with a local DynamoDB docker image wasn't enough to detect the problem, so I hope ya'll have added some test coverage to help ensure surprises like this don't happen again.

Thanks for the fast turnaround!
