### ISSUE TITLE
@aws-sdk/client-translate : socket hang up Error [TimeoutError] 

### ISSUE THREAD

**Issue by bsriniv** [aws/aws-sdk-js-v3#4219] opened 2022-11-22 07:43 UTC
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

We are experiencing the intermittent socket hang up Error [TimeoutError] when using the SDK, particularly the TranslateClient.

```console
Error in AWS translate service : socket hang up Error [TimeoutError]: socket hang up
    at connResetException (internal/errors.js:639:14)
    at TLSSocket.socketOnEnd (_http_client.js:499:23)
    at TLSSocket.emit (events.js:412:35)
    at TLSSocket.emit (domain.js:475:12)
    at /home/deploy/node_modules/newrelic/lib/shim/shim.js:1313:22
    at LegacyContextManager.runInContext (/home/deploy/node_modules/newrelic/lib/context-manager/legacy-context-manager.js:59:23)
    at Shim.applySegment (/home/deploy/node_modules/newrelic/lib/shim/shim.js:1303:25)
    at TLSSocket.wrapper [as emit] (/home/deploy/node_modules/newrelic/lib/shim/shim.js:1904:17)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ECONNRESET',
  '$metadata': { attempts: 3, totalRetryDelay: 426 }
}
```
### SDK version number

@aws-sdk/client-translate@3.192.0 and @aws-sdk/client-translate@3.213.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v14.21.1

### Reproduction Steps
```js
const AwsTranslateClient = new TranslateClient({
  region: 'us-east-1'
})


const awsTranslateText = async ( originalText, targetLanguageCode, sourceLanguageCode ) => {
  let data = null
  try {
    const params = {
      Text: originalText,
      SourceLanguageCode: sourceLanguageCode || 'en',
      TargetLanguageCode: targetLanguageCode,
    }
    const command = new TranslateTextCommand(params)
    data = await AwsTranslateClient.send(command)
  } catch (err) {
    console.log(err, `Error in AWS translate service : ${err.message}`)
  }
  return data
}
```
### Observed Behavior
```console
Error in AWS translate service : socket hang up Error [TimeoutError]: socket hang up
    at connResetException (internal/errors.js:639:14)
    at TLSSocket.socketOnEnd (_http_client.js:499:23)
    at TLSSocket.emit (events.js:412:35)
    at TLSSocket.emit (domain.js:475:12)
    at /home/deploy/node_modules/newrelic/lib/shim/shim.js:1313:22
    at LegacyContextManager.runInContext (/home/deploy/node_modules/newrelic/lib/context-manager/legacy-context-manager.js:59:23)
    at Shim.applySegment (/home/deploy/node_modules/newrelic/lib/shim/shim.js:1303:25)
    at TLSSocket.wrapper [as emit] (/home/deploy/node_modules/newrelic/lib/shim/shim.js:1904:17)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ECONNRESET',
  '$metadata': { attempts: 3, totalRetryDelay: 426 }
}
```
### Expected Behavior

The API call should succeed without socket hang up Error [TimeoutError]: socket hang up

### Additional Information/Context

Still we are seeing the socket hangup error after updating the latest translate client version 3.213.0 and also enabled the keepAlive with httpOptions as shown below:
```js
const AwsTranslateClient = new TranslateClient({
  region: 'us-east-1',
  httpOptions: {
    agent: new Agent({ keepAlive: true }),
  },
  region: 'us-east-1'
})
```

**Comment by yenfryherrerafeliz** [comment] 2022-12-09 22:52
Hi @bsriniv, thanks for opening this issue. This issue commonly occurs when there is a connectivity problem at the time of the request, and I actually see it did retry 3 times and got the same result, which is weird. I tried to get a reproduction of this error on my end but I could not, so, are there any other details you think I should consider to replicate this error on my end?

Thanks!

**Comment by yenfryherrerafeliz** [comment] 2022-12-23 16:42
Hi @bsriniv, I have reopened the issue. Do you have any other details that could help me in reproducing this on my end?

Thanks!

**Comment by oielbanna** [comment] 2023-04-27 18:29
Hey, I'm having the same issue when using `client-sns`. Are there any updates?

**Comment by benheymink** [comment] 2023-06-19 08:48
Started seeing this as well (on the lambda clint) since transitioning to V3 of the SDK. Am using 3.188.0, since that's the version bundled with the runtime. I can't pin down what is causing it, and we're manually destroying our lambda client after each use:

```
    const lambdaClient = new LambdaClient({});
    try {
        return await lambdaClient.send(command);
    } finally {
        lambdaClient.destroy();
    }
```

`"TimeoutError: socket hang up\n    at connResetException (node:internal/errors:717:14)\n    at TLSSocket.socketCloseListener (node:_http_client:475:25)\n    at TLSSocket.emit (node:events:525:35)\n    at node:net:322:12\n    at TCP.done (node:_tls_wrap:588:7)\n    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)"`

**Comment by yenfryherrerafeliz** [comment] 2023-09-07 19:07
Hi @benheymink, @oielbanna, which version of the SDK are you using?, if is not the latest, could you please try with the latest version?. We have introduced the following change [here](https://github.com/aws/aws-sdk-js-v3/pull/4561) that makes the underlying sockets to send keep-alive packets and keep the connection alive longer, so I am wondering if this could be helpful for you.

Please let me know.

Thanks!

**Comment by benheymink** [comment] 2023-09-08 06:50
@yenfryherrerafeliz We're using the version made available by the AWS Lambda runtime, 3.188.0. (So I doubt it includes the fix you mentioned).

How often are the AWS runtimes/environments updated?

**Comment by dan-istoc-k24** [comment] 2023-09-21 07:13
Hi, we got this error as well yesterday with the `SNSClient`.

Didn't enable `keepAlive` witht the requestHandler (didn't pass a requestHandler at all).

### Package version:
`"@aws-sdk/client-sns": "^3.363.0"`

### Nodejs version:
v19

### Stack trace:
`"TimeoutError: socket hang up\n    
at connResetException (node:internal/errors:717:14)\n    
at TLSSocket.socketCloseListener (node:_http_client:468:25)\n    
at TLSSocket.emit (node:events:525:35)\n    
at runInContextCb (/app/node_modules/newrelic/lib/shim/shim.js:1315:22)\n    
at LegacyContextManager.runInContext (/app/node_modules/newrelic/lib/context-manager/legacy-context-manager.js:59:23)\n    
at Shim.applySegment (/app/node_modules/newrelic/lib/shim/shim.js:1305:25)\n    
at TLSSocket.wrapper [as emit] (/app/node_modules/newrelic/lib/shim/shim.js:1861:17)\n    
at node:net:332:12\n    
at TCP.done (node:_tls_wrap:588:7)\n    
at TCP.callbackTrampoline (node:internal/async_hooks:130:17)"`

**Comment by yenfryherrerafeliz** [comment] 2023-10-18 18:34
@dan-istoc-k24 this error is caused by a network issues, such as connection interruption or lost, etc., and enabling keep-alive may help sometimes, but all depends on what really happens with the connection at that time. Also, keep-alive is enabled by default.

Thanks!

**Comment by yenfryherrerafeliz** [comment] 2023-10-26 16:36
I am closing this for now, but please if you still need help feel free of opening a new issue. 

Thanks!

**Closed by yenfryherrerafeliz** 2023-10-26 16:36 UTC
Labels: bug, p2
