### ISSUE TITLE
sns.listTopics() does not work, sns.listTopics({}) works 

### ISSUE THREAD

**Issue by vvo** [aws/aws-sdk-js-v3#1406] opened 2020-07-29 14:23 UTC
**Describe the bug**
The documentation says that `params` in sns.listTopics defaults to `{}` but if you try to use:

```js
sns.listTopics();
```

Then it will error with: `TypeError: Cannot read property 'NextToken' of undefined`.

While `sns.listTopics({})` will work.

Documentation says that params defaults to `{}` (https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SNS.html#listTopics-property).

**SDK version number** gamma 5

**Is the issue in the browser/Node.js/ReactNative?**
Browser/Node.js/ReactNative

**Details of the browser/Node.js/ReactNative version**
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by trivikr** [comment] 2020-07-29 18:27
Duplicate of https://github.com/aws/aws-sdk-js-v3/issues/424

**Closed by trivikr** 2020-07-29 18:27 UTC
