### ISSUE TITLE
Profile is not read when defined as assuming role

### ISSUE THREAD

**Issue by jaraqueffdc** [aws/aws-sdk-js-v3#2393] opened 2021-05-14 11:46 UTC
## Describe the bug
I am not sure if this is a bug or a feature request, I am assuming it is a bug because this is a rather standard behaviour even with other sdks (the python one works fine, for example).

The issue is that in my shared credentials file I have a security profile we use to log into our centralized IAM account and from there we can assume roles into other accounts with proper permissions. The way we do this is by defining them as profiles with the security profile as source profile and indicating what role to asume in the config shared filed.

For example, this profile is present in my `.aws/credentials` file

```
[securityiam]
aws_access_key_id=AKIAXXXXXX
aws_secret_access_key=XXXXXX
```

and then, in my `.aws/config` file I have configured this profile

```
[profile my-new-profile]
source_profile=securityiam
role_arn=arn:aws:iam::XXXX:role/my_role_to_asume
```

I wold expect that by creating an S3 client specifying the `analytics-dev` profile it would automatically handle the role assumption logic but it seems that it does not. I get the following error:

```
ProviderError: Profile my-new-profile requires a role to be assumed, but no role assumption callback was provided.
```

We would like to avoid, if possible, having dependencies in code with the role to be used because, when deployed, it will authenticate using the service metadata. Having to add a role assumption logic seems adding logic we should not need (and with other sdks we actually don't need). Whatever extra code we need to add is code only intended for development purposes and we would like to keep it to the minimum.

Probably I am missing something, let me know if you need further information.

Thanks!

#### SDK version number
`@aws-sdk/credential-provider-node@3.15.0`
`@aws-sdk/client-s3@3.15.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
node v14.16.0

## Steps to reproduce
Add a profile into `.aws/credentials` and a profile as explained above in `.aws/config`. Create a client to s3 that tries to list buckets

```ts
import { S3, ListBucketsCommandInput } from "@aws-sdk/client-s3";
import { defaultProvider } from "@aws-sdk/credential-provider-node";


const credentials = defaultProvider({profile: "my-new-profile"});

const client = new S3({credentials: credentials, region: "us-east-1"});

const buckets = client.listBuckets({}, (err, data) => {
    if (err) console.log(err, err.stack); // an error occurred
    else     console.log(data);           // successful response
});
console.log(buckets);
```

#### Observed behavior
The call returns an error that states:

```
ProviderError: Profile analytics-dev requires a role to be assumed, but no role assumption callback was provided.
```

#### Expected behavior
The S3 client returns the list of bucket using the assumed role as stated in the config file.

**Comment by ajredniwja** [comment] 2021-06-10 06:12
Hi @jaraqueffdc, thanks for opening this issue, I believe this should have been fixed by https://github.com/aws/aws-sdk-js-v3/pull/2221 can you verify if it is still an issue?

**Comment by jaraqueffdc** [comment] 2021-06-10 07:40
Hi, thanks for the answer! 

Has that changed been released? I have updated to version 3.18.0 and I am still seeing the error. This is the piece of code I am using:

```ts
import { S3, ListBucketsCommandInput } from "@aws-sdk/client-s3";
import { defaultProvider } from "@aws-sdk/credential-provider-node";


const credentials = defaultProvider({profile: "analytics-dev"});

const client = new S3({credentials: credentials, region: "us-east-1"});

const buckets = client.listBuckets({}, (err, data) => {
    if (err) console.log(err, err.stack); // an error occurred
    else     console.log(data);           // successful response
});
console.log(buckets);
```

And the error is the same as before

```
Error: Profile analytics-dev requires a role to be assumed, but no role assumption callback was provided.
```

Maybe I am missing something or misunderstanding how it should work? I can ensure the profile is properly setup since running 

```
aws --profile analytics-dev s3 ls
``

properly returns the list of buckets.

**Comment by ajredniwja** [comment] 2021-06-10 07:42
It is release, I will try to reproduce this and discuss it with the team as well.

**Comment by njlaw** [comment] 2021-07-19 06:08
I was experiencing this as well and am currently using the following work-around: explicitly specifying the default roleAssumer from STS:

```typescript
import { getDefaultRoleAssumerWithWebIdentity, getDefaultRoleAssumer } from '@aws-sdk/client-sts';
import { defaultProvider } from '@aws-sdk/credential-provider-node';
import { STSClient, GetCallerIdentityCommand } from '@aws-sdk/client-sts';

const provider = defaultProvider({
  roleAssumerWithWebIdentity: getDefaultRoleAssumerWithWebIdentity(),
  roleAssumer: getDefaultRoleAssumer(),
});

const stsClient = new STSClient({ credentialDefaultProvider: () => provider });

async function main() {
  console.log(await stsClient.send(new GetCallerIdentityCommand({}));
}

main();
```

I know that it is intended behavior for roleAssumerWithWebIdentity, but the documentation at https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_provider_node.html makes it sound like this should happen automatically for roleAssumer:

> `roleAssumer` - A function that assumes a role and returns a promise fulfilled with credentials for the assumed role. **If not specified, the SDK will create an STS client and call its assumeRole method.** (my emphasis)

**Closed** 2021-08-18 23:08 UTC
Labels: bug, workaround-avaialable
