### ISSUE TITLE
Warning -  Can't resolve 'aws-crt', maybe related to SecretsManagerClient

### ISSUE THREAD

**Issue by mwawrusch** [aws/aws-sdk-js-v3#2885] opened 2021-10-09 02:14 UTC
## Describe the bug
At least with versions 3.35 and 3.36 I get the following warning when compiling using webpack:

```
WARNING in ../node_modules/@aws-sdk/util-user-agent-node/dist-es/is-crt-available.js 3:96-114
Module not found: Error: Can't resolve 'aws-crt' in '/Users/mwawrusch/Dev/roji/aws-backend/aws-backend-wallet/lambdas/node_modules/@aws-sdk/util-user-agent-node/dist-es'
 @ ../node_modules/@aws-sdk/util-user-agent-node/dist-es/index.js 5:0-52 16:23-37
 @ ../node_modules/@aws-sdk/client-secrets-manager/dist-es/runtimeConfig.js
 @ ../node_modules/@aws-sdk/client-secrets-manager/dist-es/SecretsManagerClient.js 10:0-73 15:24-42
 @ ../node_modules/@aws-sdk/client-secrets-manager/dist-es/index.js 1:0-39 1:0-39
 @ ../aurorav2/aurora-helper.ts 1:0-94 4:33-53 8:65-86
 @ ./src/handler.ts 10:0-73 28:29-54
 ```

#### SDK version number
     "@aws-sdk/client-cognito-identity-provider": "3.36.0",
        "@aws-sdk/client-cognito-identity": "3.36.0",
        "@aws-sdk/client-ssm": "3.36.0",
        "@aws-sdk/client-sns": "3.36.0",
        "@aws-sdk/client-sqs": "3.36.0",
        "@aws-sdk/client-rds-data": "3.36.0",
        "@aws-sdk/client-secrets-manager": "3.36.0",

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`
v14.15.0
## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.

#### Observed behavior
A clear and concise description of what happens.

#### Expected behavior
A clear and concise description of what you were expecting to happen.

**Comment by samchungy** [comment] 2021-10-10 08:14
List it as external in your webpack config

**Comment by bluepeter** [comment] 2021-11-17 03:47
Related to https://github.com/aws/aws-sdk-js-v3/issues/2750 ... this has been 'bugging' us for weeks now.

**Comment by vudh1** [comment] 2021-12-06 20:53
Hi @mwawrusch thanks for reaching out. I am not able to reproduce this. Please refer to this #2750 also. Let me know if you are still experiencing this with the latest version of SDK

**Comment by coneill-relay** [comment] 2021-12-16 23:56
I'm running into this as well bundling my application using serverless-webpack. 

I was trying to bundle everything down to a single file rather than uploading the node_modules folder and unless I install this package or add it as an external I get this warning. 

```
WARNING in ./node_modules/@aws-sdk/util-user-agent-node/dist-cjs/is-crt-available.js 6:96-114
Module not found: Error: Can't resolve 'aws-crt' in '/node_modules/@aws-sdk/util-user-agent-node/dist-cjs'
```

**Comment by coneill-relay** [comment] 2021-12-16 23:58
As others have also stated that `aws-crt` package is enourmous. does this need to be installed for SSM to work?

**Comment by coneill-relay** [comment] 2021-12-17 13:48
@samchungy I think a better solution might be to use `resolve.alias` or possibly NormalModuleReplacementPlugin for webpack. I think marking as external still generates the `require (aws-crt)` if you are trying to parse the node_modules to generate a single a file I haven't tested that out tho.

**Comment by samchungy** [comment] 2021-12-18 11:15
> @samchungy I think a better solution might be to use `resolve.alias` or possibly NormalModuleReplacementPlugin for webpack. I think marking as external still generates the `require (aws-crt)` if you are trying to parse the node_modules to generate a single a file I haven't tested that out tho.

Yes it still generates the require but does try to traverse the library which is the whole purpose of external. I wouldn't use resolve.alias for this

**Comment by vudh1** [comment] 2022-02-21 22:31
Hi all, please check if this helps, if not, please reopen this issue. 
```
// Install aws-crt and run again:
$ yarn add aws-crt
```

**Closed by vudh1** 2022-02-21 22:31 UTC
Labels: bug
