### ISSUE TITLE
Error objects are different in v2 and v3

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#759] opened 2020-01-20 18:46 UTC
**Describe the bug**
Error objects are different in v2 and v3

**SDK version number**
```console
$ npm list aws-sdk
└── aws-sdk@2.605.0
$ npm list @aws-sdk/client-cloudtrail
└── @aws-sdk/client-cloudtrail@1.0.0-alpha.9
```

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
```console
$ node -v
v12.14.0
```

**To Reproduce (observed behavior)**
Reproduced using the following code:
```javascript
const AWS = require("aws-sdk");
const { CloudTrail } = require("@aws-sdk/client-cloudtrail");

(async () => {
  const v2Client = new AWS.CloudTrail();

  try {
    await v2Client.createTrail({}).promise();
  } catch (e) {
    console.log("\nError returned by v2:");
    console.log(JSON.stringify(e, null, 2));
  }

  const v3Client = new CloudTrail({});

  try {
    // Try to reate trail with invalid name
    await v3Client.createTrail({});
  } catch (e) {
    console.log("\nError returned by v3:");
    console.log(JSON.stringify(e, null, 2));
  }
})();

```

Output:
```console
Error returned by v2:
{
  "message": "There were 2 validation errors:\n* MissingRequiredParameter: Missing required key 'Name' in params\n* MissingRequiredParameter: Missing required key 'S3BucketName' in params",
  "code": "MultipleValidationErrors",
  "errors": [
    {
      "message": "Missing required key 'Name' in params",
      "code": "MissingRequiredParameter",
      "time": "2020-01-20T18:42:30.422Z"
    },
    {
      "message": "Missing required key 'S3BucketName' in params",
      "code": "MissingRequiredParameter",
      "time": "2020-01-20T18:42:30.422Z"
    }
  ],
  "time": "2020-01-20T18:42:30.422Z"
}

Error returned by v3:
{
  "name": "InvalidTrailNameException",
  "__type": "InvalidTrailNameException",
  "$fault": "client",
  "$metadata": {
    "httpStatusCode": 400,
    "httpHeaders": {
      "x-amzn-requestid": "a0ef2a90-7167-4a8d-9624-a30e4f3e0729",
      "content-type": "application/x-amz-json-1.1",
      "content-length": "78",
      "date": "Mon, 20 Jan 2020 18:44:29 GMT",
      "connection": "close"
    },
    "requestId": "a0ef2a90-7167-4a8d-9624-a30e4f3e0729",
    "retries": 0,
    "totalRetryDelay": 0
  },
  "Message": "Trail name cannot be blank!"
}
```

**Expected behavior**
Creating this issue for documenting Expected behavior

**Comment by trivikr** [comment] 2020-01-20 18:50
Differences:
* v2 error object contains message in key `"message"` while v3 error object contains message in `"Message"`
  * suggestion: use `"message"` as that is used by JavaScript error constructor ([MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error))
* v2 error object documents all validation errors with code `"MultipleValidationErrors"` while v3 error object documents only first error `"InvalidTrailNameException"`
  * suggestion: Throw all validation errors at once, so users can fix all of them at once.

**Comment by kstich** [comment] 2020-01-30 22:07
The error difference described is an intended difference in SDK versions - v2 here performed client side validation ([throwing this exception code explicitly here](https://github.com/aws/aws-sdk-js/blob/cb1604ca89a077ffdb86127884292d3b18c8b4df/lib/param_validator.js#L41)) and v3 does not. This results in v3 sending the request and receiving the error shown above, and is an intentional improvement.

Closing this as the remaining issue in it is a duplicate of the more clearly described #763.

**Closed by kstich** 2020-01-30 22:07 UTC
Labels: bug report, smithy-codegen
