### ISSUE TITLE
Property 'send' does not exist on type 'DynamoDBDocumentClient'

### ISSUE THREAD

**Issue by JoshuaH-TRT** [aws/aws-sdk-js-v3#3595] opened 2022-05-06 09:28 UTC
## Describe the bug
Property 'send' does not exist on type 'DynamoDBDocumentClient'

## Your environment
Yarn PnP - Node.js with Typescript

#### SDK version number
`@aws-sdk/lib-dynamodb@3.85.0`
`@aws-sdk/client-dynamodb@3.85.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Yarn PnP v3.2.0
Node v17.9.0
Typescript v4.6.4

## Steps to reproduce
```TypeScript
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient } from "@aws-sdk/lib-dynamodb";

const client = new DynamoDBClient({});
const ddbDocClient = DynamoDBDocumentClient.from(client);
await ddbDocClient.send()
```

#### Observed behavior
Property 'send' does not exist on type 'DynamoDBDocumentClient'

#### Expected behavior
As per the [lib-dynamo readme](https://github.com/aws/aws-sdk-js-v3/blob/main/lib/lib-dynamodb/README.md) you should be able to call the bare-bones client like the following

```TypeScript
import { DynamoDBDocumentClient, PutCommand } from "@aws-sdk/lib-dynamodb";

// ... DynamoDB client creation

const ddbDocClient = DynamoDBDocumentClient.from(client);
// Call using bare-bones client and Command object.
await ddbDocClient.send(
  new PutCommand({
    TableName,
    Item: {
      id: "1",
      content: "content from DynamoDBDocumentClient",
    },
  })
);
```

**Comment by yenfryherrerafeliz** [comment] 2022-05-06 17:59
Hi @JoshuaH-TRT, thank you for reaching out. I tried to reproduce the reported behavior by using the provided environment specs, but I was not able to. 
<summary>Please see my code below:</summary>

<details>

```js
const TableName = 'MY-TABLE-NAME';
const client = new DynamoDBClient({region: 'MY-REGION'});
const ddbDocClient = DynamoDBDocumentClient.from(client);
await ddbDocClient.send(new PutCommand({
    TableName,
    Item: {
        id: "1",
        content: "content from DynamoDBDocumentClient",
    }
    })
);
```
</details>

Could you please also provide the minor version for:
- @aws-sdk/client-dynamodb

Thank you!

**Comment by JoshuaH-TRT** [comment] 2022-05-09 08:15
Thank you for checking @yenfryherrerafeliz 
@aws-sdk/client-dynamodb@3.85.0

**Comment by JoshuaH-TRT** [comment] 2022-05-09 08:19
A bit more of an update after testing this morning, it does work fine on a npm repo however using Yarn@3.2.0 with PnP i still seem to have an issue

**Comment by JoshuaH-TRT** [comment] 2022-05-09 08:31
@yenfryherrerafeliz I've pinned the issue down to the @aws-sdk/lib-dynamodb package requests the @aws-sdk/smithy-client package.

Whilst using Yarn@3.2.0 PnP, @aws-sdk/smithy-client needs to be installed but it isnt
`aws@workspace:. doesn't provide @aws-sdk/smithy-client (p5be1c), requested by @aws-sdk/lib-dynamodb`

Issue is fixed by running
`yarn add -D @aws-sdk/smithy-client`

Looking at the dependencies section [https://www.npmjs.com/package/@aws-sdk/lib-dynamodb](https://www.npmjs.com/package/@aws-sdk/lib-dynamodb) i presume the smithy-client package shouldn't be in the dev deps section?

**Comment by yenfryherrerafeliz** [comment] 2022-05-11 20:31
[@JoshuaH-TRT](https://github.com/JoshuaH-TRT), "@aws-sdk/smithy-client" is within the dependencies of "@aws-sdk/client-dynamodb", which means smithy-client package should be installed along with the installation of client-dynamodb, so that I am not sure why you had to add it manually.
Please see below the client-dynamodb dependencies:
```json
"dependencies": {
    "@aws-crypto/sha256-browser": "2.0.0",
    "@aws-crypto/sha256-js": "2.0.0",
    "@aws-sdk/client-sts": "3.85.0",
    "@aws-sdk/config-resolver": "3.80.0",
    "@aws-sdk/credential-provider-node": "3.85.0",
    "@aws-sdk/fetch-http-handler": "3.78.0",
    "@aws-sdk/hash-node": "3.78.0",
    "@aws-sdk/invalid-dependency": "3.78.0",
    "@aws-sdk/middleware-content-length": "3.78.0",
    "@aws-sdk/middleware-endpoint-discovery": "3.80.0",
    "@aws-sdk/middleware-host-header": "3.78.0",
    "@aws-sdk/middleware-logger": "3.78.0",
    "@aws-sdk/middleware-retry": "3.80.0",
    "@aws-sdk/middleware-serde": "3.78.0",
    "@aws-sdk/middleware-signing": "3.78.0",
    "@aws-sdk/middleware-stack": "3.78.0",
    "@aws-sdk/middleware-user-agent": "3.78.0",
    "@aws-sdk/node-config-provider": "3.80.0",
    "@aws-sdk/node-http-handler": "3.82.0",
    "@aws-sdk/protocol-http": "3.78.0",
    "@aws-sdk/smithy-client": "3.85.0",
    "@aws-sdk/types": "3.78.0",
    "@aws-sdk/url-parser": "3.78.0",
    "@aws-sdk/util-base64-browser": "3.58.0",
    "@aws-sdk/util-base64-node": "3.55.0",
    "@aws-sdk/util-body-length-browser": "3.55.0",
    "@aws-sdk/util-body-length-node": "3.55.0",
    "@aws-sdk/util-defaults-mode-browser": "3.85.0",
    "@aws-sdk/util-defaults-mode-node": "3.85.0",
    "@aws-sdk/util-user-agent-browser": "3.78.0",
    "@aws-sdk/util-user-agent-node": "3.80.0",
    "@aws-sdk/util-utf8-browser": "3.55.0",
    "@aws-sdk/util-utf8-node": "3.55.0",
    "@aws-sdk/util-waiter": "3.78.0",
    "tslib": "^2.3.1",
    "uuid": "^8.3.2"
  }
```

Maybe you could provide details about how you installed lib-dynamodb and client-dynamodb, and see what is different from what I did. In my environment I installed the dependencies as shown below, and I had not issues:
- yarn add @aws-sdk/lib-dynamodb@3.85.0
- yarn add @aws-sdk/client-dynamodb@3.85.0

Thanks!

**Comment by LasaleFamine** [comment] 2022-06-10 15:25
I just had the exact same problem with `@aws-sdk/client-dynamodb@3.85.0` and PNPM 7 (I don't know if this is related). After spending some hours figuring out what was happening, I tried the (incredible) solution of installing the `@aws-sdk/smithy-client` and it worked.
I want to point out a thing: locally the project was working correctly and running a simple `tsc` would correctly compile the code. The error was present only during the build on Vercel. I don't know how this is related.

**Comment by yenfryherrerafeliz** [comment] 2023-01-18 05:43
Hi, I will be closing this issue as completed since it is nailed down to Yarn PnP.

If this is still an issue please feel free to reopen or open a new issue.

Thanks!

**Closed by yenfryherrerafeliz** 2023-01-18 05:43 UTC
Labels: third-party, bug, workaround-available
