### ISSUE TITLE
DynamoDB client doesn't retry on 503 errors

### ISSUE THREAD

**Issue by agrubi** [aws/aws-sdk-js-v3#4683] opened 2023-05-01 16:57 UTC
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

DynamoDB client throws `Unexpected token < in JSON at position 0` error when it sees 503 from the server. This causes retry logic to not work.

### SDK version number

@aws-sdk/client-dynamodb@3.301.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.19.1

### Reproduction Steps

We use on-demand provisioning for dynamodb, and I think this usually happens when dynamodb tries to auto-scale or in similar cases. We get especially many of these failures during weekends, when not too many users are using the system. Basically any 503 error results it dynamodb request failing and not being retried.

### Observed Behavior

This is stack trace of the error when it happens:
```console
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /srv/binsentry/api/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:6391:21
    at tryCatcher (/srv/binsentry/api/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/srv/binsentry/api/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/srv/binsentry/api/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/srv/binsentry/api/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/srv/binsentry/api/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/srv/binsentry/api/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/srv/binsentry/api/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/srv/binsentry/api/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/srv/binsentry/api/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:466:21)
    at process.topLevelDomainCallback (node:domain:161:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
From previous event:
    at parseBody (/srv/binsentry/api/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:6389:83)
    at parseErrorBody (/srv/binsentry/api/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:6396:25)
    at deserializeAws_json1_0GetItemCommandError (/srv/binsentry/api/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:1719:21)
    at deserializeAws_json1_0GetItemCommand (/srv/binsentry/api/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:1704:16)
    at deserialize (/srv/binsentry/api/node_modules/@aws-sdk/client-dynamodb/dist-cjs/commands/GetItemCommand.js:42:71)
    at /srv/binsentry/api/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:30
    at async /srv/binsentry/api/node_modules/@aws-sdk/lib-dynamodb/dist-cjs/baseCommand/DynamoDBDocumentClientCommand.js:26:34
    at async /srv/binsentry/api/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at async /srv/binsentry/api/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /srv/binsentry/api/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
```

JSON.stringify(err) of the thrown error: 
```
{\"$metadata\":{\"attempts\":1,\"totalRetryDelay\":0}}
```

Error response I see when looking at err.$response field (just relevant parts of it):
```console
{
  statusCode: 503,
  headers: { server: 'Server', date: 'Sat, 29 Apr 2023 23:44:28 GMT', 'content-length': '98', connection: 'keep-alive', 'x-amzn-requestid': '31M60OABTV2HVTCJR6BM9KGH0JVV4KQNSO5AEMVJF66Q9ASUAAJG', 'x-amz-crc32': '2640734255' },
  body: {
    _events: {},
    _eventsCount: 2,
    socket: null,
    complete: true,
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 503,
    statusMessage: 'Service Unavailable',
  },
  req: {
    _header: 'POST / HTTP/1.1\r\n' +
      '   content-type: application/x-amz-json-1.0\r\n' +
      '   x-amz-target: DynamoDB_20120810.GetItem\r\n' +
      '   content-length: 107\r\n' +
      '   host: dynamodb.us-east-1.amazonaws.com\r\n' +
      '   x-amz-user-agent: aws-sdk-js/3.301.0\r\n' +
      '   user-agent: aws-sdk-js/3.301.0 os/linux/5.4.228-131.415.amzn2.x86_64 lang/js md/nodejs/16.20.0 api/dynamodb/3.301.0\r\n' +
      '   amz-sdk-invocation-id: ebd581c7-e108-4a47-92e5-3aaebee1afa9\r\n' +
      '   amz-sdk-request: attempt=1; max=5\r\n' +
      '   x-amz-date: 20230429T234411Z\r\n' +
      '   x-amz-security-token: ...yvornVA==\r\n' +
      '   x-amz-content-sha256: 04ecdf42e8d57bf9a030c2e0f4f6dc57d3dbbb9cedc7de763f853071946e4468\r\n' +
      '   authorization: AWS4-HMAC-SHA256 Credential=...\r\n' +
      '   X-Request-Id: bde94a50-e6e7-11ed-81c9-55a49d66aa54\r\n' +
      '   Connection: keep-alive\r\n' +
      '\r\n' +
      '',
  },
}
```

As you can see from the `amz-sdk-request` header, it only tries once, even though max attempts is set to 5: `amz-sdk-request: attempt=1; max=5\r\n`

### Expected Behavior

I am expecting request to be retried on 503 errors.

### Possible Solution

My analysis of why it happens:

```js
// node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js
const retryMiddleware = (options) => (next, context) => async (args) => {
  ...
    while (true) {
      try {
        if (protocol_http_1.HttpRequest.isInstance(request)) {
          request.headers[util_retry_1.REQUEST_HEADER] = `attempt=${attempts + 1}; max=${maxAttempts}`;
        }
        const { response, output } = await next(args);   <<<<<<<<<<<<<<<<<<<<< we get JSON error here
        retryStrategy.recordSuccess(retryToken);
        output.$metadata.attempts = attempts + 1;
        output.$metadata.totalRetryDelay = totalRetryDelay;
        return { response, output };
      }
      catch (e) {
        const retryErrorInfo = getRetyErrorInto(e); <<<<<<<<<<<<<<<<<<< this returns {errorType: "CLIENT_ERROR"}
        lastError = (0, util_1.asSdkError)(e);
        try {
          retryToken = await retryStrategy.refreshRetryTokenForRetry(retryToken, retryErrorInfo);
        }
        catch (refreshError) {
          if (!lastError.$metadata) {
            lastError.$metadata = {};
          }
          lastError.$metadata.attempts = attempts + 1;
          lastError.$metadata.totalRetryDelay = totalRetryDelay;
          throw lastError;
        }
        attempts = retryToken.getRetryCount();
        const delay = retryToken.getRetryDelay();
        totalRetryDelay += delay;
        await new Promise((resolve) => setTimeout(resolve, delay));
      }
    }
  }
};


const getRetyErrorInto = (error) => {
    const errorInfo = {
        errorType: getRetryErrorType(error), <<<<<<<<<<<<<<<< this returns "CLIENT_ERROR"
    };
    const retryAfterHint = (0, exports.getRetryAfterHint)(error.$response);
    if (retryAfterHint) {
        errorInfo.retryAfterHint = retryAfterHint;
    }
    return errorInfo;
};

const getRetryErrorType = (error) => {
    if ((0, service_error_classification_1.isThrottlingError)(error))
        return "THROTTLING";
    if ((0, service_error_classification_1.isTransientError)(error)) <<<<<<<<<< this returns false, because error is just a generic json error, not an aws error
        return "TRANSIENT";
    if ((0, service_error_classification_1.isServerError)(error))
        return "SERVER_ERROR";
    return "CLIENT_ERROR";
};


// node_modules/@aws-sdk/service-error-classification/dist-cjs/index.js
const isTransientError = (error) => {
    var _a;
    return constants_1.TRANSIENT_ERROR_CODES.includes(error.name) ||   <<<<<<<< error.name is undefined
        constants_1.NODEJS_TIMEOUT_ERROR_CODES.includes((error === null || error === void 0 ? void 0 : error.code) || "") ||   <<<<<< error.code is undefined
        constants_1.TRANSIENT_ERROR_STATUS_CODES.includes(((_a = error.$metadata) === null || _a === void 0 ? void 0 : _a.httpStatusCode) || 0); <<< the only metadata we see is: "{\"$metadata\":{\"attempts\":1,\"totalRetryDelay\":0}}"
};


// node_modules/@aws-sdk/util-retry/dist-cjs/StandardRetryStrategy.js
shouldRetry(tokenToRenew, errorInfo, maxAttempts) {
    const attempts = tokenToRenew.getRetryCount();
    return (attempts < maxAttempts &&
        tokenToRenew.hasRetryTokens(errorInfo.errorType) &&
        this.isRetryableError(errorInfo.errorType));
}
isRetryableError(errorType) {
    return errorType === "THROTTLING" || errorType === "TRANSIENT";   <<<<<<<<<<<<<<< CLIENT_ERROR is not retriable
}
```

### Additional Information/Context

This started to happen when we upgraded from SDK v2.

**Comment by RanVaknin** [comment] 2023-05-02 18:56
Hi @agrubi ,

Thanks for the in-depth analysis. The SDK should retry on 503 errors. 
From what I can see, the service responds and the deserialization fails, so the SDK can't figure out the correct error code, so it assumes its a client error. 

This would be difficult to simulate in order to get reproduce the same deserialization error. I will keep investigating. 

Thanks,
Ran~

**Comment by agrubi** [comment] 2023-05-15 13:05
We've got 22 of these errors yesterday (was quiet before that, I even thought something on the server side was fixed), so this problem still exists.

**Comment by RanVaknin** [comment] 2023-08-08 19:38
Hi @agrubi ,

You are using a really old version of the SDK. Can you update your dependencies and see if you are running into the same issue?

Thanks,
Ran~

**Comment by agrubi** [comment] 2023-08-09 20:03
I've upgraded to version `3.387.0`. Will monitor it, and update this thread next week.

**Comment by agrubi** [comment] 2023-08-14 13:54
Looks like this error was not happening in last 30 days (even before upgrading to the latest client version).

**Comment by RanVaknin** [comment] 2023-08-14 18:55
Hi @agrubi ,

This error was difficult to analyze to begin with. My guess is that the service responded with an XML response ( starts with a `<` character) and the SDK's deserializer was expecting a JSON object, hence you saw that error. 

Since this doesnt seem like an issue anymore Im going to close this. 
If this shows up again please open a new issue.

All the best,
Ran~

**Closed by RanVaknin** 2023-08-14 18:55 UTC
Labels: bug, p2
