### ISSUE TITLE
Google Translate not working

### ISSUE THREAD

**Issue by madakaheri** [aws/aws-sdk-js-v3#4443] opened 2023-02-17 05:03 UTC
## Is this TypeDoc problem ?

MacOS Monterey 12.6.3
Chrome 110.0.5481.100（Official Build）（x86_64）

![タイトルなし](https://user-images.githubusercontent.com/31895949/219553272-aaa73853-3e21-4d0a-9412-f6ea38471df9.gif)

### Links

- [AWS SDK V3 - CopyObjectCommnd](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/classes/copyobjectcommand.html)

**Comment by kellertk** [comment] 2023-02-17 19:44
Hi there. I can't seem to reproduce this problem. The page correctly translates with the Google Translate for me.

https://www.youtube.com/watch?v=iE-_a-L1Xdc

**Comment by madakaheri** [comment] 2023-02-23 17:30
@kellertk Thank you for checking.
But it doesn't work on my chrome. Safari translates just fine.
https://youtu.be/oStUVcpQCmk

**Comment by RanVaknin** [comment] 2023-02-27 21:57
Konichiwa @madakaheri 👋 

Since this is not an issue with the docs, its likely an issue with google chrome itself.
Please check out [this guide](https://www.guidingtech.com/fix-google-chrome-translate-not-working/) perhaps it would be useful. 

The SDK team can't provide recourse in this situation so I will be closing this issue.

I apologize for the inconvenience,
Ran~

**Closed by RanVaknin** 2023-02-27 21:57 UTC
Labels: documentation, bug, p3

**Comment by madakaheri** [comment] 2023-03-08 07:35
@RanVaknin Thanks for the support.
I close this issue.
