### ISSUE TITLE
Secrets Manager EPROTO error

### ISSUE THREAD

**Issue by steelbrain** [aws/aws-sdk-js-v3#3513] opened 2022-04-05 06:18 UTC
## Describe the bug

We're using Secrets Manager to initialize lambda state, and are frequently getting `write EPROTO` failure messages. It started happening recently after we upgraded from v3.41.0 to v3.58.0

#### SDK version number
`@aws-sdk/client-secrets-manager@3.58.0`

#### Is the issue in the browser/Node.js/ReactNative?

Node.js

#### Details of the browser/Node.js/ReactNative version

`Node.js 14.x` Lambda :)

## Steps to reproduce

Here's tl;dr of the lambda handler code

```js
const { SecretsManagerClient, GetSecretValueCommand } = require('@aws-sdk/client-secrets-manager')

const promiseEnv = new SecretsManagerClient({
  region: process.env.AWS_ENV_SECRET_REGION,
}).send(
  new GetSecretValueCommand({
    SecretId: process.env.AWS_ENV_SECRET_ID,
  })
)

async function handler(event, context) {
  console.log('Requesting environment variables')
  const env = await promiseEnv
  console.log('Got environment variables')
  // ....
}

module.exports = { handler }
```

#### Observed behavior

**Most** of the times, everything works, but then unexpectedly crashes at `await promiseEnv`, and `Got environment variables` is never logged

#### Expected behavior

Secrets Manager would keep working

#### Screenshots

N/A

## Additional context

<details>
<summary>Here's the raw logs:</summary>

```console
[TS] [UUID] INFO	Requesting environment variables
[TS] [UUID] ERROR	Invoke Error 	{"errorType":"Error","errorMessage":"write EPROTO","code":"EPROTO","errno":-71,"syscall":"write","$metadata":{"attempts":1,"totalRetryDelay":0},"stack":["Error: write EPROTO","    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)","    at WriteWrap.callbackTrampoline (internal/async_hooks.js:130:17)"]}
[TS] [UUID] ERROR	(node:9) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 14)\n(Use `node --trace-warnings ...` to show where the warning was created)
END RequestId: [UUID]
REPORT RequestId: [UUID]	Duration: 33.91 ms	Billed Duration: 34 ms	Memory Size: 1536 MB	Max Memory Used: 99 MB	Init Duration: 1213.34 ms
```
</details>

**Comment by semmgeorge** [comment] 2022-04-05 17:53
I got the same issue, "@aws-sdk/client-secrets-manager": "^3.53.0". And I got the same behavior: "Most of the times, everything works, but then unexpectedly crashes at await promiseEnv"

**Comment by samkotlove** [comment] 2022-04-20 13:40
Noticing this same behavior on v3.67.0

**Comment by tux86** [comment] 2022-05-19 20:42
Same thing we have serious problems with our production environment, and we are struggling with our customers since few weeks ago. The switched to environment  variables and disabled secretsManager

**Comment by ppsmol24** [comment] 2022-05-20 17:26
Same on our live environment. Initially updated @aws-sdk/client-secrets-manager from version 3.20.0 to 3.52.0. Our lambdas starting throwing spikes of the following errors : 

`error.code | EPROTO
-- | --
error.errno | -71
error.errorMessage | write EPROTO
error.errorType | Error
error.stack.0 | Error: write EPROTO
error.stack.1 | at __node_internal_captureLargerStackTrace (internal/errors.js:412:5)
error.stack.2 | at __node_internal_errnoException (internal/errors.js:542:12)
error.stack.3 | at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
error.syscall | write
errorType | AwsError
stack.0 | AwsError
stack.1 | at /var/task/packages/aws/dist/secretsManager/secretsManager.js:11:38
stack.2 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
stack.3 | at async Promise.all (index 1)
`

Upgraded then to 3.89.0 thinking the issue may have been fixed in the meantime but encountering the same behavior

**Comment by hikarunoryoma** [comment] 2022-07-20 16:10
We are also seeing this issue and have opted for the work around to downgrade to 3.20.0.  Any updates @RanVaknin?

**Comment by jjpepper** [comment] 2022-07-26 06:43
@AllanZhengYP @RanVaknin is this an issue you've seen.  We have been seeing it a quite a few times in recent weeks, with a very recent aws-sdk v3.

**Comment by jjpepper** [comment] 2022-07-26 08:44
@AllanZhengYP @RanVaknin we've investigated this a bit more.  It seems that we are seeing the EPROTO error after the lambda times out, and then tries to re-initialise (i.e. we see our cold start code again in the same log group).

**Comment by sans-jmansfield** [comment] 2022-08-31 18:57
We recently began moving a variety of microservices from AWS SDK v2 to v3 and have seen flavors of this error in several repos. Most recently with `3.154.0`

**Comment by RanVaknin** [comment] 2022-09-01 17:35
Hi All,

Unfortunately Im not able to reproduce this issue. We have multiple issues opened for the same EPROTO error, I tried reproducing with 2 customer examples and never ran into this. 
I assigned it to the dev team to take a look.

**Comment by jjpepper** [comment] 2022-09-01 21:32
One of my colleagues had done some analysis and suspects the issue is due
to the clock being momentarily wrong when the lambda starts up.

**Comment by Dantemss** [comment] 2022-10-17 15:02
I too have encountered this over and over and my educated guess is that this happens when some (unrelated) code blocks the event loop a bit too long. AWS services seem to have short timeouts when dealing with connections and the SDK does not retry them, so blocking the JS event loop would delay the connection handling and cause the connection fail with this error.

**Comment by bdevore17** [comment] 2022-10-19 18:41
Having the same issue.

**Comment by bdevore17** [comment] 2022-10-19 18:45
@RanVaknin What's the status here? This is crashing mission critical processes for us and its been assigned P1 for over a month...

**Comment by bdevore17** [comment] 2022-10-26 14:06
@RanVaknin ?????

**Comment by trivikr** [comment] 2022-11-11 22:36
On quick revisit during review meeting for issues with `p1` labels, we noticed that this issue is likely in Node.js. Search results https://github.com/search?q=repo%3Anodejs%2Fnode+EPROTO&type=issues

We need to find out whether the issue is with the Node.js setup which Lambda follows, or some Node.jsconfiguration which SDK sets, or a bug is Node.js core itself.

The requirement is to provide a minimal repro code which makes multiple secret manager getSecretValue calls. This will help us to log more information, and find out if the issue is specific to Lambda, Node.js or SDK.

For reference, here is a package which attempted to repro npm ping test failure from CodeBuild https://github.com/trivikr/aws-codebuild-npm-ping-test

**Comment by hikarunoryoma** [comment] 2022-12-15 18:47
Has anyone found that using a newer version of Node makes this issue go away?  I am planning on upgrading my version of Node, but I was curious if anyone else has already tried this.  

Like the OP i am also using 14.X, but I am planning on updating to 18.X

**Comment by michaelmrn** [comment] 2022-12-22 11:45
We are also seeing this error fairly regularly now and wondering if a node upgrade would help - also node 14 and on latest sdk packages we are using

**Comment by james-m-hall** [comment] 2023-01-10 19:01
We also see this error fairly frequently with @aws-sdk/client-secrets-manager v3.131.0 and a Node 14.x lambda environment.

It looks like the following issues are closely related which implies it may not exclusively be a secrets manager issue:

- https://github.com/aws/aws-sdk-js-v3/issues/3219
- https://github.com/aws/aws-sdk-js-v3/issues/3476

**Comment by dgoemans** [comment] 2023-01-17 09:00
Regularly getting this with the SSM client v3.229.0.
https://stackoverflow.com/questions/75143854/ssm-client-failing-to-get-parameters-from-lambda-in-startup

**Comment by dgoemans** [comment] 2023-01-18 11:40
Yesterday after posting the above comment, i decided to upgrade my lambdas to Node 16, and so far haven't had this happen. It might be speaking too soon, but @RanVaknin maybe something to pass on to the dev team investigating.

cc @hikarunoryoma (since you asked)

**Comment by hikarunoryoma** [comment] 2023-01-18 13:49
@dgoemans Thanks for the heads up! Looking forward to upgrading my lambdas next month and will follow up if I see success on my end!

**Comment by jeeteshchel** [comment] 2023-02-07 18:24
We tried Lambda extension for fetching secrets from secrets manager and that has worked quite well https://docs.aws.amazon.com/secretsmanager/latest/userguide/retrieving-secrets_lambda.html

**Comment by michaelmrn** [comment] 2023-03-02 09:52
An upgrade to Node18 appears to have resolved this for us

**Comment by dgoemans** [comment] 2023-03-02 09:57
Indeed, 6 weeks after upgrading to Node 16 I haven't seen the issue again. Seems to be Node 14 only.

**Closed** 2023-06-27 22:12 UTC
Labels: bug, p3
