### ISSUE TITLE
SDK v3 upload has three times as many API calls vs v2 for some streams

### ISSUE THREAD

**Issue by Linkgoron** [aws/aws-sdk-js-v3#2581] opened 2021-07-14 09:45 UTC
## Describe the bug

We've recently upgraded to SDK v3 from SDK v2, and we've noticed that in some of our services, those using `upload`, the number of API calls has _tripled_ vs SDK v2 for _a lot_ of our smaller uploads, and obviously this also noticeably increased everything related to more API calls to S3. The reason is that SDK v2 `upload` has specific [code for streams](https://github.com/aws/aws-sdk-js/blob/master/lib/s3/managed_upload.js#L480) that finish before the upload starts, and uses a single `PUT` command to upload the file in one go. In SDK v3, lib-storage does not have this optimization, and always uses the create/upload/complete commands.

This kind of behaviour was very unexpected for us when we upgraded from an older version to a newer version, and we definitely did not expect a tripling of the number API calls. Is there a specific reason why this behavior was not ported to v3, or any reason that this will not get ported in the future?

Note that the [upgrade guide](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md#s3-multipart-upload) claims that `In v3, @aws-sdk/lib-storage package is available. It supports all the features offered in v2 upload(), and supports both Node.js and browsers runtime.`

**Comment by ajredniwja** [comment] 2021-07-15 06:40
Hey @Linkgoron thanks for bringing this up, can you please share your use case and the code you were using with v2 and v3? I have personally not encountered this.

**Comment by Linkgoron** [comment] 2021-07-15 06:53
Yes, we're using [Multer](https://github.com/expressjs/multer) and [Multer-s3](https://github.com/anacronw/multer-s3/blob/168eb90c0f050760f791f1e97ced72253e01a6aa/index.js#L182) to upload files using express, and we we've [forked Multer-s3](https://github.com/testimio/multer-s3/blob/264071769f0073520d6c20d65e6b2dfdb609bb3a/index.js#L212) to use the lib-storage v3 sdk instead of the v2 sdk.

**Comment by MoLow** [comment] 2021-07-15 13:29
Hi, @ajredniwja I faced this as well.
the usecase is simple - upgrading from sdkV2 to sdkV3 resulted in tripling our s3 costs:
![image](https://user-images.githubusercontent.com/8221854/125796075-97791e12-e0ab-4ae4-b72f-2fb5645e147b.png)

**Comment by MoLow** [comment] 2021-07-15 13:31
Hi, @ajredniwja I faced this as well.
the usecase is simple - upgrading from sdkV2 to sdkV3 resulted in tripling our s3 costs:
![image](https://user-images.githubusercontent.com/8221854/125796354-061282a1-3338-4157-b53e-4262e91fa791.png)

**Comment by AllanZhengYP** [comment] 2021-07-16 21:36
@Linkgoron @MoLow 

Is the object you are uploading mostly smaller than 5mb? The API call graph indicates the difference: it previously uses `putObject` API but it switched to use multipart upload API later. In v2, when the object smaller than 5mb, the `s3.upload()` will use the `putObject` API by default. Only when the object is bigger than 5 mb will it use the multipart upload API. 

Whereas in v3, you are using the multipart upload `upload()`directly, which will make `StartMultipartUpload`, `UploadPart`, and `CompleteMultipartUpload` API calls. It is intended for uploading bigger object, with ability to pause and resume the upload. In these case, S3's `PutObject` API is more preferrable over the `upload()`. 

I will create a feature request for falling back to use `PutObject` API when the object is smaller than certain threshold.

**Comment by Linkgoron** [comment] 2021-07-17 11:49
> @Linkgoron @MoLow
> 
> Is the object you are uploading mostly smaller than 5mb? 

In general, for our use case, this code is generic on the server and doesn't know the size of the files that it uploads. However, it looks like the files are mostly small.

>The API call graph indicates the difference: it previously uses `putObject` API but it switched to use multipart upload API later. In v2, when the object smaller than 5mb, the `s3.upload()` will use the `putObject` API by default. Only when the object is bigger than 5 mb will it use the multipart upload API.

Note that [the code](https://github.com/aws/aws-sdk-js/blob/master/lib/s3/managed_upload.js#L480) that I referenced in the OP that handles this is v2, also some [specific code ](https://github.com/aws/aws-sdk-js/blob/8533bd2d2336c00f95efb63702ebc10af2ddc12b/lib/s3/managed_upload.js#L189) for streams (not just small buffers).

> Whereas in v3, you are using the multipart upload `upload()`directly

Per the docs, `s3.upload` and the lib-storage `upload` _should_ behave the same.

> I will create a feature request for falling back to use `PutObject` API when the object is smaller than certain threshold.

Thanks. Note that I get that smaller files that are chunked should probably get uploaded using multi-part (if it takes time to send them to the server), but if the request has already transferred to the server (even though it's a stream), it should use PUT when possible just like aws-sdk v2 does.

**Comment by AllanZhengYP** [comment] 2021-08-06 21:25
Closing this as the root cause has been tracked at #2593

**Closed by AllanZhengYP** 2021-08-06 21:25 UTC
Labels: guidance
