### ISSUE TITLE
EMFIL error when using SQS and DynamoDB for large amount of data

### ISSUE THREAD

**Issue by Angoulema** [aws/aws-sdk-js-v3#5010] opened 2023-07-25 11:19 UTC
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Related to [this issue](https://github.com/aws/aws-sdk-js-v3/issues/4964).
We still have errors, and after more thorough investigation it was identified, that errors occur not only while using SQS client, but while using DynamoDB client as well. 

Case: our lambda reads kafka topics (may simultaneously read up to 6 topics and process messages from them), and during high load (from 1000 messages in topic(s)) we see EMFIL errors during processing. Errors do not occur at the beginning of the processing, usually after some amount was already processed. E.g. our log timeline looks like this usually:
![image](https://github.com/aws/aws-sdk-js-v3/assets/70232156/84fa12eb-beb5-47f1-b294-9938f0b682fc)
Where blue color messages are ok, red and dark red - error messages.

So, when using AWS SDK@3 we encounter errors EMFIL, it seems that there're not enough descriptors. But the same operations were ok with v2, problems surfaced only after moving to v3.
Please see details below.

### SDK version number

@aws-sdk/client-sqs@3.363.0, @aws-sdk/client-dynamodb@3.363.0, @aws-sdk/node-http-handler@3.374.0, @aws-sdk/util-dynamodb@3.365.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node v16.17.1

### Reproduction Steps

Simplified example of our code is below. I tried to include all steps which may help to solve the issue.

```js
import { SendMessageRequest, SQSClient, SendMessageCommand } from '@aws-sdk/client-sqs'
import { NodeHttpHandler } from '@aws-sdk/node-http-handler';
import https from 'https';
import { MSKEvent } from 'aws-lambda';
import {
  DynamoDBClient, PutItemCommand
} from '@aws-sdk/client-dynamodb';
import { marshall } from '@aws-sdk/util-dynamodb';

let isInitialized = false;
let failHandler: FailHandler;
let sqs: SQSClient;
let sqsQueueUrl: SendMessageRequest['QueueUrl'] | undefined;

const region = 'aws-region';
const sqsName = 'sqs-name';
const dlqName = 'dlq-name';
const tableName = 'table-name';

type LambdaFailure = {
  reason: string;
  stack: string;
  message: string;
  event: Record<string, unknown>
};

type Message = {
  id: string;
  dates: string[]; // '2023-07-25'
  toBeSendNow: boolean;
  [otherFileds: string]: unknown;
}

async function initSqs() {
  const agent = new https.Agent({
    maxSockets: 25
  });
  sqs = new SQSClient({
    region,
    requestHandler: new NodeHttpHandler({
      httpsAgent: agent
   })
  });
  sqsQueueUrl = getSqsQueueUrl(sqsName);
}

class FailHandler {
  private sqs: SQSClient;

  private readonly queueUrl: string;

  constructor(private sqsOptions: { queueName: string }) {
    this.sqs = new SQSClient({
      region
    });
    this.queueUrl = getSqsQueueUrl(sqsOptions.queueName);
  }

  public async handle(msg: LambdaFailure): Promise<void> {
    try {
      const command = new SendMessageCommand({
        MessageBody: JSON.stringify(msg),
        QueueUrl: this.queueUrl
      });
      await this.sqs.send(command);
    } catch (err) {
      console.error('failed to send event', err); // here we get EMFIL printed to log
    }
  }
}

class Repository {
  private readonly connection: DynamoDBClient;

  private readonly table: string = tableName;

  constructor() {
    this.connection = new DynamoDBClient({});
  }

  public async addData(entity: Message): Promise<void> {
    const {
      id, dates
    } = entity;
    
    const key = `${id}${dates[0]}`
    const item = {
      key,
      event: JSON.stringify(entity)
    };
    const command = new PutItemCommand({
      TableName: this.table,
      Item: marshall(item)
    });

    await this.connection.send(command); // at this point errors occur
  }
}

class SQSService {
  constructor(
    private readonly sqs: SQSClient,
    private readonly queueUrl: SendMessageRequest['QueueUrl'] | undefined
  ) {
    this.sqs = sqs;
    this.queueUrl = queueUrl;
  }

  public async sendMessageToSQS(message: Message): Promise<void> {
    const command = new SendMessageCommand({
      QueueUrl: this.queueUrl,
      MessageBody: JSON.stringify({
        message
      })
    });
    await this.sqs.send(command); // at this point errors occur
  }
}

class MessagesService {
  constructor(
    private readonly dynamoRepo: Repository,
    private readonly sqsService: SQSService,
    private readonly failHandler: FailHandler
  ) {
    this.failHandler = failHandler;
  }
  private async sendNowMessages(message: Message | null) {
    if (!message) {
      return;
    }
    await this.sqsService.sendMessageToSQS(message);
  }

  private async handleOtherMessages(messages: Message[]) {
    if (!messages.length) {
      return;
    }
    const promises = messages.map((message) => this.dynamoRepo.addData(message));
    await Promise.all(promises);
  }

  public handleMessage = async (kafkaMessage: Message): Promise<void> => {
    let nowMessage: Message | null = null;
    const otherMessages: Message[] = [];

    if (kafkaMessage.toBeSendNow) {
      nowMessage = kafkaMessage;
    }
    for (const date of kafkaMessage.dates) {
      const msg = {
        ...kafkaMessage,
        dates: [date]
      };
      otherMessages.push(msg);
    }

    try {
      await this.sendNowMessages(nowMessage);
      await this.handleOtherMessages(otherMessages);
    } catch (err) {
      await this.failHandler.handle({
        event: kafkaMessage as any,
        message: (err as Error).message,
        reason: 'reason',
        stack: (err as Error).stack ?? ''
      });
    }
    
  }
}

async function handler(event: MSKEvent): Promise<void> {
  if (!isInitialized) {
    isInitialized = true;
    failHandler = new FailHandler({ queueName: dlqName });
    await initSqs();
  }
  try {
    // here messages are decoded
    // let's just take messages as an array
    const messages: Message[] = [
      {
        id: '1',
        dates: ['2024-01-01', '2025-01-03', '2025-03-01'],
        toBeSendNow: true
      }
    ]; // from 25 to 75 items of Message type (see above)

    const sqsService = new SQSService(sqs, sqsQueueUrl);
    const dynamoDbRepo = new Repository();
    const messageService = new MessagesService(dynamoDbRepo, sqsService, failHandler);

    const messagePromises = messages.map((message) => messageService.handleMessage(message));
    await Promise.all(messagePromises);
  } catch (err) {
    console.error('Lambda failed', err);
    throw err;
  }
}
```

If you need, I may generate for you messages by indicated simplified interface.

### Observed Behavior

Errors when using SQS:
```
"err": {
            "type": "Error",
            "message": "connect EMFILE 3.250.244.21:443 - Local (undefined:undefined)",
            "stack": "Error: connect EMFILE 3.250.244.21:443 - Local (undefined:undefined)\n    at internalConnect (node:net:1041:16)\n    at defaultTriggerAsyncIdScope (node:internal/async_hooks:464:18)\n    at GetAddrInfoReqWrap.emitLookup [as callback] (node:net:1187:9)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:8)",
            "errno": -24,
            "code": "EMFILE",
            "syscall": "connect",
            "address": "3.250.244.21",
            "port": 443,
            "$metadata": {
                "attempts": 1,
                "totalRetryDelay": 0
            }
        }
```
```
"err": {
            "type": "Error",
            "message": "getaddrinfo EMFILE sqs.eu-west-1.amazonaws.com",
            "stack": "Error: getaddrinfo EMFILE sqs.eu-west-1.amazonaws.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)",
            "errno": -24,
            "code": "EMFILE",
            "syscall": "getaddrinfo",
            "hostname": "sqs.eu-west-1.amazonaws.com",
            "$metadata": {
                "attempts": 1,
                "totalRetryDelay": 0
            }
        }
```

Errors when using DynamoDB:
```
"err": {
            "type": "Error",
            "message": "connect EMFILE 52.119.242.12:443 - Local (undefined:undefined)",
            "stack": "Error: connect EMFILE 52.119.242.12:443 - Local (undefined:undefined)\n    at internalConnect (node:net:1041:16)\n    at defaultTriggerAsyncIdScope (node:internal/async_hooks:464:18)\n    at GetAddrInfoReqWrap.emitLookup [as callback] (node:net:1187:9)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:8)",
            "errno": -24,
            "code": "EMFILE",
            "syscall": "connect",
            "address": "52.119.242.12",
            "port": 443,
            "$metadata": {
                "attempts": 1,
                "totalRetryDelay": 0
            }
        }
```
```
"err": {
            "type": "Error",
            "message": "getaddrinfo EMFILE dynamodb.eu-west-1.amazonaws.com",
            "stack": "Error: getaddrinfo EMFILE dynamodb.eu-west-1.amazonaws.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)",
            "errno": -24,
            "code": "EMFILE",
            "syscall": "getaddrinfo",
            "hostname": "dynamodb.eu-west-1.amazonaws.com",
            "$metadata": {
                "attempts": 1,
                "totalRetryDelay": 0
            }
        }
```

### Expected Behavior

No EMFILE  errors.

### Possible Solution

If we knew we'd open PR, not issue :)

**Comment by jooleeanh** [comment] 2023-08-03 08:51
We have the same issue here. We have multiple services with high traffic where an important number of lambda invocations started to fail with these errors. They also use SQS and DynamoDB. We're attempting various fixes (sharing clients, closing them), but while these solutions reduce the amount of errors, they don't eliminate them completely. If we had none of these issues in the previous SDK version, and have them now with the v3, is it possible that the v3 handles the connections differently (more conservative) ?

**Comment by Angoulema** [comment] 2023-08-04 11:20
@RanVaknin sorry to bother you, but maybe anyone could look into this problem?

**Comment by remibruyere** [comment] 2023-08-07 16:04
I'm facing the same problem. We are generating around 10k calls to SQS. We haven't any problem with SDK v2 but we got this issue with the V3. This is extremely annoying, we have to reduce our call rate and slow down our app.

**Comment by RanVaknin** [comment] 2023-08-08 16:42
Hi @Angoulema ,

I've spent a few good hours trying to mimic your setup to the best of my ability. The code part you provided is the straight forward part, the hard part was to mimic the throughput and setting up all the components to talk to each other in a way that simulates the scenario you were talking about:
>our lambda reads kafka topics (may simultaneously read up to 6 topics and process messages from them), and during high load (from 1000 messages in topic(s)) we see EMFIL errors during processing. 

Since Im not familiar with Kafka, I used Kinesis to simulate the same kind of throughput. In my Kinesis setup I've configured a single stream with 6 shards. Each shard in Kinesis can be equated to a Kafka topic in terms of parallel processing. Thus, the 6 shards are designed to mimic the concurrent processing of 6 Kafka topics. 

Each shard can handle up to 1MB or 1,000 records per second for writes. With 6 shards, a stream can handle up to 6,000 records per second. This mirrors the high load scenario in the Kafka setup.

My Kinesis producer code:

```js
// producer.js
const { KinesisClient, PutRecordsCommand } = require("@aws-sdk/client-kinesis");

const kinesisClient = new KinesisClient({ region:  "us-east-1" });

async function putRecords(messages) {
    const batchSize = 500;

    for (let i = 0; i < messages.length; i += batchSize) {
        const batch = messages.slice(i, i + batchSize);

        const records = batch.map(message => ({
            Data: Buffer.from(JSON.stringify(message)),
            PartitionKey: message.id 
        }));

        const params = {
            Records: records,
            StreamName: "foo-stream"
        };

        try {
            const response = await kinesisClient.send(new PutRecordsCommand(params));
            console.log(`Sent batch starting from ${i}: ${response.Records.length} records with ${response.FailedRecordCount} failures.`);
        } catch (err) {
            console.error(`Failed to send batch starting from ${i} records:`, err);
        }
    }
}


const main = async () => {
    const messagesPerTopic = 1000;
    const totalTopics = 6;

    for (let topic = 0; topic < totalTopics; topic++) {
        const messages = Array.from({ length: messagesPerTopic }, (_, idx) => ({
            id: `msg-${topic}-${idx}`,
            date: new Date().toISOString(),
            topicNumber: topic
        }));
        await putRecords(messages);
    }
};

main()
```
The producer code generates and sends batches of messages to a Kinesis stream. It creates 6 sets of 1,000 messages each (representing 6 topics), with each message batched in groups of 500, and then pushes these batches to the stream, using the message ID as the partition key.

This is hooked into my Lambda function as a trigger:
```
Activate trigger: Yes
Batch size: 1000
Batch window: None
Concurrent batches per shard: 1
Last processing result: OK
Maximum age of record: -1
On-failure destination: None
Report batch item failures: No
Retry attempts: -1
Split batch on error: No
Starting position: LATEST
Tumbling window duration: None
```

 The lambda code looks a bit different than yours as it went through several iterations have a very similar structure:

```js
const { SQSClient, SendMessageCommand } = require('@aws-sdk/client-sqs');
const { NodeHttpHandler } = require('@aws-sdk/node-http-handler');
const https = require('https');
const { DynamoDBClient, PutItemCommand } = require('@aws-sdk/client-dynamodb');
const { marshall } = require('@aws-sdk/util-dynamodb');

let isInitialized = false;
let failHandler;
let sqs;
let sqsQueueUrl;

const region = 'us-east-1';
const sqsName = 'sqs-name';
const dlqName = 'dlq-name';
const tableName = 'table-name';

async function initSqs() {
    const agent = new https.Agent({
        maxSockets: 25
    });
    sqs = new SQSClient({
        region,
        requestHandler: new NodeHttpHandler({
            httpsAgent: agent
        })
    });
    sqsQueueUrl = `https://sqs.us-east-1.amazonaws.com/REDACTED/${sqsName}`;
}

class FailHandler {
    constructor(sqsOptions) {
        this.sqsOptions = sqsOptions;
        this.sqs = new SQSClient({ region });
        this.queueUrl = `https://sqs.us-east-1.amazonaws.com/REDACTED/${this.sqsOptions.queueName}`;
    }

    async handle(msg) {
        try {
            const command = new SendMessageCommand({
                MessageBody: JSON.stringify(msg),
                QueueUrl: this.queueUrl
            });
            await this.sqs.send(command);
        } catch (err) {
            console.error('Error in FailHandler:', err);
            throw err;
        }
    }
}

class Repository {
    constructor() {
        this.connection = new DynamoDBClient({});
        this.table = tableName;
    }

    async addData(record) {
        const id = Math.random().toString(36).substr(2, 9);
  

        const item = {
          id: id,  
          event: JSON.stringify(record)
        };

        const command = new PutItemCommand({
          TableName: this.table,
          Item: marshall(item, { removeUndefinedValues: true })
        });

        try {
            await this.connection.send(command);
        } catch (err) {
            throw err;  
        }
    }
}


class SQSService {
    constructor(sqs, queueUrl) {
        this.sqs = sqs;
        this.queueUrl = queueUrl;
    }

    async sendMessageToSQS(message) {
        const command = new SendMessageCommand({
            QueueUrl: this.queueUrl,
            MessageBody: JSON.stringify({ message })
        });
        try {
            await this.sqs.send(command);
        } catch (err) {
            console.error('Error in SQSService:', err);
            throw err;
        }
    }
}

class MessagesService {
    constructor(dynamoRepo, sqsService, failHandler) {
        this.dynamoRepo = dynamoRepo;
        this.sqsService = sqsService;
        this.failHandler = failHandler;
    }

    async sendNowMessages(message) {
        if (!message) {
            console.log("There are no messages to send now!");
            return;
        }
        await this.sqsService.sendMessageToSQS(message);
    }

    async handleOtherMessages(messages) {
        if (!messages.length) {
            return;
        }    
        const results = await Promise.all(messages.map(async (message) => {
            try {
                await this.dynamoRepo.addData(message);
                return { success: true, message: null };
            } catch (err) {
                console.error('Error while adding a message:', err);
                return { success: false, error: err.message };
            }
        }));
    
        const failedMessages = results.filter(result => !result.success);
        if (failedMessages.length > 0) {
            console.error(`Failed to process ${failedMessages.length} messages.`, failedMessages);
        } else {
            console.log("MessagesService: Handled other messages successfully.");
        }
    }


    async handleMessage(kinesisMessage) {
        try {
            if (kinesisMessage.type === 'SEND_NOW') {
                await this.sendNowMessages(kinesisMessage);
            } else {
                await this.handleOtherMessages([kinesisMessage]); 
            }
        } catch (err) {
            console.error("Error in MessagesService:", err);
            await this.failHandler.handle({
                event: kinesisMessage,
                message: err.message,
                reason: 'reason',
                stack: err.stack ?? ''
            });
            throw err;
        }
    }

}

exports.handler = async (event, context) => {
    if (!isInitialized) {
        isInitialized = true;
        failHandler = new FailHandler({ queueName: dlqName });
        try {
            await initSqs();
        } catch (err) {
            console.error('Error during initialization in handler:', err);
            throw err;
        }
    }

    try {
        const messages = event.Records.map(record => {
            let payload = Buffer.from(record.kinesis.data, 'base64');
            return JSON.parse(payload);
        });

        const sqsService = new SQSService(sqs, sqsQueueUrl);
        const dynamoDbRepo = new Repository();
        const messageService = new MessagesService(dynamoDbRepo, sqsService, failHandler);

        const messagePromises = messages.map((message) => messageService.handleMessage(message));
        await Promise.all(messagePromises);
    } catch (err) {
        console.error('Top-level Lambda error:', err);
        throw err;
    }
};
```

Lambda setup:
Memory: 128MB
Ephemeral storage: 2000MB

------

### Result:
All records are streamed correctly into lambda, and lambda is piping all the data into dynamo successfuly. My DLQ is empty as there are no failures. 

Would you mind giving my setup a look and see if yours is setup differently? If you see something obvious that can be configured differently to force an EMFILE error, let me know and I can try to tweak this. 

--- 

A note to all the others upvoting / commenting on the thread:  Please provide as much information as possible as this is not reproducible at this moment.

Thanks,
Ran~

**Comment by kuhe** [comment] 2023-08-08 18:08
try initializing the DynamoDBClient that is used in `new Repository` outside of the handler code path.

**Comment by satheesh-anecure** [comment] 2023-08-08 19:08
This gives me the same  "connect EMFILE 3.250.244.21:443 - Local (undefined:undefined)", error,
`import {S3} from "@aws-sdk/client-s3"

export const handler = async (event) => {
  // TODO implement
  const promises = [];
  for(let i=0;i<1200;i++){
    const s3 = new S3({
    })
    promises.push( s3.getObject({
      Bucket: "bucketname",
      Key: "filename"
    }));
  }
  await Promise.all(promises);
  const response = {
    statusCode: 200,
    body: JSON.stringify('Hello from Lambda!'),
  };
  return response;
};`

 but my actual app flow which uses a combination of S3, SES, and SQS gives the following
`
SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_homedir returned EMFILE (too many open files)    at getHomeDir (/var/runtime/node_modules/@aws-sdk/shared-ini-file-loader/dist-cjs/getHomeDir.js:14:29)    at getCredentialsFilepath (/var/runtime/node_modules/@aws-sdk/shared-ini-file-loader/dist-cjs/getCredentialsFilepath.js:7:128)    at loadSharedConfigFiles (/var/runtime/node_modules/@aws-sdk/shared-ini-file-loader/dist-cjs/loadSharedConfigFiles.js:11:76)    at /var/runtime/node_modules/@aws-sdk/node-config-provider/dist-cjs/fromSharedConfigFiles.js:8:102    at /var/runtime/node_modules/@aws-sdk/property-provider/dist-cjs/chain.js:11:28    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)    at async coalesceProvider (/var/runtime/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:14:24)    at async Object.useDualstackEndpoint (/var/runtime/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:26:28)    at async getEndpointFromRegion (/var/runtime/node_modules/@aws-sdk/config-resolver/dist-cjs/endpointsConfig/utils/getEndpointFromRegion.js:12:34)    at async buildHttpRpcRequest (/var/runtime/node_modules/@aws-sdk/client-sqs/dist-cjs/protocols/Aws_query.js:2157:68) {  code: 'ERR_SYSTEM_ERROR',  info: {    errno: -24,    code: 'EMFILE',    message: 'too many open files',    syscall: 'uv_os_homedir'  },  errno: [Getter/Setter: -24],  syscall: [Getter/Setter: 'uv_os_homedir']} | 2023-08-04T08:02:16.681Z db9119e3-a7ff-5142-b713-44a5155e1708 INFO Error in send message to queue: { QueueUrl: 'https://sqs.us-west-2.amazonaws.com/453952239310/SlackNotificationEventQueue', MessageAttributes: { event: { DataType: 'String', StringValue: 'MarketingEventFailure' } }, MessageBody: '{"event":"MarketingEventFailure","value":"Error in sending marketing message on attempt 1 for user: UThk86PnCDAL Not a retryable Error.. Mail not sent to UThk86PnCDAL Error: connect EMFILE 34.217.168.113:443 - Local (undefined:undefined)"}' } SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_homedir returned EMFILE (too many open files) at getHomeDir (/var/runtime/node_modules/@aws-sdk/shared-ini-file-loader/dist-cjs/getHomeDir.js:14:29) at getCredentialsFilepath (/var/runtime/node_modules/@aws-sdk/shared-ini-file-loader/dist-cjs/getCredentialsFilepath.js:7:128) at loadSharedConfigFiles (/var/runtime/node_modules/@aws-sdk/shared-ini-file-loader/dist-cjs/loadSharedConfigFiles.js:11:76) at /var/runtime/node_modules/@aws-sdk/node-config-provider/dist-cjs/fromSharedConfigFiles.js:8:102 at /var/runtime/node_modules/@aws-sdk/property-provider/dist-cjs/chain.js:11:28 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async coalesceProvider (/var/runtime/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:14:24) at async Object.useDualstackEndpoint (/var/runtime/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:26:28) at async getEndpointFromRegion (/var/runtime/node_modules/@aws-sdk/config-resolver/dist-cjs/endpointsConfig/utils/getEndpointFromRegion.js:12:34) at async buildHttpRpcRequest (/var/runtime/node_modules/@aws-sdk/client-sqs/dist-cjs/protocols/Aws_query.js:2157:68) { code: 'ERR_SYSTEM_ERROR', info: { errno: -24, code: 'EMFILE', message: 'too many open files', syscall: 'uv_os_homedir' }, errno: [Getter/Setter: -24], syscall: [Getter/Setter: 'uv_os_homedir'] }
-- | --


`

**Comment by RanVaknin** [comment] 2023-08-08 19:17
@satheesh-anecure ,

You are creating an s3 client for each network call. 
You need to create it **once** in the global scope:

```diff
import {S3} from "@aws-sdk/client-s3"

+const s3 = new S3({})


export const handler = async (event) => {
  // TODO implement
  const promises = [];
  for(let i=0;i<1200;i++){
-    const s3 = new S3({})
    promises.push( s3.getObject({
      Bucket: "bucketname",
      Key: "filename"
    }));
  }
  await Promise.all(promises);
  const response = {
    statusCode: 200,
    body: JSON.stringify('Hello from Lambda!'),
  };
  return response;
};
```

Thanks,
Ran~

**Comment by UladzislauKudravets** [comment] 2023-08-18 08:35
Hello,
I've faced the same problem. In general terms, the lambda receives a 100-message batch and should send the same number of messages to SQS.
I measured the number of descriptors on the lambda runs on second and third versions of aws-sdk. It is expected to create a number of descriptors for sending messages equal to the size of the batch - that happens on both versions of sdk. In a situation where there is only one lambda run, namely in a situation where open descriptors will not be reused, I saw that after the messages have been sent, the second version deletes ALL descriptors for sending messages and the third version sometimes leaves some open. But if more messages are sent to this hot lambda, the initial number of descriptors will be larger than at the first run. It turns out that the number of descriptors will grow during subsequent lambda runs until we get an EMFILE error.

Surely if I destroy SQS client at the end of each execution of the lambda, then the number of descriptors becomes equal to the initial one and that helps to get rid of the problem, but I'm not sure if it should work like that.

**Comment by Angoulema** [comment] 2023-08-23 06:34
Hi @RanVaknin,
Sorry for not answering at once, I was on vacation.

It seems that our problem is similar to the one @UladzislauKudravets has. The problem occurs when hot lambda keeps processing incoming messages. Could you please change lambda batch to 75 messages and send the same 1000 messages to it? I think this way the problem will be reproduced.

**Comment by Angoulema** [comment] 2023-09-04 11:14
Hi @RanVaknin ,
Could you clarify what initialization do you mean? In our code, resources are initialized once per lambda ran, as I can see.

For now we use @UladzislauKudravets 's tip and destroy clients after each execution of lambda.

**Comment by RanVaknin** [comment] 2023-09-13 18:37
@Angoulema ,


```js
async function handler(event: MSKEvent): Promise<void> {
  if (!isInitialized) {
    isInitialized = true;
    failHandler = new FailHandler({ queueName: dlqName });
    await initSqs();
  }
  try {
    // here messages are decoded
    // let's just take messages as an array
    const messages: Message[] = [
      {
        id: '1',
        dates: ['2024-01-01', '2025-01-03', '2025-03-01'],
        toBeSendNow: true
      }
    ]; // from 25 to 75 items of Message type (see above)

    const sqsService = new SQSService(sqs, sqsQueueUrl);
    const dynamoDbRepo = new Repository(); // <--- you are initializing the client inside your handler. It should be iniitalized outside of the handler in the global scope.
    const messageService = new MessagesService(dynamoDbRepo, sqsService, failHandler);

    const messagePromises = messages.map((message) => messageService.handleMessage(message));
    await Promise.all(messagePromises);
  } catch (err) {
    console.error('Lambda failed', err);
    throw err;
  }
}
```

Thanks,
Ran~

**Closed by RanVaknin** 2023-09-13 18:37 UTC
Labels: bug, p2

**Comment by Angoulema** [comment] 2023-09-14 07:03
@RanVaknin , and how it can explain errors on _SQS_, which is initialized once?
