### ISSUE TITLE
@aws-sdk/client-sso@3.264.0 does not exist

### ISSUE THREAD

**Issue by j-mishra** [aws/aws-sdk-js-v3#4399] opened 2023-02-03 14:19 UTC
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Getting error while installing package @aws-sdk/client-sso@3.264.0

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-sdk/client-sso@3.264.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:

### SDK version number

@aws-sdk/client-sso@3.264.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.14.2

### Reproduction Steps

While performing a npm run build, the build failed with above error.

### Observed Behavior

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-sdk/client-sso@3.264.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

### Expected Behavior

Should install the version mentioned above as it is available in package repository.

**Comment by lnxslck** [comment] 2023-02-03 14:53
I tried to installed the supposed latest version 3.264.0 but it didnt work

`npm install @aws-sdk/client-sso@3.264.0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-sdk/client-sso@3.264.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2023-02-03T14_51_39_293Z-debug-0.log`

**Comment by lnxslck** [comment] 2023-02-03 14:54
If you try to install the latest version

```
npm install @aws-sdk/client-sso

$ npm list                               
tce-tenant@0.1.0 /Users/brunoqueiros/dev/git/tce-tenant
+-- @aws-sdk/client-sso@3.261.0
```

**Comment by ajredniwja** [comment] 2023-02-03 19:13
Hey @j-mishra thanks for opening this issue, however I was not able to replicate it. 
I was able to successfully run `npm install @aws-sdk/client-sso@3.264.0`.

```
npm list                                 
aj@ /Users/aj/
├── @aws-sdk/client-sso@3.264.0
```
NPM: https://www.npmjs.com/package/@aws-sdk/client-sso

Can you provide some reproduction steps or maybe setup a repo?

**Comment by dathomae** [comment] 2023-02-03 20:50
I'm having the same problem.  When I try npm install @aws-sdk/client-sso@3.264.0 I get

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-sdk/client-sso@3.264.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

In the log file I see:

3689 verbose stack @aws-sdk/client-sso: No matching version found for @aws-sdk/client-sso@3.264.0.
3689 verbose stack     at module.exports (C:\Users\dougl\AppData\Roaming\npm\node_modules\npm\node_modules\npm-pick-manifest\lib\index.js:209:23)
3689 verbose stack     at RegistryFetcher.manifest (C:\Users\dougl\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\registry.js:125:22)
3689 verbose stack     at async Arborist.[nodeFromEdge] (C:\Users\dougl\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1061:19)
3689 verbose stack     at async Arborist.[buildDepStep] (C:\Users\dougl\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:930:11)
3689 verbose stack     at async Arborist.buildIdealTree (C:\Users\dougl\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:211:7)
3689 verbose stack     at async Promise.all (index 1)
3689 verbose stack     at async Arborist.reify (C:\Users\dougl\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:153:5)
3689 verbose stack     at async Install.exec (C:\Users\dougl\AppData\Roaming\npm\node_modules\npm\lib\commands\install.js:145:5)
3689 verbose stack     at async module.exports (C:\Users\dougl\AppData\Roaming\npm\node_modules\npm\lib\cli.js:78:5)

**Comment by dathomae** [comment] 2023-02-03 20:55
I'm pulling packages through CodeArtifact, which shows that the latest version of client-sso is 3.261,  When I try that pull:

npm install @aws-sdk/client-sso@3.261.0

I get the same error, complaining that it can't find version 3.264.0:

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-sdk/client-sso@3.264.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

Is there a reason why I'd get an error for client-sso@3.264.0 when I asked to install client-sso@2.261.0?

**Comment by wyattisimo** [comment] 2023-02-03 21:00
This might be a caching/propagation issue with CodeArtifact.

**Using npm directly:**
```
$ npm view @aws-sdk/client-sso versions | grep "3.26"
  '3.261.0',        '3.264.0'
```

**Using CodeArtifact:**
```
$ aws codeartifact login --domain $DOMAIN --repository sp-npm --tool npm
Successfully configured npm to use AWS CodeArtifact repository https://**************.d.codeartifact.us-east-1.amazonaws.com/npm/sp-npm/ 

$ npm view @aws-sdk/client-sso versions | grep "3.26"
  '3.261.0'
```

**CodeArtifact repo upstream config:**
```
$ aws codeartifact describe-repository --domain $DOMAIN --repository sp-npm --query "repository.{upstreams:upstreams}"
{
    "upstreams": [
        {
            "repositoryName": "npmjs-store"
        }
    ]
}

$ aws codeartifact describe-repository --domain $DOMAIN --repository npmjs-store --query "repository.{externalConnections:externalConnections}"
{
    "externalConnections": [
        {
            "externalConnectionName": "public:npmjs",
            "packageFormat": "npm",
            "status": "AVAILABLE"
        }
    ]
}
```

**Comment by dathomae** [comment] 2023-02-03 21:01
An additional data point if it makes a difference:

The package that I've named in package.json is @aws-sdk/client-apigatewaymanagementapi, which depends on @aws-sdk/client-provider-node which depends on @aws-sdk/client-provider-sso which depends on @aws-sdk/client-sso.

**Comment by wyattisimo** [comment] 2023-02-03 21:08
> I'm pulling packages through CodeArtifact, which shows that the latest version of client-sso is 3.261, When I try that pull:
> 
> npm install @aws-sdk/client-sso@3.261.0
> 
> I get the same error, complaining that it can't find version 3.264.0:
> 
> npm ERR! code ETARGET npm ERR! notarget No matching version found for @aws-sdk/client-sso@3.264.0. npm ERR! notarget In most cases you or one of your dependencies are requesting npm ERR! notarget a package version that doesn't exist.
> 
> Is there a reason why I'd get an error for client-sso@3.264.0 when I asked to install client-sso@2.261.0?


This is likely because other dependencies are requiring client-sso@3.264.0.

Doing `npm install @aws-sdk/client-sso@3.261.0` in your project will add @aws-sdk/client-sso@3.261.0 to your package.json dependencies _and_ attempt to resolve all dependencies, including @aws-sdk/client-sso@3.264.0.

**Comment by dathomae** [comment] 2023-02-03 21:11
It could be a problem with CodeArtifact.  I have npmjs configured as the external connections, but when I query for the upstream I get this:

aws codeartifact describe-repository --domain wheelstrategytools --repository wheelstrategytools-common --query "repository.{upstreams:upstreams}"
{
    "upstreams": []
}

Is there any way to find out if CodeArtifact is having a problem right now?

**Comment by dathomae** [comment] 2023-02-03 21:14
BTW, I've reset all versions in my package.json to those that worked find 5 days ago and cleared the cache and I still have the same problem.

**Comment by wyattisimo** [comment] 2023-02-03 21:23
> I have npmjs configured as the external connection, but when I query for the upstream I get this:
> 
> aws codeartifact describe-repository --domain wheelstrategytools --repository wheelstrategytools-common --query "repository.{upstreams:upstreams}" { "upstreams": [] }

Direct external connection to npmjs should work fine. It's just considered best practice to access external connections through upstream repos.

**Comment by wyattisimo** [comment] 2023-02-03 21:31
> BTW, I've reset all versions in my package.json to those that worked find 5 days ago and cleared the cache and I still have the same problem.

Likely because @aws-sdk/client-sso is specified with a caret range (if not in your dependencies, then somewhere in your dependency tree). e.g.:
```
  "@aws-sdk/client-sso": "^3.259.0"
```

**Comment by egarc-fiado** [comment] 2023-02-04 01:27
i have this problem. By uninstalling the @aws-sdk/client-dynamodb library I was able to compile my project. I think they just made a mistake with the package @aws-sdk/client-sso@3.264.0

**Comment by wyattisimo** [comment] 2023-02-04 04:04
I contacted AWS support and they determined that **this is actually an npm issue**. While the npm registry shows the latest version as `3.264.0`, the npm replication API is returning the previous revision, showing the latest version as `3.261.0`.

This means that all node package registries that rely on the replication API (including CodeArtifact and yarnpkg) will show version `3.261.0`.

It's possible that this glitch is somehow related to the "Delay in replication feed" incident that was recently reported on npm's status page: https://status.npmjs.org/incidents/rbxpf1l8cvp1

## Current response from npm registry API:
<img width="517" alt="image" src="https://user-images.githubusercontent.com/625546/216746574-8ca7f08c-9cb0-4a69-a9eb-532b2ee8f396.png">

## Current response from npm replication API: 
<img width="522" alt="image" src="https://user-images.githubusercontent.com/625546/216746170-83cdf8ef-4511-46da-ac7b-ec9e6a7147ba.png">

## Current screenshot from npmjs.com: 
<img width="357" alt="image" src="https://user-images.githubusercontent.com/625546/216746523-9cbdefe3-5b3e-42b2-afdd-d0a2e8fea834.png">

## Current screenshot from yarnpkg.com:
<img width="386" alt="image" src="https://user-images.githubusercontent.com/625546/216746703-0f15aa96-3a5d-406e-9294-4f59976eaf58.png">

**Comment by rockettown1** [comment] 2023-02-04 17:33
Hi @wyattisimo I'm also seeing this issue (using CodeArtifact). Is it just a case of waiting for the propagation to catch up?

I'm actually trying to install `serverless-offline` which has `@aws-sdk/client-sso` as a dependency down the chain.

**Comment by j-mishra** [comment] 2023-02-06 08:06
Hi @ajredniwja, thank you for your response and investigating on this issue. 
As mentioned by @wyattisimo, we are still facing this issue using CodeArtifact.

**Comment by wyattisimo** [comment] 2023-02-06 08:07
It's not pending—it's just broken. Something appears to have gone wrong with npm's handling of @aws-sdk/client-sso@3.264.0 with regard to their replication data.

The AWS team reached out to npm to see if npm can fix it. In the meantime, AWS is also rolling out a CodeArtifact update this week that uses the registry API instead of the replication API. This should resolve the issue for CodeArtifact.

**Comment by jacwak** [comment] 2023-02-06 08:11
Does anyone has a workaround while this issue been resolved

**Comment by bursache** [comment] 2023-02-06 09:39
@jacwak you can configure your .npmrc to use awk-sdk package scope from public npm registry eg. npm config set @aws-sdk:registry https://registry.npmjs.org

**Comment by Baratam** [comment] 2023-02-06 10:57
@bursache we have custom code artifact repo

> eam reached out to npm to see if npm can fix it. In the meantime, AWS is also rolling out a CodeArti

@wyattisimo - As per your comment I understand the fix will be available from AWS this week, when can we get the exact release date so we have to plan the work/releases at our end as this is seriously impacted.

**Comment by abhisheksett** [comment] 2023-02-06 22:33
Is there any ETA for this?

**Comment by dathomae** [comment] 2023-02-07 23:24
The workaround that I'm using:

First, run
aws codeartifact get-repository-endpoint --domain <domain> --domain-owner <account number> --repository <repository name> --format npm

Use the endpoint you get back and put

@<domain>:registry=<endpoint>

in your .npmrc file for local builds

and put 

npm config set @<domain>:registry=<endpoint>

in your buildspec.yaml for pipeline builds.  This causes the install to go direct to the npm registry for everything except the packages you've defined in CodeArtifact.

**Comment by j-mishra** [comment] 2023-02-08 11:10
The CodeArtifact issue related to the package `@aws-sdk/client-sso@3.264.0` seems to be resolved. Its started working now.

**Comment by RanVaknin** [comment] 2023-02-24 19:13
Hi, 
This issue seems to be due to 3rd party tooling not working as expected. The recommendation is to use NPM directly to mitigate this problem. 

Im going to close this since there are a number of workarounds mentioned in this thread including the last comment mentioning that this is solved.

If this persists **please open a new issue.**
Thanks,
Ran~

**Closed by RanVaknin** 2023-02-24 19:13 UTC
Labels: bug
