### ISSUE TITLE
Access denied sending/receiving messages to SQS queue after upgrading to V3 using sts assumeRole credentials 

### ISSUE THREAD

**Issue by razzpoker50** [aws/aws-sdk-js-v3#4509] opened 2023-03-10 04:06 UTC
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I have an application that sends a SQS message and a separate process that uses long polling to consume the messages as part of the API request and it used to work as expected on **V2**. After migrating to the **V3** version started seeing this error.
 
```
SQS receive message failed: Access to the resource https://sqs.us-west-2.amazonaws.com/ is denied.
``` 

The credentials passed to the sqsClient is are the temporary credentials generated by `sts.assumeRole`. The reason for this is that we have multiple AWS profiles in play and one of the profile is managed by the service level account which takes care of refreshing the credentials in the background. For the case where a message needs to be sent to the SQS, which is not part of the primary AWS profile ( that uses service level account ) generating the credentials once the previous credentials expire and generate the new sqsclient instance. The exact use case was working as expected on **V2.** 

**Code using aws-sdk V3**
```js
import { SQSClient, SQSClientConfig } from '@aws-sdk/client-sqs';
import { Credentials, STSClient } from '@aws-sdk/client-sts';

const stsClient = new STSClient({
  region: 'us-west-2'
});
const assumeRoleConfig = {
  RoleArn: 'Role-Arn'
  RoleSessionName: `Test-Session`,
};

async function getCrossAccountCredentials() {
    const command = new AssumeRoleCommand({
      ...assumeRoleConfig,
    });

    const assumedRole = await stsClient.send(command);

    credentials.AccessKeyId = assumedRole.Credentials.AccessKeyId;
    credentials.SecretAccessKey = assumedRole.Credentials.SecretAccessKey;
    credentials.SessionToken = assumedRole.Credentials.SessionToken;
    credentials.Expiration = assumedRole.Credentials.Expiration;

    return credentials;
}

async funtion getSqsClientWithCrossAccountCredentials() {
    const credentials = await getCrossAccountCredentials();

    const sqsClient: SQSClient = new SQSClient({
    region: 'us-west-2',
    ...credentials,
  });

  return sqsClient;
}

const main = async () => {
  const sqsClient = await getSqsClientWithCrossAccountCredentials();
  const payload = {
    name: 'test',
    email: 'test@123.com'
  };
  const params = {
    DelaySeconds: 120,
    MessageAttributes: {
      Title: {
        DataType: 'String',
        StringValue: `Test message`,
      },
    },
    MessageBody: JSON.stringify({
      ...payload,
    }),
    QueueUrl: 'queue_url',
  };

    try {
      const sqsCommand = new SendMessageCommand(params);

      await sqsClient.send(sqsCommand);

       console.log('Successfully sent a message');
    } catch (e) {
      console.log('Error sending a message !');
    }
};

main();
```

The same working solution when using the V2 is as below

**Code using aws-sdk V2** 
```js
import AWS from 'aws-sdk';

const stsClient = new AWS.STS({
  region: 'us-west-2'
});
const assumeRoleConfig = {
  RoleArn: 'Role-Arn'
  RoleSessionName: `Test-Session`,
};

async function getCrossAccountCredentials() {
    const assumedRole = await sts.assumeRole(assumeRoleConfig).promise();

    credentials.AccessKeyId = assumedRole.Credentials.AccessKeyId;
    credentials.SecretAccessKey = assumedRole.Credentials.SecretAccessKey;
    credentials.SessionToken = assumedRole.Credentials.SessionToken;
    credentials.Expiration = assumedRole.Credentials.Expiration;

    return credentials;
}

async funtion getSqsClientWithCrossAccountCredentials() {
    const credentials = await getCrossAccountCredentials();

    const sqsClient: SQSClient = new AWS.SQS({
    region: 'us-west-2',
    ...credentials,
  });

  return sqsClient;
}

const main = async () => {
  const sqsClient = await getSqsClientWithCrossAccountCredentials();
  const payload = {
    name: 'test',
    email: 'test@123.com'
  };
  const params = {
    DelaySeconds: 120,
    MessageAttributes: {
      Title: {
        DataType: 'String',
        StringValue: `Test message`,
      },
    },
    MessageBody: JSON.stringify({
      ...payload,
    }),
    QueueUrl: 'queue_url',
  };

  await sqsClient
    .sendMessage(params, (err, data) => {
      if (err) {
        console.log('Failed to send message');
      }

      if (data) {
        console.log('Successfully sent a message');
      }
    })
    .promise();
};

main();
```

Any pointers on how to solve this issue would be great. 

### SDK version number

"@aws-sdk/client-sts": "^3.288.0"

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16

### Reproduction Steps

None

### Observed Behavior

Accessed denied error when using similar code but upgrading to V3.

### Expected Behavior

Ability to send and receive SQS messages without any error when using credentials to initialize a sqs client.

**Comment by yenfryherrerafeliz** [comment] 2023-03-13 14:28
Hi @razzpoker50, thanks for opening this issue. The issue you are having may be caused because with V2 you are allowed to provide credentials details directly as parameters to the client, but with V3 you need to specify those details as a credentials object. 

For example, with v2 you are able to do the following:
```js
const client = new SQSClient({
    accessKeyId: 'ACCESSKEYID',
    secretAccessKey: 'SECRETACCESSKEY',
    sessionToken: 'SESSION-TOKEN',
    expiration: 'EXPIRATION'
})
```
But with v3 you need do the following:
```js
const sqsClient = new SQSClient({
        region: 'us-west-2',
        credentials: {
              accessKeyId: 'ACCESSKEYID',
              secretAccessKey: 'SECRETACCESSKEY',
              sessionToken: 'SESSION-TOKEN',
               expiration: 'EXPIRATION'
        }
    });
```

A working example based on the code you have provided would be:
```js
import {SendMessageCommand, SQSClient, SQSClientConfig} from '@aws-sdk/client-sqs';
import {AssumeRoleCommand, Credentials, STSClient} from '@aws-sdk/client-sts';

const stsClient = new STSClient({
    region: 'us-west-2'
});
const assumeRoleConfig = {
    RoleArn: 'Role-Arn'
    RoleSessionName: `Test-Session`,
};

async function getCrossAccountCredentials() {
    const command = new AssumeRoleCommand({
        ...assumeRoleConfig,
    });

    const assumedRole = await stsClient.send(command);

    return {
        accessKeyId: assumedRole.Credentials.AccessKeyId,
        secretAccessKey: assumedRole.Credentials.SecretAccessKey,
        sessionToken: assumedRole.Credentials.SessionToken,
        expiration: assumedRole.Credentials.Expiration
    }
}

async function getSqsClientWithCrossAccountCredentials() {
    const credentials = await getCrossAccountCredentials();

    const sqsClient = new SQSClient({
        region: 'us-west-2',
        credentials,
    });

    return sqsClient;
}

const main = async () => {
    const sqsClient = await getSqsClientWithCrossAccountCredentials();
    const payload = {
        name: 'test',
        email: 'test@123.com'
    };
    const params = {
        DelaySeconds: 120,
        MessageAttributes: {
            Title: {
                DataType: 'String',
                StringValue: `Test message`,
            },
        },
        MessageBody: JSON.stringify({
            ...payload,
        }),
        QueueUrl: 'queue_url',
    };

    try {
        const sqsCommand = new SendMessageCommand(params);

        await sqsClient.send(sqsCommand);

        console.log('Successfully sent a message');
    } catch (e) {
        console.log('Error sending a message !');
    }
};

main();

```

Please let me know if that helps you.

Thanks!

**Comment by razzpoker50** [comment] 2023-03-13 19:28
@yenfryherrerafeliz Thank you for the response. I tried to make the changes accordingly and see if that takes care of the issue but I started running into a AccessDenied ( 403 ) error. 

```
User: arn:aws:sts::111:assumed-role/RoleA/aws-sdk-js-session-1678730405800 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::222:role/RoleB
```

The service is configured to use a kubernetes service level account ( Account - 111 ) and I would be needing the STS credentials to send a SQS message that is part of Account 222. 

Tried adding a `sts:AssumeRole` action via terraform so that RoleA can assume role but I am running into a malformed policy document as `wildcards * ` are not supported as part of the principal `arn:aws:sts::111:assumed-role/RoleA/aws-sdk-js-session-*` ( the last part is the timestamp which I thought I can take care using the * ).

Also passed in an explicit `RoleSessionName` in the code to see if I can get rid of the time stamp but for some reason that is not being used. 

Not sure if there is something I am missing here. Any pointers in that direction would be great.

**Comment by n-erwen** [comment] 2023-06-29 09:25
I'm having the same issue, trying to put an object in an S3 bucket with an assumed role but receiving "Access Denied" as the assumed role ARN ends with "aws-sdk-js-session-<timestamp>". 

Is there a way to allow assumed role ARNs formatted in this way to access an S3 bucket through a bucket policy, or to change the arn using STS?

**Comment by yosefbs** [comment] 2023-07-10 11:31
I have the same issue and it to solution was to set the the region of the queue in the SQS constructor (in v2 when assuming a role it was work without define the queue region )

**Comment by yenfryherrerafeliz** [comment] 2023-09-13 18:58
Hi @razzpoker50, sorry for the delay on this. I just tried one more time to reproduce this but still is not possible. Everything works fine on my end. Can you please confirm if you are still having this issue?

Please let me know.

Thanks!

**Comment by razzpoker50** [comment] 2023-09-21 00:06
I completely switched over to use the API's from V3 instead of mixing up with V2 API. So after the change I did not use `STS` to generate the credentials. I think this issue only happens if you mix V2 and V3.

**Comment by pkruk** [comment] 2023-11-02 08:52
In my case, the problem is with eks-iam-role, because I forgot to add to the iam-eks-role permissions to sts:AssumeRole.
IAM role was okay, and this role could access the role in different account. So role attached to the app Service Account was ok and was trusted in Account B, the only thing I need to do, was to add a policy to this role with:

```
    {
      effect = "Allow"
      actions = [
        "sts:AssumeRole"
      ]
      resources = [
        "AccountB",
      ]
    }
```

**Comment by yenfryherrerafeliz** [comment] 2023-11-07 15:46
Closing this issue for now. Please if you need anything else that we can help with, feel free of opening a new issue.

Thanks!

**Closed by yenfryherrerafeliz** 2023-11-07 15:46 UTC
