### ISSUE TITLE
[React Native] Problem with parseUrl in @aws-sdk/url-parser-node

### ISSUE THREAD

**Issue by bndkt** [aws/aws-sdk-js-v3#1900] opened 2021-01-12 11:49 UTC
I'm using @aws-sdk/client-cognito-identity and @aws-sdk/credential-provider-cognito-identity to retrieve credentials from a Cognito Identity Pool to access AWS recourses from a React Native app.

The relevant code is:

```
import { CognitoIdentityClient } from "@aws-sdk/client-cognito-identity";
import { fromCognitoIdentityPool } from "@aws-sdk/credential-provider-cognito-identity";

const cognitoIdentityClient = new CognitoIdentityClient({
  region: AWS_REGION,
});
const credentials = fromCognitoIdentityPool({
  client: cognitoIdentityClient,
  identityPoolId: AWS_IDENTITY_POOL_ID,
  logins: {
    "appleid.apple.com": userToken,
  },
});
```

Upon resolving the promise returned by fromCognitoIdentityPool, an error is thrown:

```
[Unhandled promise rejection: Error: not implemented]
- node_modules/react-native/Libraries/Blob/URL.js:169:10 in get__hostname
- node_modules/@aws-sdk/url-parser-node/dist/cjs/index.js:5:26 in parseUrl
- node_modules/@aws-sdk/config-resolver/dist/cjs/EndpointsConfig.js:26:30 in getEndPointFromRegion
```

This seems to be cause by the line
https://github.com/aws/aws-sdk-js-v3/blob/982ad9347bdfdea14e055775584f2ad1b4c43134/packages/url-parser-node/src/index.ts#L5
The problem is that React Native contains a homemade polyfill for URL (see also https://github.com/facebook/react-native/issues/16434).

As a workaround, https://github.com/charpeni/react-native-url-polyfill can be used. If I include *import "react-native-url-polyfill/auto";* in the file where the fromCognitoIdentityPool() function is located, it works. I think it would be good to solve this for React Native in @aws-sdk/url-parser-node, so that people don't need to deploy their own workarounds. I'd be happy to do pull request if pointed in the right direction, but right now I'm not sure how to solve this. I guess you probably don't want to include https://github.com/charpeni/react-native-url-polyfill in @aws-sdk/url-parser-node.

**Comment by AllanZhengYP** [comment] 2021-01-12 19:06
@bndkt 
Thank you for reporting this! This is a regression introduced in https://github.com/aws/aws-sdk-js-v3/pull/1766. We actually already have a ticket tracking fixing this issue: #1867. I will close this one because of duplication. Can you comment on #1867 for further discussion?

**Closed by AllanZhengYP** 2021-01-12 19:06 UTC
Labels: feature-request

**Comment by bndkt** [comment] 2021-01-12 19:19
Thanks @AllanZhengYP! I actually saw #1867 but thought it must be something else, but a regression makes sense. I'll track #1867 and comment there in case I can add something.
