### ISSUE TITLE
LicenseManager.listReceivedLicenses throws error when adding a filter of >1 status values 

### ISSUE THREAD

**Issue by gloverke** [aws/aws-sdk-js-v3#4244] opened 2022-12-01 12:53 UTC
### Describe the issue

The following code will throw an error that you are only allowed a single value in the "Values" array.  The documentation says you can have multiple.

```js
var params = {
  Filters: [
    { Name: 'ProductSKU', Values: [YYYYY] },
    {  Name: 'Beneficiary', Values: [XXXXX]}],
    { Name: 'Status', Values: ['AVAILABLE','EXPIRED'] }
  MaxResults: 10
};
availableAndExpiredLicenses = await licensemanager.listReceivedLicenses(params).promise();

```
I also tried multiple Status objects in the filter list as well as the command line flag style

`  {Name: 'Status', Values: ["AVAILABLE,EXPIRED"] }
`
All had the same error

### Links

[LInk to top google result](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/LicenseManager.html)

The most recent documentation doesn't provide code examples for this method that I could find.  The cli-skeleton generated shows the filters to have Values:[] with an array, but multiple values throw an error.

**Comment by yenfryherrerafeliz** [comment] 2023-01-13 01:59
Hi @gloverke, thanks for opening this issue. I can confirm that we received an error when specified more than one value in the filter, even when the documentation says it allow an array of string as values. I will reach out to the internal team regarding to this just to have a clarification of how it really should be.

Steps to reproduce:
- Start a node project ```npm init projectname```
- Install the client ```npm i @aws-sdk/client-license-manager```
- copy and paste the following code in a js file, maybe "src/index.js":
```js
import {
    LicenseManagerClient, ListReceivedLicensesCommand
} from "@aws-sdk/client-license-manager";

const client = new LicenseManagerClient({
    region: 'us-east-2'
});
const response = await client.send(new ListReceivedLicensesCommand({
    Filters: [
        {
            Name: 'Status',
            Values: ['Available, Inactive']
        }
    ]
}));

console.log(response)
```

Note that this error occurs is also cli and the rest of the SDKs, so that the validation error returned is by the service api.

Thanks!

**Comment by yenfryherrerafeliz** [comment] 2023-01-13 17:51
Hi @gloverke, since this issue is with the service api itself, and not with the SDK, I have created a new issue in our cross sdk repo, which purpose of it is to have issues like this. [Here](https://github.com/aws/aws-sdk/issues/449) is the link to it in case you want to follow up.

In the meantime I will close this issue.

Thanks!

**Closed by yenfryherrerafeliz** 2023-01-13 17:51 UTC
Labels: investigating, service-api, documentation
