### ISSUE TITLE
The v1.0.0-gamma.5 release didn't mention #1379 as a breaking change

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1395] opened 2020-07-21 18:59 UTC
**Describe the bug**
The v1.0.0-gamma.5 release didn't mention #1379 as a breaking change
https://github.com/aws/aws-sdk-js-v3/releases/tag/v1.0.0-gamma.5

**SDK version number**
v1.0.0-gamma.5

**Is the issue in the browser/Node.js/ReactNative?**
N/A

**To Reproduce (observed behavior)**
* An exclamation was appended in #1379 (`fix!`) to call it out as a breaking change
  * Conventional commits docs: https://www.conventionalcommits.org/en/v1.0.0/#summary
* The release notes in https://github.com/aws/aws-sdk-js-v3/releases/tag/v1.0.0-gamma.5 mentioned it under "Other Changes"

**Expected behavior**
The release CHANGELOG should call out `!` as breaking change

**Comment by trivikr** [comment] 2020-07-23 16:56
Findings:
* we use `lerna@3.22.1` https://github.com/aws/aws-sdk-js-v3/blob/59948eebf0a16e44356339df781d5bce3b1f1e07/package.json#L74
* lerna internally depends on `conventional-changelog-core@^3.1.6` https://github.com/lerna/lerna/blob/f6e7a13e60fefc523d701efddfcf0ed41a77749b/core/conventional-commits/package.json#L37

ToDo: Find out when support for adding `!` after scope to specify breaking changes was added in `conventional-changelog-core`

**Comment by alexforsyth** [comment] 2020-07-23 18:47
Creating a new repo to test out conventional commits (hopefullly) repro this error in an isolated env

**Comment by alexforsyth** [comment] 2020-07-23 20:31
This looks like a bug with lerna conventional commits. I created [this repo](https://github.com/alexforsyth/lerna-conventional-commits) with full instructions on how to reproduce this specific error. 

**Findings**: Lerna conventional commits do not respect '!' as denoting a breaking change when part of the 'types' on a [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#examples). Additionally, It seems like including the '!' may make lerna not recognize that commit as a valid conventional commit in some cases. [This repo](https://github.com/alexforsyth/lerna-conventional-commits) also highlights this problem.  

For now, the **workaround** is to include `BREAKING CHANGE: my breaking change message` inside a commit with a breaking change. 

I'm closing this issue as I think this is a reasonable workaround and the root cause isnt in with our code. Feel free to open an issue with lerna - I need to timebox this investigation for now.

**Closed by alexforsyth** 2020-07-23 20:31 UTC

**Comment by alexforsyth** [comment] 2020-07-23 20:46
Opened lerna issue: https://github.com/lerna/lerna/issues/2668
