### ISSUE TITLE
Cannot view CI build status of my own PR

### ISSUE THREAD

**Issue by justingrant** [aws/aws-sdk-js-v3#1463] opened 2020-08-25 19:31 UTC
**Describe the bug**
When filing a PR on this repo (e.g. #1462), if builds fail then I'm unable to view the build results. This means that I can't figure out exactly what's failing.  This is especially problematic now because #1460 prevents local builds and testing from working.

**SDK version number**
n/a

**Is the issue in the browser/Node.js/ReactNative?**
n/a

**Details of the browser/Node.js/ReactNative version**
n/a

**To Reproduce (observed behavior)**
File any PR when you're not an AWS employee

**Actual behavior**
I don't have permission to view CI build results.

**Expected behavior**
I can view CI build results

**Screenshots**
![image](https://user-images.githubusercontent.com/277214/91218710-52801a80-e6ce-11ea-93ed-b1e90aefd24f.png)

https://us-west-2.console.aws.amazon.com/codesuite/codebuild/138827292993/projects/sdk-staging-test/build/sdk-staging-test%3A13bfb14f-b7d8-49de-9d41-12449a757415

![image](https://user-images.githubusercontent.com/277214/91218789-717eac80-e6ce-11ea-9461-d30434c1298f.png)

**Additional context**
I'm not sure if CodeBuild permissions can be edited to allow public read-only access, but that'd seem like the logical fix here. Not sure why an open-source project should have any build artifacts closed to the public.

**Comment by trivikr** [comment] 2020-08-25 19:51
History:
* The logs were enabled in the past using github-codebuild-logs in https://github.com/aws/aws-sdk-js-v3/pull/386
* They were disabled when we moved to GitHub Actions in https://github.com/aws/aws-sdk-js-v3/pull/1265
* Unfortunately, the GitHub Actions CI had to be disabled as secrets are not shared with forks https://github.com/aws/aws-sdk-js-v3/pull/1278

We either need to re-enable github-codebuild-logs or revisit GitHub Actions.

**Comment by justingrant** [comment] 2020-08-25 19:57
OK, thanks @trivikr for the update. I don't know which of those options would be best. 

In the meantime, would it be possible to let me know if #1462 has build failures other than the memory exhaustion caused by #1460?  If there are non-#1460 failures, I'll fix them!

**Comment by trivikr** [comment] 2020-08-25 21:14
> would it be possible to let me know if #1462 has build failures other than the memory exhaustion caused by #1460?

Yup, it's memory exhaustion failure caused by #1460

**Comment by trivikr** [comment] 2021-01-05 19:28
Closing, as github-codebuild-logs was re-enabled on aws-sdk-js-v3.
Example comment: https://github.com/aws/aws-sdk-js-v3/pull/1863#issuecomment-754848001

**Closed by trivikr** 2021-01-05 19:28 UTC
