### ISSUE TITLE
Error ENOTFOUND from parallel client invocations on Apple Silicon

### ISSUE THREAD

**Issue by Dylanlan** [aws/aws-sdk-js-v3#5236] opened 2023-09-20 21:12 UTC
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When using parallel SDK client commands on my 2021 M1 Macbook Pro, I sometimes get an error like: `Error: getaddrinfo ENOTFOUND sts.us-east-1.amazonaws.com`

I've seen the error using at least these clients so far: `sts`, `s3`, `rds`, `ssm`

I can't reproduce the error if I run the commands in sequence, and I also can't reproduce it using the SDK v2.

### SDK version number

@aws-sdk/client-sts@3.414.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.18.0

### Reproduction Steps

I can reproduce it around 50% of the time from this script:

```js
const sts = require('@aws-sdk/client-sts');

const stsClient = new sts.STSClient();
const command = new sts.GetCallerIdentityCommand();

async function test() {
    const promises = [];
    for (let i = 0; i < 1000; i++) {
        // await stsClient.send(command); // Succeeds if awaited in sequence
        promises.push(stsClient.send(command));
    }
    await Promise.all(promises);
    console.log('success');
}

test();
```

Note that I've been able to reproduce it with as few as 2 parallel promises.

### Observed Behavior

The script will sometimes have a DNS error:
```
> node aws-script.js
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: getaddrinfo ENOTFOUND sts.us-east-1.amazonaws.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'sts.us-east-1.amazonaws.com',
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}

Node.js v18.18.0
```

### Expected Behavior

I expected it to log `success` without erroring

### Possible Solution

Something related to DNS lookups seems to have changed in v3 compared to v2. I haven't dug into where the difference is, though

### Additional Information/Context

The root cause might be a bug between Node, IPv6, & Apple Silicon. I have a related discussion here: https://github.com/orgs/nodejs/discussions/49734

But it's interesting that I can't reproduce the error using the AWS JS SDK v2, and I'm wondering if v3 has any workarounds.

I find it strange that this doesn't seem to be a widespread issue, so it seems related to my setup. But I have a handful of coworkers also able to reproduce the error on different M1 processor Macbooks, different home networks, and different ISPs.

It seems to get fixed for me if any of these are true:
1. Using the SDK v2
2. Awaiting the client commands in sequence
3. Using other OS (eg: Windows desktop, Ubuntu AWS EC2 instance, Intel processor Macbook)
4. Overriding node's `dns.lookup` function to use `{ family: 4 }`

Things I've tried that haven't seemed to fix it:
- Restarting my Macbook
- Flushing my DNS cache with `sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder`
- Upgrading to latest node 18.18.0 or 20.7.0
- Downgrading to node 16.18.1 (previous version I used)
- Downgrading to `@aws-sdk/client-sts@3.13.0`
- Using `AWS_MAX_ATTEMPTS=3` or `AWS_RETRY_MODE=standard` ([reference](https://docs.aws.amazon.com/sdkref/latest/guide/feature-retry-behavior.html))
- Disabling IPv6 (System Settings -> Network -> TCP/IP -> Configure IPv6, set to `Link-Local Only`)
- Disconnecting from my VPN
- Using only Ethernet
- Using only Wifi
- Disabling firewall and antivirus
- Using --dns-result-order=ipv4first or NODE_OPTIONS=--dns-result-order=ipv4first
- Changing configured DNS server from Mac default to Google's 8.8.8.8 or Cloudflare's 1.1.1.1

**Comment by danielvy** [comment] 2023-09-26 21:57
I have a very similar problem with @aws-sdk/client-s3. The exact same errors with bucket domain names (e.g. `<bucket-name>.s3.eu-central-1.amazonaws.com`).

I also find it strange that the problem is not more wide spread and after considerable time spent investigating this it doesn't seem to be @aws-sdk problem, per se. I still can't pin point the exact cause but it is either `getaddrinfo` or `mDNSResponder`.

You can easily replicate it just by "concurrently" calling `dns.lookup()` on those aws domain names, you will randomly get these errors after some time. It will happen sooner the more lookup calls your push at once.

Here is what I know/learned:

- By default, all node's requests use `dns.lookup()` to resolve domain names, which @aws-sdk also uses.
- `dns.lookup()` doesn't have any in memory caching and always call `getaddrinfo`, which in turn seems to use `mDNSResponder`. `mDNSResponder` handles TTL and provides caching. `dns.lookup()` doesn't even get TTL from `getaddrinfo`.
- The problem seems to only happen for domain records with short TTL (under 50 seconds). Using the same testing logic with records that have longer TTL doesn't reproduce the problem.
- To rule out that the problem is on the DNS server or router/network side, I used a packet sniffer (Wireshark) to see what's actually being transmitted/received. On the network level, TTL seems to be respected and I see the proper amount of actual DNS queries even under heavy lookup load and zero actual DNS query errors.
- If you put a hard coded IP address in the `hosts` file, the problem goes away.
- System log console doesn't show any relevant errors/warnings.
- Node's `dns.resolve*()` functions use a different logic, don't use `getaddrinfo` and don't use caching. They don't produce this error but will occasionally get a refused connection by the DNS server.

The above leads me to believe that it's an issue with one of the underlying libraries.

Unfortunately,  I didn't find an easy way to fix/workaround this:

- It's possible to monkey patch `dns.lookup()` to provide some basic DNS caching. But this feels like the last resort.
- Some @aws-sdk interfaces offer a way to provide request handler that may be possibly used to send requests with looked up and cached ip address and a hosts header.
- Add some retry logic with cool down to handle these errors around my @aws-sdk client calls.

Ideally and most reasonably, it should be fixed by the underlying OS library, or by node providing a way to plugin DNS caching (or implement their own). The next best thing is @aws-sdk catching these errors and handling them gracefully.

**Comment by RanVaknin** [comment] 2023-09-28 22:36
Hi @Dylanlan 

I have a 2020 apple silicone M1 that I've tested your code on. I did over 100 executions and all were successful without seeing a single dns error. 

I've seen this problem reported before, and it's usually due to networking error on something like a customer's pod 
 restarting, or when a k8 cluster scales down or up and it has some intermittent networking errors, but this is the first time I've seen this reported on a laptop.

Also props to @danielvy for doing some world class investigation here. And here are a few follow up points:
> Some @aws-sdk interfaces offer a way to provide request handler that may be possibly used to send requests with looked up and cached ip address and a hosts header.

This might be possible. Im not sure how I would build the caching logic, but you can easily provide your own http handler like so:

```js
const sts = require('@aws-sdk/client-sts');
const { NodeHttpHandler } from "@smithy/node-http-handler"

const stsClient = new sts.STSClient({
//    requestHandler:  <your custom handler here >
});
const command = new sts.GetCallerIdentityCommand();

async function test() {
    const promises = [];
    for (let i = 0; i < 1000; i++) {
        // await stsClient.send(command); // Succeeds if awaited in sequence
        promises.push(stsClient.send(command));
    }
    await Promise.all(promises);
    console.log('success');
}

test();
```

>Node's dns.resolve*() functions use a different logic, don't use getaddrinfo and don't use caching. They don't produce this error but will occasionally get a refused connection by the DNS server.

The SDK does not have an easy way of capturing and handling node level errors. There are only a handful that are truly considered transient and are retried out of the box, like ECONNRESET for example. 

What you can do is create your own simple retryer and wrap your code in it:

```js
async function customSend(client, command, maxRetries = 3) {
    let attempts = 0;
    while (attempts < maxRetries) {
      try {
        console.log("trying, attempt:", attempts)
        const result = await client.send(command);
        return result;
      } catch (error) {
        if (error.code === 'ENOTFOUND') {
          attempts++;
          await new Promise(resolve => setTimeout(resolve, 200 * attempts)); // exponential backoff
        } else {
          throw error;
        }
      }
    }
    throw new Error('Max retry attempts reached');
  }
  
  (async () => {
    try {
      const result = await customSend(stsClient, command);
      console.log('Success:', result);
    } catch (error) {
      console.log('Failure:', error);
    }
  })();
```

I simulated the same error by disconnecting my machine from the wifi and got some good results:

```
trying, attempt: 0
trying, attempt: 1
trying, attempt: 2
Failure: Error: Max retry attempts reached
```

I know this must be frustrating for you since there is no clear cut answer as to why this is happening, but I hope that the provided suggestions can point you towards the right direction. 
From an SDK standpoint this is not really actionable and for this reason I'm inclined to close this. 
If you having any additional questions or concerns you can open a discussion on our repo's discussions tab.


Ran~

**Closed** 2023-09-28 22:36 UTC
Labels: bug
