### ISSUE TITLE
Error details not being passed to the error message since migration to SDK JS v3 for AWS SES

### ISSUE THREAD

**Issue by redvivi** [aws/aws-sdk-js-v3#2334] opened 2021-04-30 19:10 UTC
## Describe the bug

The details of the error message are not being passed to the error message in AWS SDK JS v2 vs. v3.

#### SDK version number
`@aws-sdk/client-ses@3.13.1` comparing with `@aws-sdk@2.897.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Can't check.

## Steps to reproduce
1. Configure AWS SES and verify the identity you wish to send a test email in a given region
2. Implement the following code (SDK V3)
```javascript
const {
    SES
} = require('@aws-sdk/client-ses');
async callback => {
    function generateParams() {
    ...
    return params
    }
    function sendingEmail(bufferedData) {
        return new Promise((resolve, reject) => {
            const creds = {
                accessKeyId: keys["Key"],
                secretAccessKey: keys["Key Secret"],
            };
            const ses = new SES({
                apiVersion: '2010-12-01',
                region: keys["AWS Service Endpoint Region"] || 'us-east-1',
                credentials: creds
            });
            ses.sendEmail(bufferedData, function(error, data) {
                if (error) {
                    reject(error);
                } else {
                    return resolve(data.MessageId);
                };
            });
        });
    }

    generateParam()
        .then(
            (bufferedData) => {
                sendingEmail(bufferedData)
                    .then(
                        (dataFromSes) => {
                            callback(undefined, dataFromSes);
                        })
                    .catch(
                        (err) => {
                            callback(err);
                        })
            })
        .catch(
            (err) => {
                callback(err);
            });
}
```
3. Change the region by another one on which your identities are not verified to trigger a SDK error.
4. The error message says  `MessageRejected: MessageRejected`
5. Now compare with SDK V2 implementation.
```javascript
const AWS = require('aws-sdk');
async callback => {
    function generateParams() {
    ...
    return params
    }
    function sendingEmail(bufferedData) {
        return new Promise((resolve, reject) => {
            const ses = new AWS.SES({
                apiVersion: '2010-12-01',
                accessKeyId: keys["Key"],
                secretAccessKey: keys["Key Secret"],
                region: keys["AWS Service Endpoint Region"] || 'us-east-1'
            });
            ses.sendEmail(bufferedData, function(error, data) {
                if (error) {
                    reject(error);
                } else {
                    return resolve(data.MessageId);
                };
            });
        });
    }

    generateParam()
        .then(
            (bufferedData) => {
                sendingEmail(bufferedData)
                    .then(
                        (dataFromSes) => {
                            callback(undefined, dataFromSes);
                        })
                    .catch(
                        (err) => {
                            callback(err);
                        })
            })
        .catch(
            (err) => {
                callback(err);
            });
}
```
5. The error message says  `MessageRejected: Email address is not verified. The following identities failed the check in region US-EAST-2.`

#### Observed behavior
The message does not give any details of why it occurred.
```
MessageRejected: MessageRejected
    at deserializeAws_querySendEmailCommandError (/var/task/node_modules/@aws-sdk/client-ses/dist/cjs/protocols/Aws_query.js:3368:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /var/task/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
    at async /var/task/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24
    at async StandardRetryStrategy.retry (/var/task/node_modules/@aws-sdk/middleware-retry/dist/cjs/defaultStrategy.js:56:46)
    at async /var/task/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
```
#### Expected behavior
The full error message detail should be passed to the error description.
```
MessageRejected: Email address is not verified. The following identities failed the check in region US-EAST-2: xxx@domain.com
    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```

## Additional context
Perhaps related to #2261, #1287

**Comment by ajredniwja** [comment] 2021-06-10 06:26
Hi @redvivi thanks for opening this issue. Is it still persisting as #1287 was closed with a fix and https://github.com/aws/aws-sdk-js-v3/issues/2261 is the one I was able to work with but wasnt able to reproduce.

**Comment by redvivi** [comment] 2021-06-10 15:25
Hi @ajredniwja,

Still current with   `"@aws-sdk/client-ses": "3.18.0"`

**Comment by ajredniwja** [comment] 2021-06-10 22:03
> Hi @ajredniwja,
> 
> Still current with `"@aws-sdk/client-ses": "3.18.0"`

Let me try and reproduce this.

**Comment by ajredniwja** [comment] 2021-08-18 17:23
Was able to reproduce it and seems to be deserialization issue at first, will post a fix soon. 

https://github.com/aws/aws-sdk-js-v3/blob/fac5f27fc2727d91be49e403a1a81005efe685d6/clients/client-ses/protocols/Aws_query.ts#L9490

Capital case `Message` should also be taken care of.

**Comment by danielehrhardt** [comment] 2021-10-12 14:14
> Was able to reproduce it and seems to be deserialization issue at first, will post a fix soon.
> 
> https://github.com/aws/aws-sdk-js-v3/blob/fac5f27fc2727d91be49e403a1a81005efe685d6/clients/client-ses/protocols/Aws_query.ts#L9490
> 
> Capital case `Message` should also be taken care of.

Same Problem. Could you push your fix and create a new release?

**Comment by claude** [comment] 2021-11-01 22:56
I'm experiencing the same issue. It's really hard to figure out what's wrong with just a  `MessageRejected` error message. Please help!

**Comment by rguntha** [comment] 2021-11-29 17:13
I am experiencing the same issue. 
I am using nodejs on m1 macbook pro.
NodeJs: v14.18.1
"@aws-sdk/client-ses": "^3.42.0"

During the initialisation there is a rejected promise in chain.js line 7 with a message "No providers in chain"
The initialising code is below 

`const sesClient = new SESClient({ region: REGION });`

I have configured the credentials file and the environment variables with key id and access key appropriately.

**Comment by rguntha** [comment] 2021-11-29 19:48
I figured out the problem. For me it was rejecting the message because my account is in the SES sandbox. So I can only send emails to verified domains. Earlier I was trying to send email to a non verified domain and hence it is getting rejected. I also requested AWS to move my account out of sandbox

**Comment by redvivi** [comment] 2022-03-17 08:51
> > Was able to reproduce it and seems to be deserialization issue at first, will post a fix soon.
> > https://github.com/aws/aws-sdk-js-v3/blob/fac5f27fc2727d91be49e403a1a81005efe685d6/clients/client-ses/protocols/Aws_query.ts#L9490
> > 
> > Capital case `Message` should also be taken care of.
> 
> Same Problem. Could you push your fix and create a new release?

Het there! Has a fix been pushed?

**Comment by yenfryherrerafeliz** [comment] 2023-02-20 06:17
Hi @redvivi, sorry for the delay on this. This issue should be resolved. I just did a test and I got a descriptive message in the error thrown. Please see below:

```console
MessageRejected: Email address is not verified. The following identities failed the check in region US-EAST-1: INVALID_EMAIL
    at deserializeAws_queryMessageRejectedResponse (PROJECT_DIR/node_modules/@aws-sdk/client-ses/dist-cjs/protocols/Aws_query.js:3559:23)
    at deserializeAws_querySendEmailCommandError (PROJECT_DIR/node_modules/@aws-sdk/client-ses/dist-cjs/protocols/Aws_query.js:2560:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PROJECT_DIR/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async PROJECT_DIR/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at async PROJECT_DIR/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async PROJECT_DIR/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22
    at async file://PROJECT_DIR/src/index.js:11:18 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'REQUEST-ID',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Error: {
    Type: 'Sender',
    Code: 'MessageRejected',
    Message: 'Email address is not verified. The following identities failed the check in region US-EAST-1: INVALID_EMAIL',
    message: 'Email address is not verified. The following identities failed the check in region US-EAST-1: INVALID_EMAIL'
  },
  RequestId: '07db24c8-6862-42b2-9a24-14e9a8613869',
  xmlns: 'http://ses.amazonaws.com/doc/2010-12-01/'
}
```
I will close this issue now but if you still have an issue please create a new bug report or reopen this one. Also if you have any comments just let me know.

Thanks!

**Closed by yenfryherrerafeliz** 2023-02-20 06:17 UTC
Labels: bug
