### ISSUE TITLE
Transcribe Streaming Alternatives Items don't contain Confidence

### ISSUE THREAD

**Issue by jkgodwin** [aws/aws-sdk-js-v3#2182] opened 2021-03-26 12:32 UTC
## Describe the bug
The `Item` object returned in Transcribe Streaming results doesn't not contain a `Confidence` property [as specified in docs](https://docs.aws.amazon.com/transcribe/latest/dg/streaming.html).

#### SDK version number
`@aws-sdk/client-transcribe-streaming: 3.9.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Node v12.16.1

## Steps to reproduce
Start a transcribe stream using `StartStreamTranscriptionCommand` and receive results through `TranscriptResultStream`. The following code will not compile as the `Confidence` property is missing from the `Item` object.

```ts
for await (const event of data.TranscriptResultStream) {
  if(event.TranscriptEvent) {
    const results = event.TranscriptEvent.Transcript.Results;
    results.map(result => {
      (result.Alternatives || []).map(alternative => {
        const confidences = alternative.Items.map(item => item.Confidence);
      });
    });
  }
}
```

#### Observed behavior
The `Item` objects are missing the `Confidence` property and the property is not part of the [object interface](https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-transcribe-streaming/models/models_0.ts).

#### Expected behavior
The  returned `Item` objects have a `Confidence` property.

**Comment by ajredniwja** [comment] 2021-05-27 23:14
Hey @jkgodwin thanks for opening this issue, seem to be duplicate of https://github.com/aws/aws-sdk-js-v3/issues/2187

Please checkout: https://github.com/aws/aws-sdk-js-v3/issues/2187#issuecomment-850000971

Closing this issue now, feel free to reach out if you have any questions.

**Closed by ajredniwja** 2021-05-27 23:14 UTC
Labels: bug, needs-triage, service-api

**Comment by jkgodwin** [comment] 2021-06-01 18:30
Thanks @ajredniwja I'll check it out. Technically that issue is a dupe of this as this was opened first 😄
