### ISSUE TITLE
Instance and container metadata credentials not working with Deno

### ISSUE THREAD

**Issue by soundstep** [aws/aws-sdk-js-v3#4405] opened 2023-02-06 11:59 UTC
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Automatic credentials [fromInstanceMetadata and fromContainerMetadata](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_providers.html#fromcontainermetadata-and-frominstancemetadata) are not picked up and is hanging (no error message, no timeout) when used with Deno.
This happens on our CI in 2 different Jenkins instances (one EC2, one EKS), it does work locally with environment variables, or on the CI using NodeJS.
Note: I realize the Deno usage is not official, but any help would be greatly appreciated to either resolve the issue or debug it. Deno has been a tremendous improvement in our workflows.

### SDK version number

@aws-sdk/client-s3@3.264.0

### Which JavaScript Runtime is this issue in?

Deno

### Details of the browser/Node.js/ReactNative version

```sh
deno 1.30.2 (release, aarch64-apple-darwin)
v8 10.9.194.5
typescript 4.9.4
```

### Reproduction Steps

Note that the following scripts are working correctly with this port, but this port has been abandoned: https://github.com/christophgysin/aws-sdk-js-v3 (https://deno.land/x/aws_sdk@v3.32.0-1/client-s3/mod.ts)

## Test no credentials setup

1. [Install Deno](https://deno.land/manual@v1.30.2/getting_started/installation#download-and-install)
2. Create a deno script `main.ts`:

```ts
import { ListObjectsCommand, S3Client } from 'npm:@aws-sdk/client-s3@3.264.0';

console.log('No AWS credentials setup');

const client = new S3Client({
    region: 'eu-west-1'
});

console.log('S3 client created, executing ListObjectsCommand');

try {
    const res = await client.send(
        new ListObjectsCommand({
            Bucket: 'my-s3-bucket'
        }),
    );

    console.log(res);

    Deno.exit();
} catch (err) {
    console.log(err);
    Deno.exit(1);
}
```

3. Run the script: `deno run -A --reload main.ts`

Output:

The script is running and hanging forever:

<img width="1206" alt="Screenshot 2023-02-06 at 10 41 09" src="https://user-images.githubusercontent.com/133293/216960832-4acbad4b-c4ec-4c16-b2dc-cd1302e9886c.png">

## Test with credentials setup

1. [Install Deno](https://deno.land/manual@v1.30.2/getting_started/installation#download-and-install)
2. Create a deno script `main-container.ts`:

```ts
import { ListObjectsCommand, S3Client } from 'npm:@aws-sdk/client-s3@3.264.0';
import { fromContainerMetadata } from 'npm:@aws-sdk/credential-providers@3.264.0';

console.log('Using fromContainerMetadata credentials');

const client = new S3Client({
    region: 'eu-west-1',
    credentials = fromContainerMetadata({ timeout: 2000, maxRetries: 1 })
});

console.log('S3 client created, executing ListObjectsCommand');

try {
    const res = await client.send(
        new ListObjectsCommand({
            Bucket: 'my-s3-bucket'
        }),
    );

    console.log(res);

    Deno.exit();
} catch (err) {
    console.log(err);
    Deno.exit(1);
}
```

3. Run the script: `deno run -A --reload main-container.ts`

Output:

The script is running and hanging forever:

<img width="1052" alt="Screenshot 2023-02-06 at 11 14 28" src="https://user-images.githubusercontent.com/133293/216961912-31a9a825-3ba6-4fa8-8803-37685e65112d.png">

## Test with credentials setup and `esm.sh`

1. [Install Deno](https://deno.land/manual@v1.30.2/getting_started/installation#download-and-install)
2. Create a deno script `main-esmsh.ts`:

```ts
import { ListObjectsCommand, S3Client } from 'https://esm.sh/@aws-sdk/client-s3@3.264.0';
// Note: fromContainerMetadata is not available from https://esm.sh/@aws-sdk/credential-providers@3.264.0
import { fromContainerMetadata } from 'https://esm.sh/@aws-sdk/credential-provider-imds@3.259.0';

console.log('Using fromContainerMetadata credentials');

const client = new S3Client({
    region: 'eu-west-1',
    credentials = fromContainerMetadata({ timeout: 2000, maxRetries: 1 })
});

console.log('S3 client created, executing ListObjectsCommand');

try {
    const res = await client.send(
        new ListObjectsCommand({
            Bucket: 'my-s3-bucket'
        }),
    );

    console.log(res);

    Deno.exit();
} catch (err) {
    console.log(err);
    Deno.exit(1);
}
```

3. Run the script: `deno run -A --reload main-esmsh.ts`

Output:

The script output an error:

<img width="1225" alt="Screenshot 2023-02-06 at 11 23 15" src="https://user-images.githubusercontent.com/133293/216962893-e3d08635-513e-4b4e-996d-1fd77e182205.png">

```sh
11:20:43  Using fromContainerMetadata credentials
11:20:43  S3 client created, executing ListObjectsCommand
11:20:43  Error: Credential is missing
11:20:43      at re.credentialProvider (https://esm.sh/v106/@aws-sdk/client-s3@3.264.0/deno/client-s3.js:4:183903)
11:20:43      at re.signRequest (https://esm.sh/v106/@aws-sdk/signature-v4@3.257.0/deno/signature-v4.js:3:522)
11:20:43      at re.sign (https://esm.sh/v106/@aws-sdk/signature-v4@3.257.0/deno/signature-v4.js:2:4709)
11:20:43      at sign (https://esm.sh/v106/@aws-sdk/signature-v4-multi-region@3.264.0/deno/signature-v4-multi-region.js:2:764)
11:20:43      at https://esm.sh/v106/@aws-sdk/middleware-signing@3.257.0/deno/middleware-signing.js:2:2366
11:20:43      at async https://esm.sh/v106/@aws-sdk/middleware-retry@3.259.0/deno/middleware-retry.js:2:5465
11:20:43      at async https://esm.sh/v106/@aws-sdk/middleware-logger@3.257.0/deno/middleware-logger.js:2:34
11:20:43      at async file:///tmp/jenkins/workspace/Playground/scriptTest/test-ec2-credentials/esmsh/main-container-esmsh.ts:26:17
```

### Observed Behavior

With a script executing a simple `ListObjectsCommand` on an S3 Bucket (scripts are provided in the reproduction step).

1. The script is hanging forever with either (no error, no output, no timeout):

- no credentials set
- the `npm:` specifier usage ([deno npm specifier](https://deno.land/manual@v1.30.2/node/npm_specifiers))

Output:

<img width="1052" alt="Screenshot 2023-02-06 at 11 14 28" src="https://user-images.githubusercontent.com/133293/216959382-20ec208c-735c-4dde-adfc-1f48958770f8.png">

2. The script outputs an error if we use an [esm.sh](https://esm.sh/) URL (see reproduction step).

```sh
import { ListObjectsCommand, S3Client } from 'https://esm.sh/@aws-sdk/client-s3@3.264.0';
import { fromContainerMetadata } from 'https://esm.sh/@aws-sdk/credential-provider-imds@3.259.0';
```

Note that I had to use `@aws-sdk/credential-provider-imds` instead of `@aws-sdk/credential-providers`, as with `esm.sh`, the `fromContainerMetadata` export is not available.

### Expected Behavior

To be logged in automatically.

### Additional Information/Context

Deno version:
```sh
deno 1.30.2 (release, aarch64-apple-darwin)
v8 10.9.194.5
typescript 4.9.4
```
OS:
Mac OS 12.1, Linux alpine, Linux Centos

**Comment by christophgysin** [comment] 2023-02-06 15:11
This is probably the same issue I fixed in https://github.com/aws/aws-sdk-js-v3/pull/1773 for credential_process.

**Comment by christophgysin** [comment] 2023-02-06 16:00
This was fixed in my fork using a custom implementation for deno: https://github.com/christophgysin/aws-sdk-js-v3/tree/deno/packages/credential-provider-imds-deno

**Comment by soundstep** [comment] 2023-02-07 08:16
Oh great, I'll look into that, thank you!

**Comment by soundstep** [comment] 2023-02-07 14:11
Am I wrong in thinking that the behavior I reported is related to the following package that is not working with Deno as it is using node bindings?
https://github.com/awslabs/aws-crt-nodejs
Is there any workaround?

**Comment by yenfryherrerafeliz** [comment] 2023-02-07 18:36
Hi @soundstep, thanks for opening this issue. I was able to reproduce the reported behavior, however, I am not very familiar with Deno runtime, and I am currently working on understanding what exactly maybe causing the issue here.

I will get back to you as soon as possible.

Thanks!

**Comment by cdeck95** [comment] 2023-02-19 17:42
@soundstep did you find a solution? I am running into the same problem. If so, do you mind showing your updated code or package references?

**Comment by yenfryherrerafeliz** [comment] 2023-02-20 00:20
Hi @soundstep, @cdeck95, sorry for the delay answering on this. Basically, this issue is caused by the http library that deno uses, which seems to be different from the one nodejs provides and therefore the request sent is rejected by the imds. Since we do not support Deno runtime, one thing you folks can do is to do a custom implementation to fetch the credentials from the instance metadata service. Actually that is what @christophgysin did.  [Here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html) is also the documentation. 

What I can do now is to mark this issue as feature request to gather community sentiments about this and take further actions based on it.

Thanks!

**Comment by soundstep** [comment] 2023-02-21 08:40
Thank you @yenfryherrerafeliz for looking into this. I think the reason why @christophgysin port has been abandoned is he cannot compile his sdk port anymore because of an underlying crt library, more info there: https://github.com/christophgysin/aws-sdk-js-v3/issues/38#issuecomment-1400969072
We have other EKS containers that run on [web identity token](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_providers.html#fromwebtoken), I will try to provide these credentials manually once I get the info I need to see how it goes.
@cdeck95 No solution so far I'm afraid, FYI see the IMDS port from @christophgysin [there](https://github.com/christophgysin/aws-sdk-js-v3/tree/deno/packages/credential-provider-imds-deno).

**Comment by soundstep** [comment] 2023-02-21 14:24
FYI, this works with [web identity token](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html) in containers (EKS), the credentials are picked up correctly:

```ts
import { ListObjectsCommand, S3Client } from 'npm:@aws-sdk/client-s3@3.264.0';

const client = new S3Client({
    region: Deno.env.get('AWS_REGION') || 'eu-west-1',
});

const res = await client.send(
    new ListObjectsCommand({
        Bucket: 'my-bucket',
    }),
);

console.log('response length:', res.Contents.length);
```

**Comment by andykais** [comment] 2023-12-02 01:17
another error that seems to be deno-specific:
```ts
import * as s3 from 'npm:@aws-sdk/client-s3'

const s3_client = new s3.S3({
  region: 'auto',
  endpoint: R2_BASE_URL,
  credentials: {
    accessKeyId: ACCESS_KEY_ID,
    secretAccessKey: ACCESS_KEY_SECRET,
  }
})

const result = await s3_client.createMultipartUpload({
  Bucket: 'MYBUCKET',
  Key: `${Date.now()}`,
})
```
gives this error:
```
error: Uncaught (in promise) 400: UnknownError
    at throwDefaultError (file:///home/andrew/node_modules/.deno/@smithy+smithy-client@2.1.16/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at file:///home/andrew/node_modules/.deno/@smithy+smithy-client@2.1.16/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:18:39
    at de_CreateMultipartUploadCommandError (file:///home/andrew/node_modules/.deno/@aws-sdk+client-s3@3.465.0/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:3276:12)
    at Object.runMicrotasks (ext:core/01_core.js:790:30)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:53:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
    at eventLoopTick (ext:core/01_core.js:184:21)
    at async file:///home/andrew/node_modules/.deno/@smithy+middleware-serde@2.0.14/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async file:///home/andrew/node_modules/.deno/@aws-sdk+middleware-signing@3.465.0/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:30:20
    at async file:///home/andrew/node_modules/.deno/@smithy+middleware-retry@2.0.21/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
```

running the same snippet in node (with a few changes like removing the `npm:` specifier and wrapping the top-level await) will succeed so I am confident this is a deno specific issue. I have also been able to run `S3::listObjects` in deno, so it seems to be some specific logic that is hit by this method.

This is using R2 so dont crucify me :sweat_smile:. This is how they would normally call your api from node https://developers.cloudflare.com/r2/reference/data-location/

**Comment by aBurmeseDev** [comment] 2024-04-10 23:37
Hey all - checking in here. 

This issue seems to be third-party related which we do not support as previously mentioned by my colleague here: https://github.com/aws/aws-sdk-js-v3/issues/4405#issuecomment-1436145300 

Please feel free to refer to the workarounds mentioned in the thread and we'll be closing this as not planned.

**Closed by aBurmeseDev** 2024-04-10 23:37 UTC
Labels: feature-request, third-party, p2
