### ISSUE TITLE
PutCommand gives an error if a table has a ttl attribute but this attribute it isn't present on the item being put

### ISSUE THREAD

**Issue by davidcarboni** [aws/aws-sdk-js-v3#5357] opened 2023-10-14 23:52 UTC
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I've set up a DynamoDB table with a ttl attribute.

If I try to put an item that has the ttl attribute specified, it works, e.g.:
```
  const item = { pk: 'test', sk: 'test', ttl: 1697326417}
  await documentClient.send(new PutCommand({
    TableName: "tableName",
    Item: item,
  }));
```

If I try to put an item that does not have the ttl attribute specified (so that an item won't expire) it throws an error, e.g.:
```
  const item = { pk: 'test', sk: 'test'}
  await documentClient.send(new PutCommand({
    TableName: "tableName",
    Item: item,
  }));
```
Produces:
```
TypeError: Cannot read properties of undefined (reading 'S')
    at AttributeValue.visit (/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/models/models_0.js:620:19)
    at se_AttributeValue (/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:2948:38)
    at /var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3345:20
    at Array.reduce (<anonymous>)
    at se_PutItemInputAttributeMap (/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3341:34)
    at Item (/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3332:22)
    at applyInstruction (/var/task/node_modules/@smithy/smithy-client/dist-cjs/object-mapping.js:73:33)
    at take (/var/task/node_modules/@smithy/smithy-client/dist-cjs/object-mapping.js:44:9)
    at se_PutItemInput (/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3326:37)
    at se_PutItemCommand (/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:266:27)
```

### SDK version number

@aws-sdk/lib-dynamodb@3.428.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node.js 18.x (Lambda)

### Reproduction Steps

Set up a dynamodb table with a ttl attribute, e,g, (CDK):
```
    const users = new Table(this, 'users', {
      tableName: 'tableName',
      partitionKey: { name: 'email', type: AttributeType.STRING },
      timeToLiveAttribute: 'ttl', // For generating/expiring test users
    });
```

Appempt to use `PutCommand` to write an item to the table without the ttl attribute, e.g.:
```
  await documentClient.send(new PutCommand({
    TableName: "tableName",
    Item: { email: 'user@example.com'},
  }));
```

### Observed Behavior

```
TypeError: Cannot read properties of undefined (reading 'S')
    at AttributeValue.visit (/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/models/models_0.js:620:19)
    at se_AttributeValue (/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:2948:38)
    at /var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3345:20
    at Array.reduce (<anonymous>)
    at se_PutItemInputAttributeMap (/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3341:34)
    at Item (/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3332:22)
    at applyInstruction (/var/task/node_modules/@smithy/smithy-client/dist-cjs/object-mapping.js:73:33)
    at take (/var/task/node_modules/@smithy/smithy-client/dist-cjs/object-mapping.js:44:9)
    at se_PutItemInput (/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3326:37)
    at se_PutItemCommand (/var/task/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:266:27)
```

### Expected Behavior

I expected:
 * the item to be written to the table
 * the ttl attribute to not be present on the item
 * the item to therefore not expire

### Possible Solution

I'm guessing something is getting lost in translation between `PutCommand` and `PutItemCommand`?

**Comment by davidcarboni** [comment] 2023-10-15 00:00
My current workaround is to set a dummy `string` value ttl, on the basis that, according to the documentation, this will mean the item is ignored by the expiry process: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/time-to-live-ttl-before-you-start.html

What I want to do is to put the item without any ttl attribute as those docs say that this will also mean the item is ignored for expiry.

**Comment by maplesteve** [comment] 2023-10-15 11:58
We're seeing this regression also since the update to v3.428.0 in several services.
@kuhe, @trivikr: maybe it's related to this [PR](https://github.com/aws/aws-sdk-js-v3/pull/5306)? Would be great if you could have a look and advise how to proceed.

**Comment by maplesteve** [comment] 2023-10-15 14:25
The error also occurs when no ttl is involved. Maybe a different scenario - so I created https://github.com/aws/aws-sdk-js-v3/issues/5360

**Comment by kuhe** [comment] 2023-10-16 18:05
Based on the error, I don't think this has anything to do with TTL. It looks like the same error as in #5360, which is due to an undefined column.

Are you potentially inserting an undefined value for `ttl`?

```js
await documentClient.put({
  TableName,
  Item: {
    email: '...@...',
    ttl: undefined
  }
});
```

If so, please remove the undefined key from the `Item` object before inserting it. There is also a fix https://github.com/aws/aws-sdk-js-v3/pull/5365 that will be in the next version that ignores top level undefined column values in `Item`s for backwards compatibility.


---

I was able to run the following code which sets a TTL column, and then inserts a row with and a row without a TTL:

```js
import { BillingMode, DynamoDB, waitUntilTableExists } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocument } from "@aws-sdk/lib-dynamodb";

const dynamodb = new DynamoDB({
  region: "us-west-2",
});

const doc = DynamoDBDocument.from(dynamodb, {});

await dynamodb.createTable({
  TableName: "test2",
  AttributeDefinitions: [
    {
      AttributeName: "id",
      AttributeType: "S",
    },
  ],
  KeySchema: [
    {
      AttributeName: "id",
      KeyType: "HASH",
    },
  ],
  BillingMode: BillingMode.PAY_PER_REQUEST,
});

await waitUntilTableExists(
  { client: dynamodb, maxWaitTime: 30 },
  {
    TableName: "test2",
  }
);

await dynamodb.updateTimeToLive({
  TableName: "test2",
  TimeToLiveSpecification: {
    Enabled: true,
    AttributeName: "ttl",
  },
});

await doc.put({
  TableName: "test2",
  Item: { id: "1", data: "some data", ttl: 1697326417 },
});

await doc.put({
  TableName: "test2",
  Item: { id: "2", data: "some data2" },
});
```

**Comment by davidcarboni** [comment] 2023-10-17 12:22
Thanks @kuhe yes, that's correct, the ttl value would be set to undefined if not set to a value. That gives me an option so thank you.

For completeness, my client is set up as follows, which I thought would handle undefined columns:

```
export const documentClient = DynamoDBDocumentClient.from(
  new DynamoDBClient(),
  // This should handle keys that are undefined
  { marshallOptions: { removeUndefinedValues: true } },
);
```

I previously ran into an issue with undefined columns so put the above in place a while back. I wonder what's different about what I'm doing with the ttl that isn't being handled by the `marshallOptions`?

**Comment by kuhe** [comment] 2023-10-17 14:15
it's explained in more detail in https://github.com/aws/aws-sdk-js-v3/issues/5360, but in summary, there was a fix to correct what nodes are considered AttributeValue (DynamoDB) and subject to the marshalling and unmarshalling transforms.

`Item` itself was incorrectly considered one before, it actually isn't or it would be transformed as 
a `Map` (DynamoDB) `{ M: ... }`. The fix removed `undefined` processing for things that aren't AttributeValues, but users including you were relying on the filtering behavior at the top level, so it was restored in https://github.com/aws/aws-sdk-js-v3/pull/5365. This PR maintains the behavior of top level filtering while not removing the earlier fixes.

**Comment by kuhe** [comment] 2023-10-17 14:16
This version contains the compatibility fix: https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.429.0

**Closed by kuhe** 2023-10-17 14:15 UTC
Labels: response-requested, bug, p2

**Comment by davidcarboni** [comment] 2023-10-17 17:16
Thanks for the eplanation and poinetrs @kuhe I've now updated to 3.429.0
