### ISSUE TITLE
@aws-sdk/client-kinesis - 3.410.0 - breaking change in constructor

### ISSUE THREAD

**Issue by eau-de-la-seine** [aws/aws-sdk-js-v3#5201] opened 2023-09-12 10:12 UTC
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Breaking change of KinesisClient constructor

Here what it looks like:
```ts
/**
 * @public
 * <fullname>Amazon Kinesis Data Streams Service API Reference</fullname>
 *          <p>Amazon Kinesis Data Streams is a managed service that scales elastically for real-time
 *             processing of streaming big data.</p>
 */
export declare class KinesisClient extends __Client<__HttpHandlerOptions, ServiceInputTypes, ServiceOutputTypes, KinesisClientResolvedConfig> {
    /**
     * The resolved configuration of KinesisClient class. This is resolved and normalized from the {@link KinesisClientConfig | constructor configuration interface}.
     */
    readonly config: KinesisClientResolvedConfig;
    constructor(...[configuration]: __CheckOptionalClientConfig<KinesisClientConfig>);
    /**
     * Destroy underlying resources, like sockets. It's usually not necessary to do this.
     * However in Node.js, it's best to explicitly shut down the client's agent when it is no longer needed.
     * Otherwise, sockets might stay open for quite a long time before the server terminates them.
     */
    destroy(): void;
}
```

### SDK version number

@aws-sdk/client-kinesis@3.410.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.20.2

### Reproduction Steps

Does not compile anymore:
```ts
new KinesisClient({ region: LOCALSTACK_REGION, endpoint: LOCALSTACK_ENDPOINT, requestHandler: new NodeHttpHandler() });
```

Notice the wrapper array I had to add in order to make it compile, this compiles but the signature is wrong:
```ts
new KinesisClient([{ region: LOCALSTACK_REGION, endpoint: LOCALSTACK_ENDPOINT, requestHandler: new NodeHttpHandler() }]);
```

### Observed Behavior

The typescript signature has changed, the constructor is now broken

### Expected Behavior

The signature should respect the documentation https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-kinesis

### Possible Solution

Fix typescript signature, do tests before committing

**Comment by syuilo** [comment] 2023-09-12 11:19
I have the same issue.
And this is not only happening with KinesisClient, but also with S3Client.

**Comment by kuhe** [comment] 2023-09-12 16:59
The constructor type is `...[configuration]` (rest) and not `[configuration]` (array). This means it has zero or one argument.

The previous signature required one argument, and the change makes it optional. 

You can see this at work in this example: [typescript playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAwgFhAxgawPJmASwPYDsCGANjIZhLsDHgGaYDmAPACoB8UAvFAKIAe+iwBgAV8AJyxFmLADRRWUCD2DkAJgGcowUQFdoAfigBtALpQAPkaamAXJeMBuAFChI3PgObgIARllMvAExsnIb+kN6misq46paBpgYAFKHxCkqqGinhCZo60LbURGoQAJRQBUUQTs5esDT0HFAA3o5QbVCiEHQ4uHq2alqYuHSOAL6OjoiE+GoaAILNrW1g2gBGpIhQiHgDOgLYoonbuLR0tlQn9GVN4+OT07NQAEKL7SvrmJvHu9r7hwB0gMMx1OxnOCBQ6CweCIJDIFAupwYiPoLGutwmkx2wCg+G8tgWnFwEAA7lA5okSvYoAB6GmaWoQUSiA5pSACCAqWRiOjaAC25BxuGwOOwGB6RH+WNwA1xAQJjWJZIpTQ6XR6tgA5PhNVBRlSJt8cat8c9FaTnpSnEaoKt5WaiRanolVZ1ungtatdfr7EA)

Which shows it works as far back as TS 3.3.

**Comment by raphaelmacsabpf** [comment] 2023-09-12 17:46
I had the same issue with `@aws-sdk/client-s3`, by now I'll try to lock my version to `3.405.0` which it's working fine.
I'm quite disappointed with how AWS handled that migration from v2 to v3, They sell something easy and straightforward, and they indeed provide a tool to migrate, but the tool is poor and makes a lot of mistakes.

**Comment by yenfryherrerafeliz** [comment] 2023-09-13 16:32
@eau-de-la-seine, @syuilo, did you see the comment from @kuhe [here](https://github.com/aws/aws-sdk-js-v3/issues/5201#issuecomment-1716106521)?, is this comment helpful for you or are you still having the same issue?

Please let me know.

Thanks!

**Comment by joostrovers** [comment] 2023-09-13 17:51
I also have the same issue. I'm not an expert in typescript definition, and in principle I would agree that the constructor parameter could be optional, but it still remains that the practical effect of latest update is that existing code no longer compiles.

**Comment by yenfryherrerafeliz** [comment] 2023-09-13 21:56
Hi @eau-de-la-seine, @joostrovers would it be possible for you to please provide the error that you are getting when compiling?, could you please also provide the typescript version that you are using?

Thanks!

**Comment by antti-manninen-vmv** [comment] 2023-09-14 04:18
I had similar problems but it complains about use of `NodeHttpHandler` in `requestHandler` after aws-sdk update. 

```
new S3({ requestHandler: new NodeHttpHandler() })
```

```
TS2345: Argument of type  [{ requestHandler: NodeHttpHandler; }]  is not assignable to parameter of type  [S3ClientConfig] | [] 
Type  [{ requestHandler: NodeHttpHandler; }]  is not assignable to type  [S3ClientConfig] 
Type  { requestHandler: NodeHttpHandler; }  is not assignable to type  S3ClientConfig 
Type  { requestHandler: NodeHttpHandler; }  is not assignable to type  ClientDefaults 
Types of property  requestHandler  are incompatible.
Type  NodeHttpHandler  is not assignable to type  HttpHandler 
Type  NodeHttpHandler  is missing the following properties from type
{     updateHttpClientConfig(key: never, value: never): void;     httpHandlerConfigs(): {}; }
:  updateHttpClientConfig, httpHandlerConfigs 
```

It can be fixed by wrapping parameters in array but I suppose it is not what is wanted.

```
new S3([{ requestHandler: new NodeHttpHandler() }])
```

**Comment by eau-de-la-seine** [comment] 2023-09-14 13:51
So here how i fixed the issue:
* Using the latest @aws-sdk v3 dependencies
* Using latest [@smithy/node-http-handler](https://www.npmjs.com/package/@smithy/node-http-handler) instead of [@aws-sdk/node-http-handler](https://www.npmjs.com/package/@aws-sdk/node-http-handler), and replacing imports
* Using latest [@smithy/util-stream](https://www.npmjs.com/package/@smithy/util-stream) instead of [@aws-sdk/util-stream](https://www.npmjs.com/package/@aws-sdk/util-stream), and replacing imports

**Comment by timtucker-dte** [comment] 2023-09-15 13:55
Here's the minimum that I see that triggers errors for me:
```
import { S3ClientConfig } from '@aws-sdk/client-s3';
import { NodeHttpHandler } from '@aws-sdk/node-http-handler';

const config: S3ClientConfig = {
    requestHandler: new NodeHttpHandler(),
};
```

which produces the following error:
> Type 'NodeHttpHandler' is not assignable to type 'RequestHandler<any, any, HttpHandlerOptions> & RequestHandler<HttpRequest, HttpResponse, HttpHandlerOptions> & { ...; }'.
>   Type 'NodeHttpHandler' is missing the following properties from type '{ updateHttpClientConfig(key: never, value: never): void; httpHandlerConfigs(): {}; }': updateHttpClientConfig, httpHandlerConfigs

**Comment by yenfryherrerafeliz** [comment] 2023-09-26 18:51
Hi @timtucker-dte, please check the following comment [here](https://github.com/aws/aws-sdk-js-v3/issues/5201#issuecomment-1719495635), which I confirm is correct and that indicates how to resolve the issue. Basically, the problem is that you are using different versions for the SDK packages, and they are most likely desired to be in the same version so you do not get any version mismatch issues. 

I will resolve this issue, but please open a new issue if is there anything else that we can help with.

Thanks!

**Closed by yenfryherrerafeliz** 2023-09-26 18:51 UTC
Labels: bug, p2
