### ISSUE TITLE
AthenaClient does not implement ExecutionParameters

### ISSUE THREAD

**Issue by rmbrich** [aws/aws-sdk-js-v3#3837] opened 2022-08-01 20:34 UTC
### Describe the bug

In AthenaClient, [StartQueryExecutionCommandInput](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-athena/interfaces/startqueryexecutioncommandinput.html) specifies that **ExecutionParameters** can be passed for use in parameterized queries. However, this does not seem to be implemented.

### Expected Behavior

Passing an array of strings to ExecutionParameters should apply those to a parameterized query in Athena

### Current Behavior

```console
Error: {
  "ErrorCategory": 2,
  "ErrorMessage": "Incorrect number of parameters: expected 1 but found 0",
  "ErrorType": 1006,
  "Retryable": false
}
```

### Reproduction Steps

Try to run a parameterized query using StartQueryExecutionCommand and pass ExecutionParameters

### Possible Solution

`@aws-sdk\client-athena\dist-types\models\models_0.d.ts` interface `StartQueryExecutionInput` does not mention `ExecutionParameters`.

### SDK version used

3.100.0

### Environment details (OS name and version, etc.)

Windows 10, Node 14.18.3

**Comment by RanVaknin** [comment] 2022-08-01 23:04
@rmbrich ,

In order for me to accurately reproduce your issue please add minimal reproduction code. 
- How you set up your resources. S3? which type objects?
- Add relevant code including import statements.

Thank you.

**Comment by rmbrich** [comment] 2022-08-02 17:23
In Athena console, run each of these statements individually:
```
create table test_me as
select '1' as a, '2' as b;

select * from test_me;  -- This works

select * from test_me where a = ?; -- This works - Athena console prompts for parameter value to use
```

In Node:
```
const { AthenaClient, StartQueryExecutionCommand, GetQueryExecutionCommand, GetQueryResultsCommand } = require('@aws-sdk/client-athena')
const athena = new AthenaClient({})

const test_me = async () => {
   try {
      let result1 = await athena.send(new StartQueryExecutionCommand({
         QueryExecutionContext: {
            Database: 'lake_dev'
         },
         QueryString: 'select * from test_me',
         WorkGroup: 'primary'
      }))
      console.log(result1) // this works

      let result2 = await athena.send(new StartQueryExecutionCommand({
         QueryExecutionContext: {
            Database: 'lake_dev'
         },
         QueryString: 'select * from test_me where a = ?',
         ExecutionParameters: ['1'],
         WorkGroup: 'primary'
      }))
      console.log(result2) // this submits, but errors in Athena

   } catch(e) {
      console.log(e)
   }
}
test_me()
```

Now check Recent queries in Athena console. The first one ran successfully, the second fails with error `SYNTAX_ERROR: line 1:1: Incorrect number of parameters: expected 1 but found 0`

I believe `ExecutionParameters` is being ignored by AthenaClient.

**Comment by RanVaknin** [comment] 2022-08-02 23:44
I'm not able to reproduce your issue.

Im running into a different issue based on your code:
```console
SYNTAX_ERROR: line 1:31: '=' cannot be applied to varchar(1), integer
This query ran against the "default" database, unless qualified by the query.
```

This can be fixed by passing the execution parameters a string (right now its an int)

```js
const command2 = new StartQueryExecutionCommand({
    QueryExecutionContext: {
       Database: 'default'
    },
    QueryString: 'select * from test_me where a = ?',
    ExecutionParameters: ["'1'"],
    WorkGroup: 'primary',
});
```

Maybe I am missing something? Let me know if this helps at all.
Thanks.

**Closed** 2022-08-04 13:32 UTC
Labels: bug
