### ISSUE TITLE
Missing paginator for DescribeVpcEndpointServicesCommand

### ISSUE THREAD

**Issue by Nevon** [aws/aws-sdk-js-v3#6713] opened 2024-12-03 16:11 UTC
### Describe the feature

Add a function such as `paginateDescribeVpcEndpointServices`.

### Use Case

There are paginators available for most other commands, but not `DescribeVpcEndpointServicesCommand`. Having a paginator prevents bugs from incorrectly implementing pagination.

### Other Information

Since the paginators are generated, as far as I know, I'm not sure why this command didn't also get a paginator. Perhaps it is incorrectly described in some API definition.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.679.0

### Environment details (OS name and version, etc.)

-

**Comment by RanVaknin** [comment] 2024-12-06 18:42
Hi @Nevon ,

This is a duplicate of https://github.com/aws/aws-sdk-go-v2/issues/2611

I have reached out to the VPC service team to add this to their model but never heard back. I will follow up again but as I mentioned on the original ticket, this is not something that the SDK team can add ourselves, and we have no visibility as to when/if this is going to get implemented. For this reason I'm going to close this issue. If you have access to AWS support feel free to open a ticket via the developer console and reference my existing internal ticket `#P126629878`. 

Thanks again,
Ran~

**Closed** 2024-12-06 18:43 UTC
Labels: feature-request, service-api
