### ISSUE TITLE
Dynamo unmarshalled utility in aws-sdk v3 is not compatible with queried data returned from AWS StepFunctions

### ISSUE THREAD

**Issue by tienlenan** [aws/aws-sdk-js-v3#5423] opened 2023-10-27 09:59 UTC
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Queried DynamoDB data returned from StepFuntions can not be unmarshalled in Lambda function by new aws sdk v3

> Unsupported type passed: Bool

### SDK version number

@aws-sdk/util-dynamodb@3.435.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node 18

### Reproduction Steps

I have a StepFunctions that worked as below:
1. Query items from DynamoDB
2. Pass the list that is queried before to Lambda function to handle business logic
3. Use `unmarshall` utility function provided by @aws-sdk/util-dynamodb
4. Error `"Unsupported type passed: Bool",` returned in StepFunction

This problem occurred after we migrated aws sdk from `v2` to `v3`

After debugged I found the issue of `unmarshall` function. It call `convertToNative` and this function does not support `Bool` type in StepFunctions response. Below is our data example:
```json
"wct": { "Bool": false }
```
And the source from aws sdk as below:
```javascript
export const convertToNative = (data, options) => {
    for (const [key, value] of Object.entries(data)) {
        if (value !== undefined) {
            switch (key) {
                case "NULL":
                    return null;
                case "BOOL":
                    return Boolean(value);
                case "N":
                    return convertNumber(value, options);
                case "B":
                    return convertBinary(value);
                case "S":
                    return convertString(value);
                case "L":
                    return convertList(value, options);
                case "M":
                    return convertMap(value, options);
                case "NS":
                    return new Set(value.map((item) => convertNumber(item, options)));
                case "BS":
                    return new Set(value.map(convertBinary));
                case "SS":
                    return new Set(value.map(convertString));
                default:
                    throw new Error(`Unsupported type passed: ${key}`);
            }
        }
    }
    throw new Error(`No value defined: ${JSON.stringify(data)}`);
};
```

Work Around: I have to modify JSON data returned from StepFunctions. `Bool` key would be changed to `BOOL`.

### Observed Behavior

Unsupported type passed: Bool

### Expected Behavior

Successfully unmarshall and return javascript native object

### Possible Solution

Modify StepFunctions implementation to return compatible json data with new aws sdk

### Additional Information/Context

Same issue with #4948

**Comment by tienlenan** [comment] 2023-10-27 10:15
@yenfryherrerafeliz Hi, I have a quick check at #4948. Seem likes this issue is same with this one and also not resolved yet.
Could you check it? Thanks!!!

**Comment by kuhe** [comment] 2023-10-27 16:12
`Bool` is not an accepted DynamoDB AttributeValue type. It must be 'BOOL'. Your workaround is required.

**Comment by kuhe** [comment] 2023-10-27 16:14
If you want to use DynamoDB AttributeValues, use the DynamoDB client directly. 

If you want to marshal/unmarshal to Native JS types, use https://www.npmjs.com/package/@aws-sdk/lib-dynamodb

**Comment by tienlenan** [comment] 2023-10-27 18:49
@kuhe Hi. We use the original data from DynamoDB: Query. Please check the picture as below.
Then our system passes the queried data directly to Lambda function, we do not modify or provide a custom data structure.
In the old version of SDK (v2), it worked normally. 
![stepfunc](https://github.com/aws/aws-sdk-js-v3/assets/10125208/837ed590-d0ac-4a29-b674-94aae345fb4e)

**Comment by tienlenan** [comment] 2023-10-27 18:54
![error_step](https://github.com/aws/aws-sdk-js-v3/assets/10125208/c44381cc-4dd8-4001-8a35-71734ede90a7)
You can see the picture above. It's apart of our StepFunctions workflow.
`The Blue` step returns data containing `Bool` not `BOOL`.
As mentioned before, we use @aws-sdk/util-dynamodb to marshall/unmarshall DynamoDB data.

Please recheck it. It might be the issue from AWS StepFunction.

**Comment by tienlenan** [comment] 2023-10-27 18:56
Please not that we don't modify the data structure returned by `DynamoDB: Query`.

**Comment by kuhe** [comment] 2023-10-30 13:19
related https://github.com/aws/aws-sdk-js/issues/4294

the step function returns incorrect capitalization, I've opened an internal ticket.

**Comment by tienlenan** [comment] 2023-10-30 13:24
> related https://github.com/aws/aws-sdk-js/issues/4294
> 
> 
> 
> the step function returns incorrect capitalization, I've opened an internal ticket.
> 
> 

That would be great. Thank you.

**Comment by cadam11** [comment] 2023-11-08 21:14
@kuhe Is there a better place to track this bug than here? It's about Step Functions, not the JS SDK.

Also, I notice that the same state returns `"Nul": true` instead of `"NULL": true` – hopefully the internal team can fix both issues by ensuring the returned results comply with the [DynamoDB API documentation](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Scan.html)

**Comment by kuhe** [comment] 2023-11-10 17:54
I don't have any update from the internal ticket. You could try using AWS support through your AWS account.

**Comment by aBurmeseDev** [comment] 2024-08-29 00:13
Hi everyone - checking in. 

I have looked into this internally and followed up to the AWS Step Functions service team. (Ref: _ER-TT-5544_) Here's their response:

> The behavior you're encountering is expected and documented: https://docs.aws.amazon.com/step-functions/latest/dg/supported-services-awssdk.html 
This is a known behavior, and we cannot make any changes to it at the moment. This behavior is present in both our optimized integrations for DynamoDB as well as our AWS SDK integrations.

Since this is an expected behavior as per the AWS Step Functions service team, and there are no action items for the AWS SDK team, I will be closing this issue. However, if you need further assistance or have additional concerns, please feel free to reach out to the AWS Support team directly at [AWS Support](https://aws.amazon.com/contact-us/).

**Closed by aBurmeseDev** 2024-08-29 00:13 UTC
Labels: guidance, service-api, p2
