### ISSUE TITLE
TypeError: (0 , shared_ini_file_loader_1.parseKnownFiles) is not a function when deploying app to amplify with Cypress testing in build script

### ISSUE THREAD

**Issue by AgoraRich** [aws/aws-sdk-js-v3#4792] opened 2023-06-06 16:04 UTC
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

https://github.com/aws/aws-sdk-js-v3/issues/3806#issue-1309040120

I am having this exact issue occurring in my CI/CD. Is anyone able to explain where this is coming from? When I run Cypress locally it runs fine without any errors. 

### SDK version number

@aws-sdk/credential-providers@3.345.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v19.6.1

### Reproduction Steps

Set up a CI/CD `version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  phases:
    preTest:
      commands:
        - yarn add -D pm2 wait-on mocha mochawesome mochawesome-merge mochawesome-report-generator
        - npx pm2 start "yarn start"
        - npx wait-on http-get://localhost:3000
    test:
      commands:
        - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json -o cypress/testConfig.json
        - npx marge -o cypress cypress/testConfig.json
        - npx pm2 kill
  artifacts:
    baseDirectory: cypress
    configFilePath: testConfig.json
    files:
      - '**/*.mp4'
      - 'testConfig.html'
      - 'assets/**'`

Then have the following in the cypress.config.ts

`import { defineConfig } from 'cypress';
import { fromNodeProviderChain } from '@aws-sdk/credential-providers';
import preprocessor from '@cypress/webpack-preprocessor';

const webpackOptions = {
  resolve: {
    extensions: ['.ts', '.js'],
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        exclude: /node_modules/,
        loader: 'ts-loader',
      },
    ],
  },
};

async function resolveAWSCreds(config: Cypress.PluginConfigOptions) {
  config.env.awscredentials = await fromNodeProviderChain()();
  return config;
}

export default defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      on('file:preprocessor', preprocessor({ webpackOptions }));
      on('task', {
        generateOTP: require('cypress-otp'),
      });
      config.baseUrl = 'http://localhost:3000/';
      config.supportFile = 'cypress/support/e2e.ts';
      return resolveAWSCreds(config);
    },
  },
});
`

push to amplify to deploy.

### Observed Behavior

Error in amplify is

`Your configFile threw an error from: /codebuild/output/src162527060/src/webapp/cypress.config.ts
                                 The error was thrown while executing your e2e.setupNodeEvents() function:
2023-06-06T14:48:56.385Z [INFO]: TypeError: (0 , shared_ini_file_loader_1.parseKnownFiles) is not a function`

### Expected Behavior

Tests to run.

**Comment by AgoraRich** [comment] 2023-06-07 09:48
I solved this by adding 

` - rm -rf node_modules && yarn install --frozen-lockfile`

to the pre-build step in amplify. There is obviously some sort of dependency issue with this package that needs looking into as this is the same issue that happened in the thread I linked to.

**Comment by yenfryherrerafeliz** [comment] 2023-06-26 13:55
Hi @AgoraRich, sorry for the delay on this. According to the following [comment](https://github.com/aws/aws-sdk-js-v3/issues/3806#issuecomment-1190676490) seems that the issue is that somehow a dependency is not being updated properly which causes this issue. That also explains why deleting the node_modules folder and reinstalling the dependencies the issue gets fixed. I actually tried again to reproduce this on my end and I got not issues.

I will close this issue since you already fixed it, but please if you face this error again or any other type of errors feel free to open a new issue.

Thanks!

**Closed by yenfryherrerafeliz** 2023-06-26 13:55 UTC
Labels: bug, needs-triage
