### ISSUE TITLE
Shape not found

### ISSUE THREAD

**Issue by leon-adarcewicz** [aws/aws-sdk-js-v3#5047] opened 2023-08-03 13:05 UTC
### Describe the issue

```json
{"name":"AttributeValue.MMember","pkg":"@aws-sdk/client-dynamodb","type":"Interface","text":"MMember"}
```

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/preview/client/dynamodb/command/PutItemCommand/

**Comment by leon-adarcewicz** [comment] 2023-08-24 10:27
Hi @yenfryherrerafeliz!
As I'm thinking now, maybe it's not the best place to report such stuff here,
but I couldn't figure out how to use

            "<keys>": "<AttributeValue>",
          },
          L: [ // ListAttributeValue
            "<AttributeValue>",
          ],
attributes to store the data into DynamoDB.
If you can, it would be great to add some examples to the official page within Example Usage

**Comment by kuhe** [comment] 2023-10-03 17:35
duplicate of https://github.com/aws/aws-sdk-js-v3/issues/5264

**Closed by kuhe** 2023-10-03 17:35 UTC
Labels: documentation
