### ISSUE TITLE
IoTClient is sending body content with a Get request

### ISSUE THREAD

**Issue by GrahamFord** [aws/aws-sdk-js-v3#1570] opened 2020-10-13 16:16 UTC
**Describe the bug**
Using a command that sends a Get request to the AWS api, the IoTClient is attempting to set the body to `{}`. The Fetch code is rejecting this with the message `TypeError: Request constructor: HEAD or GET Request cannot have a body.`

**SDK version number**
1.0.0-gamma.11

**Is the issue in the browser/Node.js/ReactNative?**
Browser

**Details of the browser/Node.js/ReactNative version**
Browsers:
    Chrome: 86.0.4240.75
    Edge: 85.0.564.63
    Firefox: 81.0.1
    Safari: 14.0

**To Reproduce (observed behavior)**
I've uploaded a minimal application that demonstrates the problem. It won't actually run on StackBlitz but it will when downloaded locally.

https://angular-client-iot.stackblitz.io

1. Download the code from StackBlitz as a zip file
1. Expand the zip file
1. Change to the new directory
1. Install the dependencies with `npm install`
1. Start the application with `npm run start`
1. Go to `http://localhost:4200` in a browser

When the page is loaded in a browser, the console shows the error:
``` Console
Error: TypeError: Request constructor: HEAD or GET Request cannot have a body.
    handle fetch-http-handler.js:41
    resolveMiddleware GetIndexingConfigurationCommand.js:29
    deserializerMiddleware deserializerMiddleware.js:8
    step tslib.es6.js:100
    verb tslib.es6.js:81
    __awaiter tslib.es6.js:74
    ZoneAwarePromise Angular
    __awaiter tslib.es6.js:70
    deserializerMiddleware deserializerMiddleware.js:2
    awsAuthMiddleware middleware.js:36
    step tslib.es6.js:100
    verb tslib.es6.js:81
    fulfilled tslib.es6.js:71
    Angular 22
    digest webCryptoSha256.js:35
    Angular 17
    RxJS 5
    Angular 18
app.component.ts:23:28
```

**Expected behavior**
The call should return a json object.

**Screenshots**

**Additional context**

**Comment by alexforsyth** [comment] 2020-10-30 19:29
Looks like a possible duplicate of https://github.com/aws/aws-sdk-js-v3/issues/1633. Letting @AllanFly120 figure out which one to close

**Comment by AllanZhengYP** [comment] 2020-12-08 19:44
Close as duplication of https://github.com/aws/aws-sdk-js-v3/issues/1633

**Closed by AllanZhengYP** 2020-12-08 19:44 UTC
