### ISSUE TITLE
Set the default Content-Type for a PUT-signed URL

### ISSUE THREAD

**Issue by garysassano** [aws/aws-sdk-js-v3#5453] opened 2023-11-05 22:30 UTC
### Describe the feature

I'd like to be able to specify a default Content-Type when using PUT-signed URL for uploading objects to an S3 bucket.

### Use Case

I have the following code:

```ts
public async signedUrl(
  key: string,
  opts: BucketSignedUrlOptions
): Promise<string> {
  // Check if the object exists for GET requests
  if (
    opts.action === BucketSignedUrlAction.DOWNLOAD &&
    !(await this.exists(key))
  ) {
    throw new Error(
      `Cannot provide a GET-signed URL for a non-existent object (key=${key}).`
    );
  }

  // Define the AWS S3 command based on the action type
  let command;
  switch (opts.action) {
    case BucketSignedUrlAction.DOWNLOAD:
      command = new GetObjectCommand({
        Bucket: this.bucketName,
        Key: key,
      });
      break;
    case BucketSignedUrlAction.UPLOAD:
      command = new PutObjectCommand({
        Bucket: this.bucketName,
        Key: key,
        ContentType: "application/octet-stream",
      });
      break;
    default:
      throw new Error(`Invalid action type: ${opts.action}`);
  }

  // Generate the signed URL
  const signedUrl = await getSignedUrl(this.s3Client, command, {
    expiresIn: opts.duration?.seconds, // If not set, it defaults to 900
  });

  return signedUrl;
}
```

When you use a PUT-signed URL without specifying a header in the request, the Content-Type automatically defaults  to `binary/octet-stream`. I am not pleased with this default since it does not conform to the standard [IANA media types](https://www.iana.org/assignments/media-types/media-types.xhtml). Therefore, I would like to set `application/octet-stream` as the default Content-Type for the generated PUT-signed URL.

This is the command I use for uploading an object to the S3 bucket:
```
curl -X PUT -T <FILE> <PUT_SIGNED_URL>
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

v3.443.0

### Environment details (OS name and version, etc.)

Windows 11 Enterprise 23H2

**Comment by garysassano** [comment] 2023-11-05 22:36
I would basically like to have the same thing that there's in [GCP signedUrl options](https://github.com/googleapis/nodejs-storage/blob/2ba4009e599c5690c51849f307199be3452d3b07/samples/generateV4UploadSignedUrl.js#L43-L48).

**Comment by RanVaknin** [comment] 2023-11-07 07:12
Hi @garysassano

After looking at your code and doing some digging on my side, I think that the core of the issue you're experiencing is not with the default Content-Type behavior of the presigner but rather with the signature process of the presigned URL. 
By default the presigner does not sign the Content-Type header. 

So with this kind of request:

```js
const command = new PutObjectCommand({
    Bucket: bucketName,
    Key: objectKey,
    ContentType: contentType,
  });

    const signedUrl = await getSignedUrl(s3Client, command, {
        expiresIn: 3600,
    });
  return signedUrl;
```

You'll end up with something like this presigned URL

```console
https://bucket.us-east-1.amazonaws.com/key?
X-Amz-Algorithm=AWS4-HMAC-SHA256&
X-Amz-Content-Sha256=UNSIGNED-PAYLOAD
&X-Amz-Credential=REDACTED/20231107/us-east-1/s3/aws4_request&
X-Amz-Date=20231107T065248Z&
X-Amz-Expires=3600&
X-Amz-Signature=REDACTED
&X-Amz-SignedHeaders=host  <---- missing content-type
&x-id=PutObject  
```
To ensure that the Content-Type is enforced, it must be included in the X-Amz-SignedHeaders at the time of generating the presigned URL. If it's not signed, the S3 service will accept the upload with any Content-Type if the Content-Type was not specified as a signed header, even if it differs from what was intended.

You can "allowlist" the desired header, so that the presigner will sign it, and that the service will enforce it:

```js
    const signedUrl = await getSignedUrl(s3Client, command, {
        expiresIn: 3600,
        signableHeaders: new Set(['content-type']),
    });
```

This will result in the following Presigned URL:
```console
https://bucket.us-east-1.amazonaws.com/key?
X-Amz-Algorithm=AWS4-HMAC-SHA256&
X-Amz-Content-Sha256=UNSIGNED-PAYLOAD
&X-Amz-Credential=REDACTED/20231107/us-east-1/s3/aws4_request&
X-Amz-Date=20231107T070035Z&
X-Amz-Expires=3600&
X-Amz-Signature=REDACTED
&X-Amz-SignedHeaders=content-type;host
&x-id=PutObject
```

When a presigned URL is generated without including the Content-Type in the signed headers, S3 will not enforce this header upon upload. This means that regardless of whether the Content-Type is provided in the PUT request, the service will accept the upload if the rest of the signed components match.

Please give this a try and let me know if this solves your problem. 

All the best,
Ran~

**Comment by garysassano** [comment] 2023-11-07 09:42
@RanVaknin This is not what I'm looking for sadly. All this does is making the Content-Type header mandatory in the request.

So you go from this:
```sh
curl -X PUT -T <FILE> <PUT_SIGNED_URL>
```

To this:
```sh
curl -X PUT -T <FILE> -H <CONTENT_TYPE_HEADER> <PUT_SIGNED_URL>
```

Instead, I don't want to specify the Content-Type in the request. I just want to change the default when it's not specified, while also giving the user the option to manually specify it they want to override the default I set.

**Comment by RanVaknin** [comment] 2023-11-07 20:25
Hi @garysassano,

I understand the issue better now, thanks for the clarification. The default MIME type (binary/octet-stream) assigned to objects without an explicit content-type value is controlled by the _S3 service_, and _not the SDK_. 

After looking around a bit more I found a [similar issue](https://github.com/aws/aws-sdk-java/issues/1143) that was opened with the Java SDK. This particular issue was not with presigned URL, so the solution here does not apply, but it highlights the how the service is the entity that sets a default MIME type.

Your only course of action is either to enforce the application/octet-stream type by explicitly signing it (I know its not the solution you are looking for but rather a workaround). Or you can use the AWS console to open a support ticket directly with the S3 team regarding the default MIME type that gets assigned to put requests without explicit content-type. 

If you decide to go that route, please feel free to mention my alias `@rvaknin`, as the S3 team might want to a point of contact from the SDK team. Since this ticket is not actionable by the SDK team Im inclined to close it.

Thanks again,
Ran~

**Closed by RanVaknin** 2023-11-07 20:25 UTC
Labels: feature-request, response-requested, p2

**Comment by garysassano** [comment] 2023-11-07 21:57
While it may be a challenge to get approval, I'm contemplating the idea of opening a support ticket. I believe the default MIME type should be `application/octet-stream` since that's the fallback standard when a file's MIME type can't be determined, as noted in the [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types).

In contrast to the other AWS SDKs, the Java SDK for AWS is unique in that it includes MIME type recognition, automatically identifying and assigning the correct Content-Type for uploaded files, as detailed in the [AWS Java SDK documentation](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/ObjectMetadata.html#getContentType--). It also correctly uses `application/octet-stream` as the default value.

Both GCP and Azure have adopted `application/octet-stream` as the default Content-Type for their object storage services.  Hence, there seems to be a strong case for adjusting the default vakue for AWS S3 to align it with the standard.

**Comment by garysassano** [comment] 2023-11-07 21:59
While it may be a challenge to get approval, I'm contemplating the idea of opening a support ticket. I believe the default MIME type should be `application/octet-stream` since that's the fallback standard when a file's MIME type can't be determined, as noted in the [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types).

In contrast to the other AWS SDKs, the Java SDK for AWS is unique in that it includes MIME type recognition, automatically identifying and assigning the correct Content-Type for uploaded files, as detailed in the [AWS Java SDK documentation](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/ObjectMetadata.html#getContentType--). It also correctly uses `application/octet-stream` as the default value.

Both GCP and Azure have adopted `application/octet-stream` as the default Content-Type for their object storage services.  Hence, there seems to be a strong case for adjusting the default value for AWS S3 to align it with the standard.

**Comment by garysassano** [comment] 2023-11-07 21:59
While it may be a challenge to get approval, I'm contemplating the idea of opening a support ticket. I believe the default MIME type should be `application/octet-stream` since that's the fallback standard when a file's MIME type can't be determined, as noted in the [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types).

In contrast to the other AWS SDKs, the Java SDK for AWS is unique in that it includes MIME type recognition, automatically identifying and assigning the correct Content-Type for uploaded files, as detailed in the [AWS Java SDK documentation](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/ObjectMetadata.html#getContentType--). It also correctly uses `application/octet-stream` as the default value.

Both GCP and Azure have adopted `application/octet-stream` as the default Content-Type for their object storage services.  Hence, there seems to be a strong case for adjusting the AWS S3 default Content-Type to align it with the standard.

**Comment by RanVaknin** [comment] 2023-11-08 00:03
Hi @garysassano ,

>In contrast to the other AWS SDKs, the Java SDK for AWS is unique in that it includes MIME type recognition, automatically identifying and assigning the correct Content-Type for uploaded files, as detailed in the [AWS Java SDK documentation](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/ObjectMetadata.html#getContentType--). It also correctly uses application/octet-stream as the default value.

The Java SDK's automatic MIME type setting is helpful when you're uploading files directly through the SDK. It guesses the Content-Type based on the provided body, or uses a default if it can't guess. This is not applicable to presigned URLs because they are generated on the backend. This behavior is not unique to the Java SDK, its the same with the JS SDK when you're using a putObject directly from the SDK:

```js
const client = new S3Client({
    region:"us-east-1"
});

  client.middlewareStack.add(next => args => {
      console.log('before sign: ' , args.request);
      return next(args);
  }, {step: 'build'})


try {
    const response = await client.send(new PutObjectCommand({
        Bucket: "foo-bucket",
        Key:"my-key",
        Body: Buffer.from("some string")
    }))
    console.log(response)
} catch (error) {
    console.log(error)
}

/*
before sign:  HttpRequest {
  method: 'PUT',
  hostname: 'foo-bucket.s3.us-east-1.amazonaws.com',
  port: undefined,
  query: { 'x-id': 'PutObject' },
  headers: {
    'content-type': 'application/octet-stream',     <---- automatically assigned the correct MIME
    'content-length': '11',
    Expect: '100-continue'
  },
  body: <Buffer 73 6f 6d 65 20 73 74 72 69 6e 67>,
  protocol: 'https:',
  path: '/my-key',
  username: undefined,
  password: undefined,
  fragment: undefined
}
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'REDACTED',
    extendedRequestId: 'REDACTED',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  ETag: '"REDACTED"',
  ServerSideEncryption: 'AES256',
  VersionId: 'REDACTED'
}
*/
```

>While it may be a challenge to get approval, I'm contemplating the idea of opening a support ticket.

My guess is that there would be some backwards compatibility considerations. Customers that might be relying on the binary/octet-stream to be returned might encounter some unexpected behavior. This is something that the S3 team will need to examine. 

Good luck,
Ran~

**Comment by garysassano** [comment] 2023-11-08 00:42
> This behavior is not unique to the Java SDK, its the same with the JS SDK when you're using a putObject directly from the SDK.

Unfortunately, that's not the case. Based on my experience, I had to mimic the behavior of the SDK for Java's `putObject` method because the SDK for Javascript v3 would always use `application/octet-stream` for any file. To achieve this, I used the [mime](https://www.npmjs.com/package/mime) npm module, which infers the Content-Type of a file from its extension. This mirrors the Java SDK's functionality, which also derives the Content-Type from the file extension of the file and not from its binary content. There is a also a npm module called [file-type](https://www.npmjs.com/package/file-type) capable of determining binary content types, but it's ineffective with text-based formats.

However, this strays from my initial inquiry. My main concern is generating a PUT-signed URL with the correct default Content-Type, not debating the capabilities of the SDK for JavaScript v3 regarding Content-Type inference during file uploads.
