### ISSUE TITLE
Make API Commands In Docs Collapsible

### ISSUE THREAD

**Issue by rachel-wright** [aws/aws-sdk-js-v3#5210] opened 2023-09-13 19:34 UTC
### Describe the issue

There's no way to see a consolidated list of commands, methods, types, etc. - it just requires endless scrolling. Add a page menu or make sections collapsible, or something, because this new layout is NOT user-friendly

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/

**Comment by ajredniwja** [comment] 2023-09-18 16:44
Hey @rachel-wright thanks for opening this and thank you for your feedback, I can understand how it can be frustrating, I try to just use the search bar to get to the required command. It creates a long page to scroll because of the descriptions not being collapsable. I will mark this to be reviewed by the team to discuss if any changes can be made to change the layout. 
Thaks

**Comment by ajredniwja** [comment] 2023-09-21 21:26
Duplicate of https://github.com/aws/aws-sdk-js-v3/issues/5016

**Comment by ajredniwja** [comment] 2023-09-21 21:26
Will be tracked with https://github.com/aws/aws-sdk-js-v3/issues/5016

**Closed** 2023-09-21 21:27 UTC
Labels: feature-request, documentation, p3, m, queued
