### ISSUE TITLE
TransactionCanceledException doc says CancellationReasons will be missing when it's not

### ISSUE THREAD

**Issue by dibell** [aws/aws-sdk-js-v3#3635] opened 2022-05-25 10:42 UTC
### Describe the issue

The documentation for [TransactionCanceledException](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/modules/transactioncanceledexception.html) states:

"If using Java, DynamoDB lists the cancellation reasons on the CancellationReasons property. This property is not set for other      languages"

I don't believe this is the case for JavaScript and .NET at least (I have tested the JavaScript SDK v3  response and seen a resolved [issue](https://github.com/aws/aws-sdk-net/issues/1292) for .NET) but can't vouch for any other languages at this point.

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/modules/transactioncanceledexception.html

**Comment by yenfryherrerafeliz** [comment] 2022-05-25 22:47
Hi @dibell, thank you for bringing this to our attention. I can confirm that for the JavaScript SDK v3 the cancellation reasons are present when a transaction exception is generated from the DynamoDB Client. I plan to contact the corresponding team, so they can review that documentation.

**Comment by yenfryherrerafeliz** [comment] 2022-08-22 16:22
Hi @dibell, thanks again for bringing this to our attention. I have forwarded this issue to the correspondent team, and they have added it to their backlog, however, since we do not have an ETA for when this will be fixed I will close this issue in the meantime.

Thanks!

**Closed by yenfryherrerafeliz** 2022-08-22 16:22 UTC
Labels: investigating, documentation
