### ISSUE TITLE
TypeError "Cannot read property 'code' of undefined" when sending publish command for SNS in Promise.all()

### ISSUE THREAD

**Issue by ashshort** [aws/aws-sdk-js-v3#4416] opened 2023-02-08 09:48 UTC
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

We have a lambda function receiving events from a DynamoDb stream which it transforms to a business event before publishing to an SNS topic. This is happening inside a Promise.all() as the function is processing batches of events in the order of 200 per invocation. 

The integration with SNS is fairly simple. 

```js
import { SNSClient, PublishCommand } from '@aws-sdk/client-sns';

const snsClient = new SNSClient({ region: process.env.REGION });

const publish = async (some-event) => {
  const publishParams = {
    Subject: 'some-subject',
    Message: JSON.stringify(some-event),
    TopicArn: some-topic,
    MessageAttributes: {
     ... some attributes
    }
  };
  return snsClient.send(new PublishCommand(publishParams))
    .catch((error) => {
      // log some data for cloudwatch based log based metrics
      throw error;
    });
}; 
```

Periodically an exception is thrown which doesn't appear to be coming from anywhere inside our implementation. 

```console
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'code' of undefined",
    "$metadata": {
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "stack": [
        "TypeError: Cannot read property 'code' of undefined",
        "    at throwDefaultError (/var/task/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:9:26)",
        "    at deserializeAws_queryPublishCommandError (/var/task/node_modules/@aws-sdk/client-sns/dist-cjs/protocols/Aws_query.js:1852:51)",
        "    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
        "    at async /var/task/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24",
        "    at async /var/task/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20",
        "    at async /var/task/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46",
        "    at async /var/task/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22",
        "    at async Promise.all (index 0)"
    ]
}
```

The call to SNS is happening inside a Promise.all() which is being used to parallelise the publishing of events being received in the batch from the db stream.

### SDK version number

@aws-sdk/client-sns@3.264.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

nodejs14x

### Reproduction Steps

I have been unable to reproduce the error locally as it is appears to be very intermittent. 

### Observed Behavior

```console
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'code' of undefined",
    "$metadata": {
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "stack": [
        "TypeError: Cannot read property 'code' of undefined",
        "    at throwDefaultError (/var/task/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:9:26)",
        "    at deserializeAws_queryPublishCommandError (/var/task/node_modules/@aws-sdk/client-sns/dist-cjs/protocols/Aws_query.js:1852:51)",
        "    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
        "    at async /var/task/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24",
        "    at async /var/task/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20",
        "    at async /var/task/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46",
        "    at async /var/task/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22",
        "    at async Promise.all (index 0)"
    ]
}
```

### Expected Behavior

if the SDK is going to throw an exception it should be a service exception. This appears to be an error as a result of some kind of object destructuring happening on an undefined object. 

### Additional Information/Context

The function is very busy, approximately 150-200k invocations per hour during day light hours.

**Comment by yenfryherrerafeliz** [comment] 2023-02-10 06:56
Hi @ashshort, thanks for opening this issue. I was not able to reproduce this issue either but, I think I found the scenario that may cause the error. By following the stack trace that you have provided, we see that the origin of the error is [here](https://github.com/aws/aws-sdk-js-v3/blob/8fdd7a510875e7ca77d025ef5a9e5d9ab9ac38dd/packages/smithy-client/src/default-error-handler.ts#L15), where the property "code" is tried to be read from the parameter "parsedBody", but in that specific situation where the error occurs the parameter parsedBody does not have a code property and therefore a TypeError exception is thrown. 
Please see below:
[Here](https://github.com/aws/aws-sdk-js-v3/blob/8fdd7a510875e7ca77d025ef5a9e5d9ab9ac38dd/clients/client-sns/src/protocols/Aws_query.ts#L2433) is where the throwDefaultError function is called:
```js
throwDefaultError({
        output,
        parsedBody: parsedBody.Error,
        exceptionCtor: __BaseException,
        errorCode,
      });
```
And [here](https://github.com/aws/aws-sdk-js-v3/blob/8fdd7a510875e7ca77d025ef5a9e5d9ab9ac38dd/packages/smithy-client/src/default-error-handler.ts#L15) is where the problem occurs, specifically at "parsedBody.code":
```js
 const response = new exceptionCtor({
    name: parsedBody.code || parsedBody.Code || errorCode || statusCode || "UnknownError",
    $fault: "client",
    $metadata,
  });
```

I think a fix for this would be to add an optional chaining operator (?.). For example:

```js
const response = new exceptionCtor({
    name: parsedBody?.code || parsedBody?.Code || errorCode || statusCode || "UnknownError",
    $fault: "client",
    $metadata,
  });
```

I will mark this issue to review so we can address this further.

Thanks!

**Comment by ashshort** [comment] 2023-02-10 09:10
Hi @yenfryherrerafeliz thanks for the update it makes perfect sense!

**Comment by ashshort** [comment] 2023-03-07 11:52
Hi @yenfryherrerafeliz, just looking in our backlog and this error came up on one of the tickets. Any updates? :)

**Comment by yenfryherrerafeliz** [comment] 2023-03-23 21:53
Hi @ashshort, thanks for following up. This should be fixed now. You can confirm it [here](https://github.com/aws/aws-sdk-js-v3/blob/692fb8a445034ce77015e8bac353b1d18ea7abf3/packages/smithy-client/src/default-error-handler.ts#L15).

I am closing this as completed now, but please feel free to reach out with any questions or comments.

Thanks!

**Closed by yenfryherrerafeliz** 2023-03-23 21:53 UTC
Labels: bug, needs-review, p2
