### ISSUE TITLE
getSignedUrl is not working with Typescript Version 4.9.5

### ISSUE THREAD

**Issue by pranavv4615** [aws/aws-sdk-js-v3#4451] opened 2023-02-21 13:53 UTC
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Getting error as Argument of type 'S3Client' is not assignable to parameter of type 'Client<any, ServiceInputTypes, MetadataBearer, any> while using getSignedUrl() function in typescript@4.9.5

### SDK version number

@aws-sdk/@aws-sdk/s3-request-presigner@3.266.0, typescript@4.9.5

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node v14.17.3

### Reproduction Steps
```js
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { GetObjectCommand, GetObjectRequest } from "@aws-sdk/client-s3";

export const getsignedUrl = async (params: GetObjectRequest) => {
    try {
        const command = new GetObjectCommand(params)
        const signedUrl = await getSignedUrl(**_

> s3Client(getting error here)

_**, command, { expiresIn: 15 * 60 });
        return signedUrl
    } catch (err: any) {
        console.log('Error Genrating Signed URL: ', err);
        throw new Error(err?.message || 'Error Generating Signed URL')
    }
}
```
### Observed Behavior
```console
Argument of type 'S3Client' is not assignable to parameter of type 'Client<any, ServiceInputTypes, MetadataBearer, any>'.
  The types of 'middlewareStack.concat' are incompatible between these types.
    Type '<InputType extends ServiceInputTypes, OutputType extends ServiceOutputTypes>(from: MiddlewareStack<InputType, OutputType>) => MiddlewareStack<...>' is not assignable to type '<InputType extends ServiceInputTypes, OutputType extends MetadataBearer>(from: MiddlewareStack<InputType, OutputType>) => MiddlewareStack<InputType, OutputType>'.
      Types of parameters 'from' and 'from' are incompatible.
        Type 'MiddlewareStack<InputType, OutputType>' is not assignable to type 'MiddlewareStack<InputType, ServiceOutputTypes>'.
          Types of property 'addRelativeTo' are incompatible.
            Type '(middleware: MiddlewareType<InputType, OutputType>, options: RelativeMiddlewareOptions) => void' is not assignable to type '(middleware: MiddlewareType<InputType, ServiceOutputTypes>, options: RelativeMiddlewareOptions) => void'.
              Types of parameters 'middleware' and 'middleware' are incompatible.
                Type 'MiddlewareType<InputType, ServiceOutputTypes>' is not assignable to type 'MiddlewareType<InputType, OutputType>'.
                  Type 'InitializeMiddleware<InputType, ServiceOutputTypes>' is not assignable to type 'MiddlewareType<InputType, OutputType>'.
                    Type 'InitializeMiddleware<InputType, ServiceOutputTypes>' is not assignable to type 'InitializeMiddleware<InputType, OutputType>'.
                      Call signature return types 'InitializeHandler<InputType, ServiceOutputTypes>' and 'InitializeHandler<InputType, OutputType>' are incompatible.
                        Type 'Promise<InitializeHandlerOutput<ServiceOutputTypes>>' is not assignable to type 'Promise<InitializeHandlerOutput<OutputType>>'.
                          Type 'InitializeHandlerOutput<ServiceOutputTypes>' is not assignable to type 'InitializeHandlerOutput<OutputType>'.
                            Types of property 'output' are incompatible.
                              Type 'ServiceOutputTypes' is not assignable to type 'OutputType'.
                                'ServiceOutputTypes' is assignable to the constraint of type 'OutputType', but 'OutputType' could be instantiated with a different subtype of constraint 'MetadataBearer'.
                                  Type 'AbortMultipartUploadCommandOutput' is not assignable to type 'OutputType'.
                                    'AbortMultipartUploadCommandOutput' is assignable to the constraint of type 'OutputType', but 'OutputType' could be instantiated with a different subtype of constraint 'MetadataBearer'.ts(2345)
```

### Expected Behavior

getSignedUrl() function should work properly

**Comment by yenfryherrerafeliz** [comment] 2023-02-21 16:30
Hi @pranavv4615, thanks for opening this issue. I don`t see you in your code how and where you create an instance of the S3Client?. I do not even see you importing the S3Client. for example, here is a working sample based on your code:

```js
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { GetObjectCommand, GetObjectRequest, S3Client} from "@aws-sdk/client-s3";

export const getsignedUrl = async (params: GetObjectRequest) => {
    try {
        const command = new GetObjectCommand(params)
        const client = new S3Client({
            region: process.env.TEST_REGION
        })
        const signedUrl = await getSignedUrl(client, command, { expiresIn: 15 * 60 });
        return signedUrl
    } catch (err: any) {
        console.log('Error Genrating Signed URL: ', err);
        throw new Error(err?.message || 'Error Generating Signed URL')
    }
}

```

Thanks!

**Comment by pranavv4615** [comment] 2023-02-22 04:04
<img width="751" alt="Screenshot 2023-02-21 at 10 06 55 PM" src="https://user-images.githubusercontent.com/98373439/220518927-f2d267ab-bec4-4440-ae2f-e95780855397.png">

**Comment by seamus-velocity** [comment] 2023-02-22 05:02
I too am getting the same error.

```
    "@aws-sdk/client-s3": "^3.267.0",
    "@aws-sdk/s3-request-presigner": "^3.276.0",
```

```
yarn tsc -v
Version 4.9.5
```

```typescript
  const client = new S3Client({
    region: S3_REGION,
  });
  const command = new CreateMultipartUploadCommand({
    Bucket: S3_BUCKET,
    Key: key,
    Expires: expires,
  });
  const url = await getSignedUrl(client, command, { expiresIn: EXPIRE_URL_SECONDS });
```
error TS2345: Argument of type 'S3Client' is not assignable to parameter of type 'Client<any, ServiceInputTypes, MetadataBearer, any>'.
  The types of 'middlewareStack.concat' are incompatible between these types.
    Type '<InputType extends ServiceInputTypes, OutputType extends ServiceOutputTypes>(from: MiddlewareStack<InputType, OutputType>) => MiddlewareStack<...>' is not assignable to type '<InputType extends ServiceInputTypes, OutputType extends MetadataBearer>(from: MiddlewareStack<InputType, OutputType>) => MiddlewareStack<InputType, OutputType>'.
      Types of parameters 'from' and 'from' are incompatible.
        Type 'MiddlewareStack<InputType, OutputType>' is not assignable to type 'MiddlewareStack<InputType, ServiceOutputTypes>'.
          Types of property 'addRelativeTo' are incompatible.
            Type '(middleware: MiddlewareType<InputType, OutputType>, options: RelativeMiddlewareOptions) => void' is not assignable to type '(middleware: MiddlewareType<InputType, ServiceOutputTypes>, options: RelativeMiddlewareOptions) => void'.
              Types of parameters 'middleware' and 'middleware' are incompatible.
                Type 'MiddlewareType<InputType, ServiceOutputTypes>' is not assignable to type 'MiddlewareType<InputType, OutputType>'.
                  Type 'InitializeMiddleware<InputType, ServiceOutputTypes>' is not assignable to type 'MiddlewareType<InputType, OutputType>'.
                    Type 'InitializeMiddleware<InputType, ServiceOutputTypes>' is not assignable to type 'InitializeMiddleware<InputType, OutputType>'.
                      Call signature return types 'InitializeHandler<InputType, ServiceOutputTypes>' and 'InitializeHandler<InputType, OutputType>' are incompatible.
                        Type 'Promise<InitializeHandlerOutput<ServiceOutputTypes>>' is not assignable to type 'Promise<InitializeHandlerOutput<OutputType>>'.
                          Type 'InitializeHandlerOutput<ServiceOutputTypes>' is not assignable to type 'InitializeHandlerOutput<OutputType>'.
                            Types of property 'output' are incompatible.
                              Type 'ServiceOutputTypes' is not assignable to type 'OutputType'.
                                'ServiceOutputTypes' is assignable to the constraint of type 'OutputType', but 'OutputType' could be instantiated with a different subtype of constraint 'MetadataBearer'.
                                  Type 'AbortMultipartUploadCommandOutput' is not assignable to type 'OutputType'.
                                    'AbortMultipartUploadCommandOutput' is assignable to the constraint of type 'OutputType', but 'OutputType' could be instantiated with a different subtype of constraint 'MetadataBearer'.
```

```

**Comment by yenfryherrerafeliz** [comment] 2023-02-23 18:19
Hi @pranavv4615, @seamus-velocity, I suspect that the problem is due to using different versions in "@aws-sdk/client-s3" and "@aws-sdk/s3-request-presigner". Could you please make sure your sdk dependencies are in the same version?. Actually, I did a test in my local environment using two different versions of those packages and I got the same error. You probably should check your package-lock.json or yarn.lock file since the dependencies should be pinned there. You could also try with an empty project and installing the dependencies from scratch and see if the issue persists.

Thanks!

**Comment by seamus-velocity** [comment] 2023-02-24 01:42
That fixed it. I missed that `@aws-sdk/s3-request-presigner` was a different version at `3.276.0`, whereas the others were `3.267.0`.

```
    "@aws-sdk/client-s3": "3.267.0",
    "@aws-sdk/s3-presigned-post": "3.267.0",
    "@aws-sdk/s3-request-presigner": "3.267.0",
```

**Comment by yenfryherrerafeliz** [comment] 2023-02-26 00:01
@pranavv4615 I am going to close this issue since it should be resolved by using the same SDK packages version. However, please reopen this issue if you keep getting the same error.

Thanks!

**Closed by yenfryherrerafeliz** 2023-02-26 00:01 UTC
Labels: guidance, p3

**Comment by pranavv4615** [comment] 2023-02-26 06:01
"@aws-sdk/client-s3": "^3.267.0",
"@aws-sdk/s3-request-presigner": "^3.267.0"

with these versions still i am getting the same error

**Comment by subzero79** [comment] 2023-02-28 03:37
Happens the same to me. The strange thing is not popping the error in VSCode but spitting in my project build at vercel. The error does not complain about the client though but the command

```bash
info  - Linting and checking validity of types...
--
13:29:35.252 | Failed to compile.
13:29:35.252 |  
13:29:35.253 | ./lib/api/trpc/resolvers/file.getFile.ts:18:49
13:29:35.253 | Type error: Argument of type 'GetObjectCommand' is not assignable to parameter of type 'Command<GetObjectCommandInput, GetObjectCommandOutput, any, ServiceInputTypes, MetadataBearer>'.
13:29:35.253 | Types of property 'resolveMiddleware' are incompatible.
13:29:35.253 | Type '(clientStack: MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>, configuration: S3ClientResolvedConfig, options?: HttpHandlerOptions \| undefined) => Handler<...>' is not assignable to type '(stack: MiddlewareStack<ServiceInputTypes, MetadataBearer>, configuration: any, options: any) => Handler<GetObjectCommandInput, GetObjectCommandOutput>'.
13:29:35.253 | Types of parameters 'clientStack' and 'stack' are incompatible.
13:29:35.253 | Type 'MiddlewareStack<ServiceInputTypes, MetadataBearer>' is not assignable to type 'MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>'.
13:29:35.253 |  
13:29:35.254 | 16 \| 		Key: input.key as string,
13:29:35.254 | 17 \| 	});
13:29:35.254 | > 18 \| 	const signedUrl = await getSignedUrl(s3Client, command, { expiresIn: 120 });
13:29:35.254 | \| 	                                               ^
13:29:35.254 | 19 \| 	if (signedUrl) return { signedUrl };
13:29:35.254 | 20 \| 	throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "There was a problem obtaining the document URL" });
13:29:35.254 | 21 \| };
13:29:35.349 | error Command failed with exit code 1.
13:29:35.350 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
13:29:35.370 | Error: Command "yarn run build" exited with 1
```

The code for getting the presign url is 

```js
import { z } from 'zod';

import { s3Client } from '@/lib/s3-client';
import { GetObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { TRPCError } from '@trpc/server';

import { ITRpcContext } from '../createRouter';
import { FileGetFileUrlSchema } from '../schemas/file.schema';

export const getFile = async (input: z.infer<typeof FileGetFileUrlSchema>, ctx: ITRpcContext, cookieName: string) => {
	if (input.order_id !== ctx.req.cookies[cookieName])
		throw new TRPCError({ code: "NOT_FOUND", message: "The requested order is invalid for this link" });
	const command = new GetObjectCommand({
		Bucket: process.env.S3_TRANS_BUCKET_NAME as string,
		Key: input.key as string,
	});
	const signedUrl = await getSignedUrl(s3Client, command, { expiresIn: 120 });
	if (signedUrl) return { signedUrl };
	throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "There was a problem obtaining the document URL" });
};
```

**Comment by yenfryherrerafeliz** [comment] 2023-02-28 04:57
@pranavv4615, @subzero79 could you please do the following to discard that the problem is due to the version of the packages being on different versions, because, sometimes dependencies are pinned by the lock file. So, what you can do are two things:
- The first one to check the package versions by doing the following:
    - ``` npm list @aws-sdk/client-s3 ```
    -``` npm list @aws-sdk/s3-request-presigner ```
- The last thing is to create an empty project, install those dependencies and check if the issue persist there.

Thanks!

**Comment by subzero79** [comment] 2023-02-28 05:05
Here it is. I've aligned versions for all v3 modules which are ssm, ses, presign and s3 but that did not change. 
I finally opted termporarly to add  //@ts-ignore directive above the sign request

```bash
npm list @aws-sdk/client-s3
├── @aws-sdk/client-s3@3.279.0
└─┬ aws-amplify@4.3.46
  └─┬ @aws-amplify/storage@4.5.17
    └── @aws-sdk/client-s3@3.6.1
```

```bash
npm list @aws-sdk/s3-request-presigner
├── @aws-sdk/s3-request-presigner@3.279.0
└─┬ aws-amplify@4.3.46
  └─┬ @aws-amplify/storage@4.5.17
    └── @aws-sdk/s3-request-presigner@3.6.1
```

**Comment by sp88011** [comment] 2023-03-14 03:45
Same here. I'm on version 3.289.0 for what it's worth...

```
 "@aws-sdk/client-s3": "^3.289.0",
    "@aws-sdk/s3-presigned-post": "^3.289.0",
    "@aws-sdk/s3-request-presigner": "^3.289.0",
```
