### ISSUE TITLE
DynamoDBClient logger output contains 'undefined' for output values (Item, ConsumedCapacity...)

### ISSUE THREAD

**Issue by dmeehan1968** [aws/aws-sdk-js-v3#5149] opened 2023-08-28 18:02 UTC
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When DynamoDB constructor is provided a 'logger' option, the logged output seems to lack properties for the items returned.

Note that I am using DynamoDB client (although also tested DynamoDBClient with same result), from the AWS SDK installed in the Nodev18 runtime.

The following output is when `console` is supplied, eg:

```
DynamoDBDocument.from(new DynamoDbClient({ logger: console }))
```

Note that in the 'output' property, all property values are undefined, both the ConsumedCapacity and the item properties.

```
2023-08-28T17:39:22.241Z	9b1c9978-3e44-47c5-8052-fb8586a76511	INFO	{
  clientName: 'DynamoDBClient',
  commandName: 'GetItemCommand',
  input: {
    TableName: 'Compliance-3dc14f14',
    Key: { PK: [Object], SK: [Object] }
  },
  output: {
    ConsumedCapacity: undefined,
    Item: {
      S2: undefined,
      lastUpdated: undefined,
      lastNonCompliance: undefined,
      SK: undefined,
      PK: undefined,
      S1: undefined
    }
  },
  metadata: {
    httpStatusCode: 200,
    requestId: 'TL9V1BCMM31O0T6970JQ4PTFJVVV4KQNSO5AEMVJF66Q9ASUAAJG',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```

I discovered this whilst using the AWS Lambda Powertools logger, which produces empty object values (as it uses JSON.stringify which drops properties with undefined), I tested with Node console as that does the same (albeit as above showing that the keys exist but with undefined values).

This seems to only affect the DynamoDB & DynamoDBClients client, as I am using other AWS clients also with logging and those produce expected output.

Note also that values in the 'input' property do appear as expected (not visible in the above due to node console default behaviour).

### SDK version number

@aws-sdk/clientdynamodb@3.104.0 (NodeV18 default)

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

NodeV18

### Reproduction Steps

Pass a logger instance (such as `console`) to the client constructor, perform a GetItem, Query etc operation, and observe the logged output.

### Observed Behavior

Property values in the 'output' property (including meta such as ConsumedCapacity) are 'undefined'.

### Expected Behavior

Property values should reflect the returned items and consumed capacity metrics.

**Comment by RanVaknin** [comment] 2023-08-30 16:46
Hi @dmeehan1968 ,

>Pass a logger instance (such as console) to the client constructor, perform a GetItem, Query etc operation, and observe the logged output.

Im not able to reproduce the reported behavior. 

```js
import { DynamoDB } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocument } from "@aws-sdk/lib-dynamodb";

const dynamoBaseClient = new DynamoDB({
    region: "us-east-1",
    logger: console
})

const ddoc = DynamoDBDocument.from(dynamoBaseClient)

try {
    const res = await ddoc.get({
        TableName: "paginationTable",
        Key: {
        myID: "ID3226",
        },
    });
} catch (error) {
    console.log(error)
}
```

Output:
```js
  output: {
    '$metadata': {
      httpStatusCode: 200,
      requestId: 'REDACTED',
      extendedRequestId: undefined,
      cfId: undefined,
      attempts: 1,
      totalRetryDelay: 0
    },
    ConsumedCapacity: { CapacityUnits: 0.5, TableName: 'paginationTable' },
    Item: {
      column3: [Object],
      column4: [Object],
      column5: [Object],
      column6: [Object],
      column1: [Object],
      data: [Object],
      column2: [Object],
      myID: [Object]
    }
  },
  metadata: {
    httpStatusCode: 200,
    requestId: 'REDACTED',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```

Can you please share your entire code snippet? In the future when you open bug reports please fill the intake form its entirety by providing a complete code snippet that can reproduce your issue.

Many thanks,
Ran~

**Comment by dmeehan1968** [comment] 2023-08-31 10:56
@RanVaknin Thanks for the reply and apologies for the incomplete example.

What you've shown is running at the command line, and I failed to add that the described behaviour was observed in the CloudWatch console.  There seems to be a difference in behaviour between logs produced by the client itself, and those produced after the client call has completed.

Note also that this is output captured from a Node 18 Lambda via the Cloudwatch console.

The following code is exposed as a Lambda function url, and invoked by entering the URL in the browser, or using the AWS Lambda consoles 'test' functionality, the event payload is irrelevant.

Here is my example:

```
import { DynamoDB } from "@aws-sdk/client-dynamodb"
import { DynamoDBDocument, GetCommandInput } from "@aws-sdk/lib-dynamodb"

const client = new DynamoDB( { logger: console })

export const handler = async () => {

    const documentClient = DynamoDBDocument.from(client)

    const input: GetCommandInput = {
        TableName: 'DevWavetrendStoreTrackerDevice-3fdc5520',
        Key: {
            PK: 'DEVICE#',
            SK: 'DEVICE#524724',
        },
        ReturnConsumedCapacity: 'TOTAL',
    }

    try {
        const output = await documentClient.get(input)
        console.log(output)

        return {
            statusCode: 200,
            body: JSON.stringify(output, null, 2)
        }
    } catch(error: any) {
        console.log(error)
        return {
            statusCode: 500,
            body: JSON.stringify({ message: error.message ?? 'Unknown error' }, null, 2)
        }
    }
}
```

The output captured by the using the lambda console 'test' functionality is as follows:

```
START RequestId: b31cdc6c-31ab-477f-81c7-f7ac68467588 Version: $LATEST
2023-08-31T10:48:04.478Z	b31cdc6c-31ab-477f-81c7-f7ac68467588	INFO	{
  clientName: 'DynamoDBClient',
  commandName: 'GetItemCommand',
  input: {
    TableName: '<REDACTED>',
    Key: { PK: [Object], SK: [Object] },
    ReturnConsumedCapacity: 'TOTAL'
  },
  output: {
    ConsumedCapacity: {
      CapacityUnits: 0.5,
      GlobalSecondaryIndexes: undefined,
      LocalSecondaryIndexes: undefined,
      ReadCapacityUnits: undefined,
      Table: undefined,
      TableName: '<REDACTED>',
      WriteCapacityUnits: undefined
    },
    Item: {
      lastUpdated: undefined,
      longitude: undefined,
      status: undefined,
      SK: undefined,
      PK: undefined,
      recoveryRequired: undefined,
      latitude: undefined,
      tags: undefined,
      accuracy: undefined
    }
  },
  metadata: {
    httpStatusCode: 200,
    requestId: '<REDACTED>',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
2023-08-31T10:48:04.481Z	b31cdc6c-31ab-477f-81c7-f7ac68467588	INFO	{
  '$metadata': {
    httpStatusCode: 200,
    requestId: '<REDACTED>',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  ConsumedCapacity: {
    CapacityUnits: 0.5,
    GlobalSecondaryIndexes: undefined,
    LocalSecondaryIndexes: undefined,
    ReadCapacityUnits: undefined,
    Table: undefined,
    TableName: '<REDACTED>',
    WriteCapacityUnits: undefined
  },
  Item: {
    lastUpdated: '2023-08-31T10:43:13.000Z',
    longitude: <REDACTED>,
    status: {
      inTrip: false,
      batteryCondition: true,
      batteryCritical: false,
      gsmConnected: false,
      recoveryMode: false,
      noMovement: false
    },
    SK: 'DEVICE#<REDACTED>',
    PK: 'DEVICE#',
    recoveryRequired: false,
    latitude: <REDACTED>,
    tags: Set(2) { '<REDACTED>', '<REDACTED>' },
    accuracy: 24.7
  }
}
END RequestId: b31cdc6c-31ab-477f-81c7-f7ac68467588
REPORT RequestId: b31cdc6c-31ab-477f-81c7-f7ac68467588	Duration: 132.73 ms	Billed Duration: 133 ms	Memory Size: 512 MB	Max Memory Used: 95 MB	Init Duration: 418.79 ms	
```

The first log entry is the output from the DynamoDB clients use of the logger, and shows the input/output of the command.  

The second log entry is a `console.log` of the returned output, and should be equivalent to the DynamoDB clients use of the provided logger, e.g. `console.log({ input, output, ... })`.  

I opted to redact the logs as they expose confidential information, but the values replaced were real values I expected to see for those properties.

This shows a distinct difference in log behaviour between a logger provided to the client, and a logger used after the return from the client method.  It means that in order to log DynamoDB transactions we must add additional logging instead of relying on the client logger.  In my usage of multiple clients, its only DynamoDB that seems to be affected in this way.

**Comment by dmeehan1968** [comment] 2023-08-31 12:07
I was mistaken about the client version, 3.188.0 is actually the default AWS SDK version (and therefore DynamoDB client version) in effect in the Node v18 runtime.

Note that the NodeJsFunction construct (from AWS CDK) automatically excludes locally installed @aws-sdk dependencies because they are installed in the runtime.

I tried downgrading my local copy to 3.188.0 to match the runtime, and the local invocation also shows the values as undefined.  Therefore, it seems that a bug was fixed since 3.188.0.  Interestingly I did try v3.104 and that didn't show the problem, so it appears it was a regression which encompassed 3.188.0.  When I was searching for issues I didn't find anything relevant, so perhaps it wasn't documented.

I'm going to work on installing my own AWS SDK version in the runtime to work around the deficiency in the v18 runtime's version.

**Comment by RanVaknin** [comment] 2023-08-31 16:27
Hi @dmeehan1968 ,

Thanks for providing more info. I'm not sure why the embedded version has that deficiency, and nothing comes to mind that will point to the issue. 

Please let me know how your effort in upgrading the SDK version on lambda goes. 

Thanks,
Ran~

**Comment by dmeehan1968** [comment] 2023-08-31 18:58
@RanVaknin 

I use AWS CDK NodejsFunction to create the lambda.  There are a couple of approaches:

1. override the `bundling.`externalModules` property which by default skips bundling of the SDK in favour of the one preinstalled in the runtime. This causes esbuild to include the SDK modules source into the bundled assets, but does lead to bloated assets due to duplication
2. override the `bundling.nodeModules` property which allows you to specify which modules to install in the runtime, and it then gets the version information from the local package.json as to which version to install.  This used in preference to the pre-installed version for each specified package, and allows for a mix of different client versions.
3. Create a lambda layer that bundles the specific SDK versions required, and include that in the `props.layers` property.  There is [documentation](https://docs.aws.amazon.com/lambda/latest/operatorguide/sdks-functions.html) that suggests this is indeed the recommended approach.  I'll look into that as I build out my application.

I tested option 2 and it works fine for my immediate use, giving the expected result of logging the full Item details.

I think this could all be better documented, its very easy to overlook the pre-installed SDK and have the CDK defer to that by default, as it makes this sort of problem harder to track down.

As an aside, @awk-sdk/lib-dynamodb which provides the DynamoDBDocument class seems to have a peer dependency on the @aws-sdk/client-dynamodb, but its not locked to a specific version.  That might be by design, but it allowed me to create a deployment with vastly different client/document versions which might be a potential source of problems.

**Comment by RanVaknin** [comment] 2023-09-01 00:31
Hey @dmeehan1968 ,

I appreciate the in depth investigation. The SDK is made available through many different channels. Since you are consuming the SDK via Lambda, then this information of embedded SDK version is included in the [Lambda documentation](https://docs.aws.amazon.com/lambda/latest/dg/lambda-nodejs.html). 

Since this ticket is not very actionable by the SDK team, and you were able to update your Lambda's embedded SDK successfully, I'm inclined to close this issue.

If you wish to offer doc changes for the Lambda team's documentation pages, you can click on the [Feedback](https://docs-feedback.aws.amazon.com/feedback.jsp?hidden_service_name=Lambda&topic_url=https://docs.aws.amazon.com/lambda/latest/dg/lambda-nodejs.html) button at the top right corner of any AWS doc. This ensures that your feedback is going directly to the doc writers of each service team. 

Thanks again!
Ran~

**Closed by RanVaknin** 2023-09-01 00:31 UTC
Labels: bug, p3
