### ISSUE TITLE
Messaging session  for @aws-sdk/client-chime 

### ISSUE THREAD

**Issue by kvntzn** [aws/aws-sdk-js-v3#2337] opened 2021-05-02 07:25 UTC
Does @aws-sdk/client-chime has a [messaging session](https://www.npmjs.com/package/amazon-chime-sdk-js#starting-a-messaging-session) like the [amazon-chime-sdk](https://www.npmjs.com/package/amazon-chime-sdk-js) for js had ?

**Comment by ajredniwja** [comment] 2021-06-10 06:57
Hi @kvntzn, checking the [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-chime/index.html) I was not able to find anything.

I believe that this is not a bug but a feature-request. Unfortunately, this most likely wont be implemented in this SDK as it is already implemented in another one. 

Closing this issue now, please reach out if you have any other questions.

**Closed by ajredniwja** 2021-06-10 06:57 UTC
Labels: feature-request
