### ISSUE TITLE
S3 multi-part upload error

### ISSUE THREAD

**Issue by amhinson** [aws/aws-sdk-js-v3#2000] opened 2021-02-05 00:50 UTC
## Describe the bug
When using the latest version (3.4.1) of `@aws-sdk/client-s3` for multi-part uploads, we are seeing the following error:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
```

This behavior was not happening on with the previous version we were using (1.0.0-rc.4).

#### SDK version number
`@aws-sdk/client-s3@3.4.1`

#### Is the issue in the browser/Node.js/ReactNative?
Browser, although I haven't tried other environments yet.

#### Details of the browser/Node.js/ReactNative version
Browsers:
    Chrome: 88.0.4324.146
    Firefox: 78.6.1
    Safari: 14.0.3

## Steps to reproduce

Usage in `aws-amplify`: https://github.com/aws-amplify/amplify-js/blob/566b569b4256e82aa9ac3f682f33cfe08c8597e2/packages/storage/src/providers/AWSS3ProviderManagedUpload.ts#L137-L145

#### Observed behavior
See error message (above) in network tab.

#### Expected behavior
Successful multi-part upload.

## Additional context
I’ve compared the request headers before and after and here is one notable difference:
- `Content-Type: binary/octet-stream` - this header exists in rc.4 but does not exist in 3.4.1

**Comment by alexforsyth** [comment] 2021-02-17 19:09
Closing, we worked on this offline. Root cause was 
```
requestHandler: new AxiosHttpHandler({}),
```
unrelated to s3 multipart upload

**Closed by alexforsyth** 2021-02-17 19:09 UTC
Labels: bug, needs-triage
