### ISSUE TITLE
MIGRATION ISSUE: Credential chain disregards assumed credentials if AWS_PROFILE is set

### ISSUE THREAD

**Issue by martinjlowm** [aws/aws-sdk-js-v3#6295] opened 2024-07-22 15:05 UTC
### Pre-Migration Checklist

- [X] I've read the [Migration Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html).
- [X] I've reviewed the upgrading notes and major version differences mentioned in [`UPGRADING.md`](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md).
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for similar migration issues.

### Which JavaScript Runtime is this issue in?

Node.js (includes AWS Lambda)

### AWS Lambda Usage

- [ ] Yes, my application is running on AWS Lambda.
- [X] No, my application is not running on AWS Lambda.

### Describe the Migration Issue

The documentation specifically describes the prioritized order of credential providers as:
> If one of the credential providers above fails to resolve the AWS credential, the chain falls back to next provider until a valid credential is resolved, and the chain will throw an error when all of the providers fail.

However, https://github.com/aws/aws-sdk-js-v3/blob/e11de230e80b6df2fa0a8a4d444604e49d6194bf/packages/credential-provider-node/src/defaultProvider.ts#L88-L91, disregards `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` if `AWS_PROFILE` is set. I would still consider this a valid credential in response to the documentation quote.

For tools like [Granted](https://www.granted.dev/) and [AWS SSO CLI](https://github.com/synfinatic/aws-sso-cli) (I presume), it's common to use the `AWS_PROFILE` to obtain assumed credentials, meaning all three environmental variables will be present.

The aforementioned chain logic, skips `fromEnv` completely which is different behavior than how it was in v2. In our team, we use the Rust SDK too and it behaves similarly to the old behavior of v2 as well.

### Observed Differences/Errors

`AWS_PROFILE` is prioritized over `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.

**Comment by kuhe** [comment] 2024-07-23 15:13
duplicate of https://github.com/aws/aws-sdk-js-v3/issues/2549

we are going to make `AWS_ACCESS_KEY_ID` higher priority in a future update.

**Closed by kuhe** 2024-07-23 15:13 UTC
Labels: needs-triage, v2-v3-inconsistency
