### ISSUE TITLE
AWS Transcribe Streaming HTTP2 error message with WebToken

### ISSUE THREAD

**Issue by MartinEmrich** [aws/aws-sdk-js-v3#5958] opened 2024-04-04 09:53 UTC
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

AWS Transcribe Streaming fails with errors like

```
{\"code\":\"ERR_HTTP2_ERROR\",\"errno\":-505,\"$metadata\":{\"attempts\":1,\"totalRetryDelay\":0}}
```

```
Error [ERR_HTTP2_ERROR]: Protocol error\n    at Http2Session.onSessionInternalError (node:internal/http2/core:801:26)
```

### SDK version number

@aws-sdk/client-transcribe-streaming 3.540.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.5.1

### Reproduction Steps

Use Transcribe Streaming from a service within an AWS EKS Kubernetes cluster with an IAM service account.

````
const client = new transcribe.TranscribeStreamingClient();
// ...
const response = await client.send(new transcribe.StartStreamTranscriptionCommand(transcribeParams));
// ...
````

### Observed Behavior

Running the service (in fact the same container image) locally (AWS SSO auth) or on an EC2 instance (IAM instance role) works as expected.

Running it on AWS EKS with an IAM service account (Token file authentication), the STSClient call made by the Transcribe client fails:

````
{"name":"xxx","hostname":"xxxx","pid":7,"level":50,"clientName":"STSClient","commandName":"AssumeRoleWithWebIdentityCommand","input":{"RoleArn":"arn:aws:iam::###########:role/eksctl-xxxx-addon-iamservic-Role1-xxxxxx","RoleSessionName":"aws-sdk-js-session-1712219858427","WebIdentityToken":"***SensitiveInformation***"},"error":{"code":"ERR_HTTP2_ERROR","errno":-505,"$metadata":{"attempts":1,"totalRetryDelay":0}},"metadata":{"attempts":1,"totalRetryDelay":0},"msg":"","time":"2024-04-04T08:37:38.452Z","v":0}
```` 

### Expected Behavior

I expect it to work with IRSA just as with any other AWS API authentication method

### Possible Solution

Inspired by the workaround in #2533, I got it working in a similar way, by explicitly creating the credential provider (in my case, the fromTokenFile provider):

````
const awsCredentialProviders = require('@aws-sdk/credential-providers');
const credentials = awsCredentialProviders.fromTokenFile({ logger, clientConfig: { region: 'eu-central-1' } });
const client = new transcribe.TranscribeStreamingClient({ logger, credentials });
````

### Additional Information/Context

- The OP of #2533 seems to be gone, thus that issue has been closed without ever solving it?
- A vague suspicion: AWS Transcribe Streaming does stream the audio using HTTP/2 streams. Maybe something like a connection pool within the Transcribe SDK is reusing the STSClient connection for Transcribe or vice-versa, somehow distrurbing each other?
- If AWS employees are present: I also opened AWS support cases: 171222095700049 and 171216228000474

**Comment by aBurmeseDev** [comment] 2024-04-05 18:18
Hi @MartinEmrich - thanks for reaching out and sorry to hear about the issue.

While I investigate, I'd like to clarify how you're obtaining credentials on the code example that gave you the error since you mentioned you were able to workaround with `fromTokenFile` credential-provider. Can you share the code that works vs the one that throws the error to give us more insight?

**Comment by MartinEmrich** [comment] 2024-04-08 06:01
@aBurmeseDev See above: I use an IAM Service Account within an EKS Cluster, which effectively is the web token auth. (EKS automatically injects the web token and sets the AWS_WEB_IDENTITY_TOKEN_FILE environment variable. Using any official AWS SDK, this works automatically without any extra code.)

So to reproduce: 
- spin up an EKS cluster with a node group
- Create an IAM service account with appropriate permissions ( "transcribe:StartStreamTranscription")
- Run code with no special preparation (see snippet above) using the streaming transcription service in a pod on that cluster.

**Comment by aBurmeseDev** [comment] 2024-04-24 16:48
@MartinEmrich - thanks for getting back. Sorry if I wasn’t clear on my question but I was looking for your working vs non-working code to get more understanding of the issue. The more detailed information we can get, the faster we can debug and identify the root cause.

Just to provide some background on the error: this protocol error can occur for a number of reasons, generally related to HTTP/2 communication issues. Here are a few that I narrowed down based on the information you provided:

- Service side: we can rule this out as we know Transcribe support HTTP2 streaming.
- Client side: I doubt that the root cause is SDK because you were able to successfully perform the same operation on EC2. However, one thing you may try is to use `@smithy/node-http-handler` [package](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-smithy-node-http-handler/Interface/NodeHttp2HandlerOptions/) and pass in HTTP2 options into client.
```
import { NodeHttp2Handler } from "@aws-sdk/node-http-handler";

const client = new Client({
  requestHandler: new NodeHttp2Handler({
    requestTimeout: 100,
    sessionTimeout: 300,
  }),
});
```
- Load balancing or Proxies: Since you're routing traffic through a load balancer or proxy server, misconfigurations or limitations in handling HTTP/2 might be the culprit, especially when your EC2 workflow is working as expected whereas EKS workflow is throwing error. I would recommend that you verify HTTP2 support is enabled for EKS.
- Lastly, I would check to ensure that there are no other services, AWS or third-party, being used without HTTP2 support.

If issue persists, please share more requested information so that I can further assist you.

Best,
John

**Comment by MartinEmrich** [comment] 2024-05-06 07:23
Hello John! Sorry for the delay, I somehow overlooked your response.

Again, my working vs. non-working code is in the original post, if you are missing a specific information, please be specific.

The issue is not in the Transcribe client or server itself (actually, as I understand, transcribe not only supports, but actually requires HTTP/2 for streaming).  The issue seems to be in the authentication step.

My speculation:
The issue seems to be the SDK trying to use HTTP/2 to talk to the OIDC token endpoint while authenticating. And that happens obviously only if the used authentication method is actually WebToken auth.
That's why it does not happen with any other authentication method (IAM Role, Key/Secret, ...).

Your code example would do the opposite: force the Transcribe client to use the NodeHttp2Handler (which it seems to use already, as the Transcribe streaming works fine)
Instead the issue seems to be the auth code (IAM, OIDC) using HTTP/2 instead of HTTP (my suspicion: it re-uses any HTTP client previously created within the SDK, which happens to be the HTTP2Handler created by the Transcribe client).
That's why the workaround works: It calls the authentication code explicitly before the Transcribe client (and the HTTP2 handler) is created, thus defaulting to the normal HTTP 1 client. Only after authentication happened, the Transcribe client is created and now has valid authentication.

I do not use any proxies or load balancers. There is nothing custom between the code and the AWS API endpoints; it runs in plain AWS EKS cluster with IAM service account in an AWS VPC.

**Comment by jgrigg** [comment] 2024-07-17 10:21
I've also run into this. I'm also running in EKS. Using Pod Identities and role chaining to another account (i.e the expecting the ini provider to kick in). In my case this caused the issue:

```typescript
new S3Client({region: "ap-southease-2"})
new LexRuntimeV2Client({region: "ap-southease-2"}) // BOOM!
```

This workaround fixed it which makes me think @MartinEmrich's hypothesis holds up.

```typescript
import { defaultProvider as credentialDefaultProvider } from '@aws-sdk/credential-provider-node';

const awsCredsProvider = credentialDefaultProvider({
  clientConfig: { region: 'ap-southeast-2' },
});

new S3Client({
  credentials: awsCredsProvider,
  region: "ap-southease-2",
});

new LexRuntimeV2Client({
  credentials: awsCredsProvider,
  region: "ap-southease-2",
}); // HAPPY!
```

**Comment by aBurmeseDev** [comment] 2024-07-22 23:02
Hi @jgrigg - as I'm further looking into this behavior, would you be able to provide a minimal steps to reproduce your workflow? I understand that you're using EKS Pod Identities and switching roles, can you provide your use-case on switching role and share how your cross-account setup looks like?

As previously mentioned, this type of protocol error typically occurs when there's a problem with the communication between client and service. We would need to see the request logs being sent, and you can get them by adding [middleware stack](https://github.com/aws/aws-sdk-js-v3?tab=readme-ov-file#middleware) to your client call.
```js
client.middlewareStack.add(
  (next, context) => async (args) => {
    console.log("AWS SDK context", context.clientName, context.commandName);
    console.log("AWS SDK request input", args.input);
    const result = await next(args);
    console.log("AWS SDK request output:", result.output);
    return result;
  },
  {
    name: "MyMiddleware",
    step: "build",
    override: true,
  }
);
```

Since you also mentioned "expecting the ini provider to kick in", can you share the code with reported behavior and error thrown?

**Comment by jgrigg** [comment] 2024-07-30 04:25
Sorry for the delay @aBurmeseDev . Our setup is using role chaining via the ini/profile/config file. A pod identity association exists for in the cluster (shared by all workloads) and pod containers hav the `AWS_CONFIG_FILE` env var pointing to a mounted file that looks something like this:

```ini
    [default]
    role_arn =arn:aws:iam::<some_other_account_id>:role/automat-owners-slackbot-integration
    credential_source = EcsContainer
```

The idea is that we can decoratively role-chain to a role in an account external to the cluster.

Note that `EcsContainer` is a bit misleading here as it's actually the `fromHttp` provider that's being invoked. I tried to solve this here [here](https://github.com/aws/aws-sdk-js-v3/pull/6322)


Adding the debug logs you asked for didn't give me a whole lot more unfortunately (maybe i stuffed it up) :( 

```
{"level":50,"timestamp":"2024-07-30T04:14:45.068Z","environment":"owners-slackbot-prod","version":"59b9028.1485","name":"owners-slackbot","clientName":"STSClient","commandName":"AssumeRoleCommand","input":{"RoleArn":"arn:aws:iam::843736594031:role/automat-owners-slackbot-integration","RoleSessionName":"aws-sdk-js-1722312885028","DurationSeconds":3600},"error":{"message":"Protocol error","stack":"Error [ERR_HTTP2_ERROR]: Protocol error\n    at Http2Session.onSessionInternalError (node:internal/http2/core:793:26)","name":"Error","code":"ERR_HTTP2_ERROR","errno":-505,"$metadata":{"attempts":1,"totalRetryDelay":0}},"metadata":{"attempts":1,"totalRetryDelay":0}}

{"level":50,"timestamp":"2024-07-30T04:14:45.068Z","environment":"owners-slackbot-prod","version":"59b9028.1485","name":"owners-slackbot","clientName":"LexRuntimeV2Client","commandName":"PutSessionCommand","input":{"botId":"9UKKFYK6VM","botAliasId":"VBNYLMOZ77","localeId":"en_US","sessionId":"09fdcb92-8765-450c-81b0-4cd1c35e892c","sessionState":{}},"error":{"message":"Protocol error","stack":"Error [ERR_HTTP2_ERROR]: Protocol error\n    at Http2Session.onSessionInternalError (node:internal/http2/core:793:26)","name":"Error","code":"ERR_HTTP2_ERROR","errno":-505,"$metadata":{"attempts":1,"totalRetryDelay":0}},"metadata":{"attempts":1,"totalRetryDelay":0}}

{"level":50,"timestamp":"2024-07-30T04:14:45.068Z","environment":"owners-slackbot-prod","version":"59b9028.1485","name":"owners-slackbot","err":{"type":"NghttpError","message":"Protocol error","stack":"Error [ERR_HTTP2_ERROR]: Protocol error\n    at Http2Session.onSessionInternalError (node:internal/http2/core:793:26)","code":"ERR_HTTP2_ERROR","errno":-505,"$metadata":{"attempts":1,"totalRetryDelay":0}},"msg":"Error in ownersHandler"}
```

Let me know if there's anything else i can help you with. Happy to jump on a call to pair if that's easier. Thank you!

**Comment by kuhe** [comment] 2024-08-14 20:52
note to maintainers:

```js
try seeing if inner client is given the outer client's requestHandler:

new TranscibeStreaming({
  credentials: credentialDefaultProvider({
    requestHandler: NodeHttpHandler.create() || NodeHttp2Handler.create() // try setting or unsetting this
  })
});
```

**Comment by kuhe** [comment] 2024-08-15 16:56
The bug is due to the parent or outer client (e.g. TranscribeStreaming with its http2 `requestHandler`) passing its config to the default credential provider. 

The default credential provider is a chain that may include client requests using SSO-OIDC or STS. It is incorrect for the SDK to pass an HTTP2 requestHandler in these cases. 

We will release a fix for this in a future version. As a workaround, use a separated credentialProvider as in the above example, which I'll copy here:

```ts
import { defaultProvider as credentialDefaultProvider } from '@aws-sdk/credential-provider-node';

const awsCredsProvider = credentialDefaultProvider({
  clientConfig: { region: 'ap-southeast-2' },
});

new S3Client({
  credentials: awsCredsProvider,
  region: "ap-southeast-2",
});

new LexRuntimeV2Client({
  credentials: awsCredsProvider,
  region: "ap-southeast-2",
});
```

**Comment by thomaschaaf** [comment] 2024-08-26 09:29
@kuhe when will the fix be released?

**Comment by kuhe** [comment] 2024-09-05 01:18
The fix was released in https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.632.0

**Closed** 2024-09-05 01:19 UTC
Labels: closing-soon, bug, p2
