### ISSUE TITLE
Can't compile with @aws-sdk/client-elastic-load-balancing-v2:3.38.0

### ISSUE THREAD

**Issue by AK-Forter** [aws/aws-sdk-js-v3#2951] opened 2021-10-28 17:20 UTC
## Describe the bug

When trying to compile my code, with @aws-sdk/client-elastic-load-balancing-v2": "3.38.0" set as a dependency, I get an error that is missing a closing '}' from one of the type definitions.

#### SDK version number
`@aws-sdk/client-elastic-load-balancing-v2:3.38.0`
`@aws-sdk/client-elastic-load-balancing-v2:3.37.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Node v14.17.0
Typescript v: ^3.9.10

## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.
Run `tsc` when using the following imports:
```
import {
  DescribeLoadBalancersCommand,
  DescribeTargetGroupsCommand,
  DescribeTargetGroupsCommandOutput,
  DescribeTargetHealthCommand,
  DescribeTargetHealthCommandOutput,
  ElasticLoadBalancingV2Client
} from '@aws-sdk/client-elastic-load-balancing-v2'
```

#### Observed behavior
Compilation error with versions 3.37.0 and 3.38.0
version 3.36.0 compiles correctly.

#### Expected behavior
No compilation error

#### Screenshots
![Screen Shot 2021-10-28 at 20 13 26](https://user-images.githubusercontent.com/83745228/139303394-33e3f4e7-533a-47c8-a059-b5b0ffa842a1.png)

**Comment by vudh1** [comment] 2021-11-22 20:32
Hi @AK-Forter, thanks for reaching out. I'm not able to reproduce the issue you had above. I tried with multiple versions of `@aws-sdk/client-elastic-load-balancing-v2` :  `3.37.0`, `3.38.0`, `3.42.0`.  Can you show how you install the client?

**Comment by AK-Forter** [comment] 2021-11-22 21:31
I installed the client by copy pasting the dev dependencies into my package.json and then running `npm install` I'll see if I can reproduce it.

**Comment by vudh1** [comment] 2021-12-10 21:31
Closing this because no new update for reproducing the problem.

**Closed by vudh1** 2021-12-10 21:31 UTC
Labels: bug
