### ISSUE TITLE
waitForBucketExists doesn't resolve for buckets created with "EU" location constraint in "us-east-1" region

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#1799] opened 2020-12-17 02:25 UTC
**Describe the bug**
waitForBucketExists doesn't resolve for buckets created with "EU" location constraint in "us-east-1" region

**SDK version number**
`3.0.0`

**Is the issue in the browser/Node.js/ReactNative?**
All

**Details of the browser/Node.js/ReactNative version**
All

**To Reproduce (observed behavior)**
The following v3 code keeps calling the waiter:

<details>
<summary>Code</summary>

```js
const { S3, waitForBucketExists } = require("@aws-sdk/client-s3");

(async () => {
  const region = "us-east-1";
  const client = new S3({ region, logger: console });

  const Bucket = `test-bucket-${Date.now()}`;
  await client.createBucket({
    Bucket,
    CreateBucketConfiguration: {
      LocationConstraint: "EU",
    },
  });
  await waitForBucketExists({ client }, { Bucket });
  await client.deleteBucket({ Bucket });
})();

```

</details>

<details>
<summary>Output</summary>

```console
{ clientName: 'S3Client', commandName: 'CreateBucketCommand' }
{
  input: {
    Bucket: 'test-bucket-1608171295520',
    CreateBucketConfiguration: { LocationConstraint: 'EU' }
  }
}
{
  output: { Location: 'http://test-bucket-1608171295520.s3.amazonaws.com/' }
}
{
  metadata: {
    statusCode: 200,
    requestId: undefined,
    extendedRequestId: 'mRVkShXFY53vd+C44iJ+P4fZo4WLDLrIUdQi6lWTbWjWfor86uQVYJDbo+BoOGRzVXqHDONN6yk=',
    cfId: undefined
  }
}
{ clientName: 'S3Client', commandName: 'HeadBucketCommand' }
{ input: { Bucket: 'test-bucket-1608171295520' } }
{ clientName: 'S3Client', commandName: 'HeadBucketCommand' }
{ input: { Bucket: 'test-bucket-1608171295520' } }
{ clientName: 'S3Client', commandName: 'HeadBucketCommand' }
{ input: { Bucket: 'test-bucket-1608171295520' } }
...
```

</details>

When checked from console, the bucket is created.

The issue is not reproducible in v2:

<details>
<summary>Code</summary>

```js
const AWS = require("aws-sdk");

(async () => {
  const region = "us-east-1";
  const client = new AWS.S3({ region, logger: console });

  const Bucket = `test-bucket-${Date.now()}`;
  await client
    .createBucket({
      Bucket,
      CreateBucketConfiguration: {
        LocationConstraint: "EU",
      },
    })
    .promise();
  await client.waitFor("bucketExists", { Bucket }).promise();
  await client.deleteBucket({ Bucket }).promise();
})();

```

</details>

<details>
<summary>Output</summary>

```console
[AWS s3 200 0.877s 0 retries] createBucket({
  Bucket: 'test-bucket-1608171894069',
  CreateBucketConfiguration: { LocationConstraint: 'EU' }
})
[AWS s3 200 0.599s 0 retries] headBucket({ Bucket: 'test-bucket-1608171894069' })
[AWS s3 204 0.808s 0 retries] deleteBucket({ Bucket: 'test-bucket-1608171894069' })
```

</details>

**Expected behavior**
The waiter shouldn't wait if bucket is already created.

**Comment by alexforsyth** [comment] 2020-12-17 16:21
Under the hood, the waiter polls `HeadBucketCommand`
```
const client = new S3Client({ region, logger: console });
let pollResult = await client.send(new HeadBucketCommand({ Bucket: "test-bucket-XXXXDATEXXXX" }));
```
Looks like s3 doesn't follow the 301. 

Error:
```
{ Error: 
    at deserializeAws_restXmlHeadBucketCommandError (/Users/alexfors/Documents/workspace/sdk/playground/v3-test/node_modules/@aws-sdk/client-s3/protocols/Aws_restXml.ts:7402:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: '',
  '$fault': 'client',
  '$metadata':
   { httpStatusCode: 301,
     httpHeaders:
      { 'x-amz-bucket-region': 'eu-west-1',
        'x-amz-request-id': 'FC9F563D98AB2C5F',
        'x-amz-id-2':
         'QcM/fgya6AhkIlnra7rjiWCBSTz4zTl8aN0G8brTna4Cr28RRuhH80ByIx30d4oRVoBC+Mu52ZA=',
        'content-type': 'application/xml',
        'transfer-encoding': 'chunked',
        date: 'Thu, 17 Dec 2020 16:11:35 GMT',
        server: 'AmazonS3' },
     requestId: undefined,
     attempts: 1,
```
     
If the client is configured with `eu-west-1` then it should work as intended.
```
     const region = "eu-west-1";
  const client = new S3Client({ region, logger: console }); 
  ....
```

**Comment by alexforsyth** [comment] 2020-12-17 16:30
Closing this issue, root cause issue can be tracked here:

https://github.com/aws/aws-sdk-js-v3/issues/1802

**Closed by alexforsyth** 2020-12-17 16:30 UTC
