### ISSUE TITLE
MIGRATION ISSUE: Region Is Not Being Set For S3 Client

### ISSUE THREAD

**Issue by TomerPacific** [aws/aws-sdk-js-v3#5767] opened 2024-02-06 07:18 UTC
### Pre-Migration Checklist

- [X] I've read the [Migration Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html).
- [X] I've reviewed the upgrading notes and major version differences mentioned in [`UPGRADING.md`](https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md).
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for similar migration issues.

### Which JavaScript Runtime is this issue in?

Browser

### AWS Lambda Usage

- [ ] Yes, my application is running on AWS Lambda.
- [X] No, my application is not running on AWS Lambda.

### Describe the Migration Issue

When migrating from AWS SDK JS V2 to V3, it was observed that it was needed to set the region for the S3 client being instantiated.
When printing the config object for the instantiated S3 client, **the region is not observed there** as opposed to the AWS SDK JS V2 config.

Below are code snippets from our code using AWS SDK JS V2:
```
import {S3} from "aws-sdk";
_s3:S3 = new S3({apiVersion: "2006-03-01"});
```

and using AWS SDK JS V3:

```
import {S3} from "@aws-sdk/client-s3";
this._s3 = new S3({region: 'us-east-1'});
```

I have also tried using:
```
import {S3Client} from "@aws-sdk/client-s3";
this._s3 = new S3Client({region: 'us-east-1'});
```

This is the output when I log the S3 client config in V3:
`{"apiVersion":"2006-03-01","disableHostPrefix":false,"extensions":[],"logger":{},"serviceId":"S3","signingEscapePath":false,"runtime":"node","requestHandler":{"metadata":{"handlerProtocol":"http/1.1"},"configProvider":{}},"forcePathStyle":false,"useAccelerateEndpoint":false,"useGlobalEndpoint":false,"disableMultiregionAccessPoints":false,"defaultSigningName":"s3","tls":true,"isCustomEndpoint":false,"systemClockOffset":0,"followRegionRedirects":false,"s3ExpressIdentityProvider":{"cache":{"data":{},"lastPurgeTime":1707198854366}},"eventStreamMarshaller":{"universalMarshaller":{"eventStreamCodec":{"headerMarshaller":{},"messageBuffer":[],"isEndOfStream":false}}}}`

And in V2:

`{"credentials":{"expired":false,"expireTime":null,"refreshCallbacks":[],"accessKeyId":"ACCESS_KEY","profile":"default","disableAssumeRole":true,"preferStaticCredentials":false,"tokenCodeFn":null,"httpOptions":null},"credentialProvider":{"providers":[null,null,null,null,null,null,null],"resolveCallbacks":[]},**"region":"us-east-1"**,"logger":null,"apiVersions":{},"apiVersion":"2006-03-01","endpoint":"s3.amazonaws.com","httpOptions":{"timeout":120000},"maxRedirects":10,"paramValidation":true,"sslEnabled":true,"s3ForcePathStyle":false,"s3BucketEndpoint":false,"s3DisableBodySigning":true,"s3UsEast1RegionalEndpoint":"legacy","computeChecksums":true,"convertResponseTypes":true,"correctClockSkew":false,"customUserAgent":null,"dynamoDbCrc32":true,"systemClockOffset":0,"signatureVersion":"s3","signatureCache":true,"retryDelayOptions":{},"useAccelerateEndpoint":false,"clientSideMonitoring":false,"endpointCacheSize":1000,"hostPrefixEnabled":true,"stsRegionalEndpoints":"legacy"}`

I am using this in a typescript project with Node16 on a mac machine with OS Ventura 13.5

### Observed Differences/Errors

The region doesn't seem to be set on the S3 client. This results in the following error:

```
Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read',
  name: 'TimeoutError',
  '$metadata': { attempts: 3, totalRetryDelay: 97 }
}
```

**Comment by RanVaknin** [comment] 2024-02-07 22:26
Hi @TomerPacific,

Thanks for reaching out. The code snippet looks correct. Without seeing an entire code sample including imports, client construction and the API call / log statement it will be difficult to weigh in on this. 

How are you logging the contents of the config? 

You can see if the region is set by adding this middleware hook:

```js
this._s3.middlewareStack.add(next => async (args) => {
 console.log(args.request)
 const response = await next(args);
 console.log(response);
 return next(args);
}, {step: 'finalizeRequest'})
```

This hook will log the raw outgoing request including the region. If you can check that it will tell if the region is actually set.

Thanks,
Ran~

**Comment by TomerPacific** [comment] 2024-02-20 17:32
@RanVaknin - Sorry for the late response. I'll post an update here tomorrow with the details you required.

**Comment by tomer-br-taboola** [comment] 2024-02-22 15:07
@RanVaknin - I am logging the response using the S3's client config property. I.E. ```this._s3.config```.
I noticed that if I try to log the region on the config, via ```this._s3.config.region``` I get undefined.

There isn't much more to add in respect of the code as the instantiation and the imports are there.
The project I am working on is client side (not Node.js) so I am unsure how the middleware hook applies here.

Regardless of the above, shouldn't i be able to see the region after setting it via the client instantiation?

**Comment by RanVaknin** [comment] 2024-02-23 21:59
Hi @tomer-br-taboola ,

>Regardless of the above, shouldn't i be able to see the region after setting it via the client instantiation?

No. Unlike in v2, in v3 the config object is passed down to the request itself and only getting resolves when the SDK client builds the URL to make the request, before signing. 

Since you didn't share your complete code snippet, its unclear how you are attempting to log it, therefore might lead to `undefined`.

```js
const s3 = new S3Client({region: "us-west-2"});
console.log(await s3.config.region())
// prints: us-west-2
```

The reason I'm scrutinizing your analysis of the problem is because if it were a problem with the SDK not setting the region you would have seen a different error, something like :

```
Error: getaddrinfo ENOTFOUND s3.invalidregion.amazonaws.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 's3.undefined.amazonaws.com',
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

> The project I am working on is client side (not Node.js) so I am unsure how the middleware hook applies here.

It still applies here. If you are running this from the browser you should be able to see the request and response logs in the browser's console tab. 

In order to further debug this I will need to see your complete code example and also details on how you are building the SDK to run on the browser.

Thanks,
Ran~

**Comment by tomer-br-taboola** [comment] 2024-03-04 05:53
@RanVaknin  - I can confirm that when running:

`console.log(await s3.config.region())`

I get the region of the S3 client I am setting.

I posted in my original question how i log the region, by accessing it through the config object. I wasn't aware that it was an async method and not just an attribute you can access (**as was in V2**).

Thanks for your assistance.
I am closing this issue.

**Closed** 2024-03-04 05:55 UTC
Labels: response-requested, bug, p2, v2-v3-inconsistency
