### ISSUE TITLE
TimestreamQueryClient.query throws UnknownOperationException

### ISSUE THREAD

**Issue by iconara** [aws/aws-sdk-js-v3#1898] opened 2021-01-11 20:26 UTC
**Describe the bug**
Trying to query a Timestream table using `TimestreamQueryClient` results in `UnknownOperationException`.

**SDK version number**
`@aws-sdk/client-timestream-query@^3.2.0`

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
```console
$ node -v
v12.16.1
```

**To Reproduce (observed behavior)**
```js
const {TimestreamQueryClient, QueryCommand} = require('@aws-sdk/client-timestream-query')
const client = new TimestreamQueryClient({region: 'us-east-2'})
const command = new QueryCommand({QueryString: 'SELECT * FROM table'})
await client.send(command)
```

or

```js
const {TimestreamQuery} = require('@aws-sdk/client-timestream-query')
const client = new TimestreamQuery({region: 'us-east-2'})
await client.query('SELECT * FROM table')
```

**Expected behavior**
No error.

**Comment by iconara** [comment] 2021-01-12 08:11
I should add that using v2 this works fine:

```
const Timestream = require('aws-sdk/clients/timestreamquery')
const client = new Timestream({region: 'us-east-2'})
await client.query({QueryString: 'SELECT * FROM table'}).promise()
```

**Comment by mayurm88** [comment] 2021-01-14 13:16
Looks like the timestream client hasn't been implemented yet. Got the same error with `writeRecords` request.

```
import { TimestreamWrite, WriteRecordsRequest } from "@aws-sdk/client-timestream-write";

const timestreamWrite = new TimestreamWrite({});

const request:WriteRecordsRequest = {
    DatabaseName: DATABASE_NAME,
    Records: [a, b, c],
    TableName: TABLE_NAME
};
timestreamWrite.writeRecords(request);
```

Error:

```
{
    "errorType": "UnknownOperationException",
    "errorMessage": "UnknownOperationException",
    "__type": "com.amazon.coral.service#UnknownOperationException",
    "name": "UnknownOperationException",
    "$fault": "client",
    "$metadata": {
        "httpStatusCode": 404,
        "requestId": "50a4df34-5e04-4e34-87dc-3a0da2e5d64d",
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "stack": [
        "UnknownOperationException: UnknownOperationException",
        "    at /var/task/index.js:2:940788",
        "    at /var/task/index.js:2:904642",
        "    at Object.next (/var/task/index.js:2:904747)",
        "    at a (/var/task/index.js:2:903486)",
        "    at runMicrotasks (<anonymous>)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    ]
}
```

**Comment by jpoissant** [comment] 2021-01-25 20:43
I have the same issue when trying to use `WriteRecordsCommand` (from `@aws-sdk/client-timestream-write` `^3.3.0` ) when running locally or an AWS Lambda

**Comment by lewchuk** [comment] 2021-02-08 22:14
I encountered this same generic error on `writeRecords`. However, after downgrading to AWS-SDK v2 and using the exact same inputs `writeRecords` worked fine.

```js
export const buildTimestreamWrite = (d) => {
  return {
    "CommonAttributes": {
       "Dimensions": dimensions.map(name => ({
            "DimensionValueType": "VARCHAR",
            "Name": name,
            "Value": `${d[name]}`,
        })),
       "Time": `${d[timestamp]}`,
       "TimeUnit": "MILLISECONDS",
    },
    "DatabaseName": tsDatabase,
    "Records": numericValues.map(name => ({
      "MeasureName": name,
      "MeasureValue": `${d[name]}`,
      "MeasureValueType": "DOUBLE",
    })),
    "TableName": dataSetSuffix
 }
}
```

V2 code that works:
```js
import { TimestreamWrite } from 'aws-sdk';
const tsClient = new TimestreamWrite({ region: "us-west-2" });
const tsRequests = (<any[]>rawBatch).map(buildTimestreamWrite);
const batchPromises = tsRequests.map(command => tsClient.writeRecords(command).promise());
try {
  console.log(await Promise.all(batchPromises));
} catch (error) {
  console.log(error);
}
```

V3 code that does not work:

```js
import { TimestreamWrite } from "@aws-sdk/client-timestream-write";
const tsClient = new TimestreamWrite({ region: "us-west-2" });
const tsRequests = (<any[]>rawBatch).map(buildTimestreamWrite);
const batchPromises = tsRequests.map(command => tsClient.writeRecords(command));
try {
  console.log(await Promise.all(batchPromises));
} catch (error) {
  console.log(error);
}
```

My error:
```
UnknownOperationException: UnknownOperationException
    at deserializeAws_json1_0WriteRecordsCommandError (<root>/node_modules/@aws-sdk/client-timestream-write/protocols/Aws_json1_0.ts:1644:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at <root>/node_modules/@aws-sdk/middleware-serde/src/deserializerMiddleware.ts:20:18
    at <root>/node_modules/@aws-sdk/middleware-signing/src/middleware.ts:26:22
    at StandardRetryStrategy.retry (<root>/node_modules/@aws-sdk/middleware-retry/src/defaultStrategy.ts:125:38)
    at <root>/node_modules/@aws-sdk/middleware-logger/src/loggerMiddleware.ts:21:20
    at async Promise.all (index 0)
    at loadData (<root>/src/import-ts.ts:128:23) {
  __type: 'com.amazon.coral.service#UnknownOperationException',
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 404,
    requestId: '30708119-3588-49e5-b2bd-fb9c60dfbdd0',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```

**Comment by pfried** [comment] 2021-02-19 07:24
To me it looks like the SDK is not correctly resolving the endpoint. This still happens in v3.5.0 for simple commands.

The [docs](https://docs.aws.amazon.com/timestream/latest/developerguide/Using-API.endpoint-discovery.how-it-works.html) state that the endpoint resolution is done automatically but the 404 indicates this is not true or not working correctly.

**Comment by mapoulos** [comment] 2021-02-24 15:25
I'm also hitting the same issue

**Comment by joaomdmoura** [comment] 2021-03-08 21:30
Problem still happening in version `3.8.0` for the `WriteRecordsCommand`, any workarounds other than dowgrading?

**Comment by pfried** [comment] 2021-03-09 06:47
@joaomdmoura Did you see my suggestion above, does this work for you? You could also just statically add the `endpoint` property to the constructor

**Comment by joaomdmoura** [comment] 2021-03-09 12:39
@pfried Oh sorry I totally skipped that! I'll give it a try, but makes sense!

**Comment by Tantalon** [comment] 2021-03-12 01:36
@pfried your workaround works great, thanks!

**Comment by trivikr** [comment] 2021-03-18 20:22
The endpoint discovery is not yet supported in AWS SDK for JavaScript (v3).
This documentation is currently in PR https://github.com/aws/aws-sdk-js-v3/pull/2106, and the support is planned in 2021.

**Comment by kennu** [comment] 2021-04-08 21:09
Same problem here with WriteRecordsCommand, waiting for support so I can remove workarounds.

**Comment by trivikr** [comment] 2021-05-02 23:57
The endpoint discovery support is being added in https://github.com/aws/aws-sdk-js-v3/issues/2211

In the meantime, please call DescribeEndpoint API to pass custom endpoint during client creation as explained in https://github.com/aws/aws-sdk-js-v3/issues/1898#issuecomment-781887697

Verified by using the code below:

```js
import { TimestreamQuery } from "@aws-sdk/client-timestream-query";
import { TimestreamWrite } from "@aws-sdk/client-timestream-write";

const region = "us-west-2";
const endpointsQueryClient = new TimestreamQuery({ region });
const endpointsWriteClient = new TimestreamWrite({ region });

const qClientResponse = await endpointsQueryClient.describeEndpoints({});
const wClientResponse = await endpointsWriteClient.describeEndpoints({});

const queryClient = new TimestreamQuery({
  region,
  endpoint: `https://${qClientResponse.Endpoints[0].Address}`,
});
const writeClient = new TimestreamWrite({
  region,
  endpoint: `https://${wClientResponse.Endpoints[0].Address}`,
});

const DatabaseName = `Database${Date.now()}`;
const TableName = `Table${Date.now()}`;
const RetentionProperties = {
  MemoryStoreRetentionPeriodInHours: 1,
  MagneticStoreRetentionPeriodInDays: 1,
};

await writeClient.createDatabase({ DatabaseName });

await writeClient.createTable({ DatabaseName, TableName, RetentionProperties });

const currentTime = Date.now().toString(); // Unix time in milliseconds

const dimensions = [
  { Name: "region", Value: "us-east-1" },
  { Name: "az", Value: "az1" },
  { Name: "hostname", Value: "host1" },
];

const cpuUtilization = {
  Dimensions: dimensions,
  MeasureName: "cpu_utilization",
  MeasureValue: Math.floor(Math.random() * 101).toString(),
  MeasureValueType: "DOUBLE",
  Time: currentTime.toString(),
};

const memoryUtilization = {
  Dimensions: dimensions,
  MeasureName: "memory_utilization",
  MeasureValue: Math.floor(Math.random() * 101).toString(),
  MeasureValueType: "DOUBLE",
  Time: currentTime.toString(),
};

const Records = [cpuUtilization, memoryUtilization];

await writeClient.writeRecords({ DatabaseName, TableName, Records });

const QueryString = `SELECT * FROM ${DatabaseName}.${TableName} ORDER BY time DESC LIMIT 10`;
console.log(await queryClient.query({ QueryString }));

await writeClient.deleteTable({ DatabaseName, TableName });
await writeClient.deleteDatabase({ DatabaseName });

```

**Comment by Sagar-Chudamani** [comment] 2022-02-22 13:23
@trivikr @kennu 
Tried the above mentioned workaround and it did not work as expected. Are there any other workarounds/solutions?

**Comment by kuhe** [comment] 2022-04-20 16:36
@Sagar-Chudamani, please create a new issue describing the problem you encountered, with sample code that can reproduce the problem. I would like to close this issue because the original problem appears to have been fixed and this workaround should not be needed.

**Closed by kuhe** 2022-04-20 16:36 UTC
Labels: bug
