### ISSUE TITLE
Get each File bandwidth or download count

### ISSUE THREAD

**Issue by hanumanjiblog** [aws/aws-sdk-js-v3#2827] opened 2021-09-24 20:10 UTC
Get each File bandwidth or download count, please make this feature or if available let me know.

**Comment by vudh1** [comment] 2021-10-15 18:06
Hi, thank you for your post, can you follow this template for more information.

### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

### Describe the solution you'd like
A clear and concise description of what you want to happen.

### Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've considered.

### Additional context
Add any other context or screenshots about the feature request here.

**Comment by hanumanjiblog** [comment] 2021-10-16 04:34
this is a question

**Comment by vudh1** [comment] 2021-10-21 22:02
Hi @hanumanjiblog, thank you for reaching out. Can you help me understand better by clarifying more about your question or giving an example of what features you want?

**Comment by RanVaknin** [comment] 2023-02-18 00:22
@hanumanjiblog ,

Since this has been a while and you were not clear about the feature request I feel like we can close this.

If you are still interested in this FR, please open a new one and help us better understand what you mean by get each file bandwidth. Just to let you know, the SDK is a client and only serves as a such when interacting with AWS services. If you need a specific set of data returned, this is something that can be only changed on the service side. 

Thanks,
Ran.

**Closed by RanVaknin** 2023-02-18 00:22 UTC
Labels: feature-request
