### ISSUE TITLE
Can't get private devices in Node

### ISSUE THREAD

**Issue by nickohold** [aws/aws-sdk-js-v3#4732] opened 2023-05-18 11:16 UTC
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I have a project with private devices, which I've been using to manually schedule runs via the AWS platform, successfully.
I also have a script to schedule runs programmatically, which works great for public devices.
However, whenever I use a filter in ListDevicesCommand, like this:

`[{"attribute": "FLEET_TYPE", "operator": "EQUALS", "values": ["PRIVATE"]}]`

or in ScheduleRunCommand after using a hardcoded ARN of one of my private devices, as such:
```console
deviceSelectionConfiguration: {
  filters: [
    {
      attribute: "ARN",
      operator: "EQUALS",
      values: [arn],
    },
  ],
  maxDevices: 1,
},
```

I get 0 devices back.

Running the same command from the cli:

```console
aws devicefarm list-devices --filters '[{"attribute": "FLEET_TYPE", "operator": "EQUALS", "values": ["PRIVATE"]}]' --region us-west-2
```

works as expected, and I get the private devices in the response.

The credentials used are the same (same credentials file), so it's not a permissions issue.
The setup has been verified by an AWS device farm expert.

I am at a loss, and can't figure out what is wrong. I have followed the documentation to the tee.

### SDK version number

@aws-sdk/client-device-farm@3.267.0 & 3.332.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.14.2

### Reproduction Steps

```js
public async getDevices() {
    const options = {
        filters: [{ "attribute": "FLEET_TYPE", "operator": "EQUALS", "values": ["PRIVATE"] }],
    };
    const command = new ListDevicesCommand(options);
    const data = await this.deviceFarm.send(command);
    debug(`Got devices ${JSON.stringify(data)}`);
    if (!data || !data.devices) {
        throw new Error("No devices found");
    }
}
```

### Observed Behavior

```json
{
  "$metadata": {
    "httpStatusCode": 200,
    "requestId": "5bcd6d2d-d27a-46a3-89b4-aab09430bb3e",
    "attempts": 1,
    "totalRetryDelay": 0
  },
  "devices": [],
  "nextToken": "eyJpZCI6eyJzIjoiRjM1OEFFQjFEMkRBNDFCRkFDOTEyQ0ZDNEQwRkVCREEvMTAwMDA5MyIsIm4iOm51bGwsImIiOm51bGwsIm0iOm51bGwsImwiOm51bGwsImJvb2wiOm51bGwsInNzIjpudWxsLCJucyI6bnVsbCwiYnMiOm51bGwsIm51bGwiOm51bGx9fQ=="
}
```

### Expected Behavior

Same functionality as the CLI: To get a list of the private devices we have under our project (4).

**Comment by Yurish-IL** [comment] 2023-05-18 11:29
+1 same here

**Comment by shavit-trop** [comment] 2023-05-18 11:36
+1

**Comment by Avital-r** [comment] 2023-05-18 11:37
same

**Comment by yenfryherrerafeliz** [comment] 2023-05-18 17:26
Hi @nickohold, thanks for reporting this. Could any of you please (@nickohold, @Yurish-IL, @shavit-trop, @Avital-r) run the code below and post the results here?, just understand if the issue is with the deserialization of the response, or with the response that comes from the service it self?

Code:
```js
import {S3Client, ListBucketsCommand} from "@aws-sdk/client-s3";
import {NodeHttpHandler} from "@aws-sdk/node-http-handler";

class CustomHandler extends NodeHttpHandler {
    async handle(request, {abortSignal}) {
        const response = await super.handle(request, {abortSignal});
        const body = response.response.body;
        let data = "";
        body.on('data', (chunk) => {
             data += Buffer.from(chunk).toString()
        });
        body.on('end', () => {
            console.log('Data: ', data);
        });

        return response;
    }
}
const client = new S3Client({
    region: 'us-east-2',
    requestHandler: new CustomHandler()
});
client.middlewareStack.add(next => args => {
    console.log('Request: ', args.request);

    return next(args);
}, {
    step: "finalizeRequest"
});
client.send(new ListBucketsCommand({}))
.catch(console.log);
```

Note: Please make sure that any sensitive information, such as credentials, are redacted.

Thanks!

**Comment by yenfryherrerafeliz** [comment] 2023-05-18 17:33
Hi @nickohold, thanks for reporting this. Could any of you (@nickohold, @Yurish-IL, @shavit-trop, @Avital-r) please run the code below and post the results here?. It is just to understand if the issue is with the deserialization of the response, or with the response that comes from the service itself. 

```js 
import {DeviceFarmClient, ListDevicesCommand} from "@aws-sdk/client-device-farm";
import {NodeHttpHandler} from "@aws-sdk/node-http-handler";

class CustomHandler extends NodeHttpHandler {
    async handle(request, {abortSignal}) {
        const response = await super.handle(request, {abortSignal});
        const body = response.response.body;
        let data = "";
        body.on('data', (chunk) => {
            data += Buffer.from(chunk).toString()
        });
        body.on('end', () => {
            console.log('Data: ', data);
        });

        return response;
    }
}
const client = new DeviceFarmClient({
    region: 'us-west-2',
    requestHandler: new CustomHandler()
});
client.middlewareStack.add(next => args => {
    console.log('Request: ', args.request);

    return next(args);
}, {
    step: "finalizeRequest"
});
client.send(new ListDevicesCommand({
    filters: [
        {
            attribute: "FLEET_TYPE",
            operator: "EQUALS",
            values: [
                "PRIVATE"
            ]
        }
    ]
})).catch(console.log);

```

Note: Please make sure you redact any sensitive information, such as credentials.

Thanks!

**Comment by RanVaknin** [comment] 2023-05-18 19:29
Just a reminder for the folks on the thread. We monitor engagement based on reactions, you can use the 👍  reaction button instead of commenting +1. 

Thanks,
Ran~

**Comment by nickohold** [comment] 2023-05-19 20:21
Hi @RanVaknin.
Here's the response of ListDevicesCommand:

`Data:  {"devices":[],"nextToken":"eyJpZCI6eyJzIjoiQkNDMEZDNzkzNEIyNDM1OEE1QjM1QzFGOTk5NjIyNUMvMTAwMDM4OSIsIm4iOm51bGwsImIiOm51bGwsIm0iOm51bGwsImwiOm51bGwsImJvb2wiOm51bGwsIm5zIjpudWxsLCJzcyI6bnVsbCwiYnMiOm51bGwsIm51bGwiOm51bGx9fQ=="}`

**Comment by nickohold** [comment] 2023-05-22 07:35
@RanVaknin did you see my last response? I was wondering if you have any follow-up, we're really stuck on this, it's a crucial part of an automation run on the device farm, and basically nullifies the usage of the device farm.

Thank you!

**Comment by Yurish-IL** [comment] 2023-05-23 05:50
@yenfryherrerafeliz Please see Nick's reply

**Comment by aristeia** [comment] 2023-05-23 21:52
Hey folks, it turns out this is more of a pagination issue with the API than an SDK issue. The API is returning a valid response, as well as a next token, with the expectation for the user to use that next token regardless of the fact that zero devices were found on the first page. It appears that, when filtering devices, the desired filtered device can often be on the second or third page, and that the filter filters out all devices on the first page. 

I am syncing with the Device Farm service team to determine next steps given this behavior.

**Comment by yenfryherrerafeliz** [comment] 2023-09-13 18:54
@aristeia  thanks for letting us know. I will close this as completed.

**Closed by yenfryherrerafeliz** 2023-09-13 18:54 UTC
Labels: bug, p2
