### ISSUE TITLE
Unable to resolve module events in @aws-sdk/lib-storage

### ISSUE THREAD

**Issue by jereztech** [aws/aws-sdk-js-v3#2156] opened 2021-03-19 05:06 UTC
Unable to resolve module events in @aws-sdk/lib-storage/dist/cjs/Upload.js

"@aws-sdk/client-s3": "^3.9.0",
"@aws-sdk/lib-storage": "^3.9.0",
"react": "17.0.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",

**Comment by ajredniwja** [comment] 2021-03-19 06:07
Hey @jereztech, thanks for opening this issue, can you please follow the [issue template](https://github.com/aws/aws-sdk-js-v3/issues/new?assignees=&labels=bug%2C+needs-triage&template=---bug-report.md&title=)? 

I am looking for more information on how to reproduce this. Thankyou

**Comment by jereztech** [comment] 2021-03-19 18:17
Hi @ajredniwja, thanks for reply.

**Bug Description:**
importing @aws-sdk/lib-storage@3.9.0 module crashes the application

**Environment:**
@aws-sdk/lib-storage@3.9.0
react-native-cli@2.0.1
expo-cli@4.3.1
node@14.15.4
npm@7.6.3

**Minimal Repo:**
https://snack.expo.io/@jjerezalo/eabc8c (Snack: Failed to resolve dependency '@aws-sdk/lib-storage@^3.9.0' - Cannot resolve module fs after installing it as a dependency)

Using expo init lib-storage-demo, just add the fallowing to package.json and then npm install
"@aws-sdk/client-cognito-identity": "^3.9.0",
"@aws-sdk/client-s3": "^3.9.0",
"@aws-sdk/credential-provider-cognito-identity": "^3.9.0",
"@aws-sdk/lib-storage": "^3.9.0",

**Error:** Unable to resolve module events from /Users/.../.../.../node_modules/@aws-sdk/lib-storage/dist/cjs/Upload.js: events could not be found within the project.

I'm following the official documentation: https://www.npmjs.com/package/@aws-sdk/lib-storage

**My minimal code:**

import { CognitoIdentityClient } from "@aws-sdk/client-cognito-identity";
import { fromCognitoIdentityPool } from "@aws-sdk/credential-provider-cognito-identity";
import { Upload } from "@aws-sdk/lib-storage";
import {
    S3Client,
} from "@aws-sdk/client-s3";

const REGION = "us-east-2";
const s3Client = new S3Client({
    region: REGION,
    credentials: fromCognitoIdentityPool({
        client: new CognitoIdentityClient({ region: REGION }),
        identityPoolId: "IDENTITY_ID",
    }),
});

export const uploadFile = async (bucketName, key, file, onProgressFn, onResponseFn) => {
    try {
        const paralellUploads3 = new Upload({
            client: s3Client,
            params: { Bucket: bucketName, Key: key, Body: file },
        });
        paralellUploads3.on("httpUploadProgress", (progress) => {
            console.log(progress);
            onProgressFn && onProgressFn(progress)
        });
        return await paralellUploads3.done();
    } catch (e) {
        console.log(e);
    }
}

**Importing Upload from @aws-sdk/lib-storage crashes the application.**

**Comment by ajredniwja** [comment] 2021-03-22 20:31
This is a duplicate of https://github.com/aws/aws-sdk-js-v3/issues/2136

Workaround for now is to lower the version of lib-storage to 3.7.0 in your pacakge.json

I have created a PR for the fix https://github.com/aws/aws-sdk-js-v3/pull/2165

The issue should be resolved soon. Thankyou

**Comment by trivikr** [comment] 2021-03-22 21:25
Fixed in https://github.com/aws/aws-sdk-js-v3/pull/2165, to be published with the next release expected on 3/25 or 3/26.

**Closed by trivikr** 2021-03-22 21:25 UTC
Labels: bug

**Comment by VitaliiShpital** [comment] 2021-03-26 13:54
could someone confirm please if it'll be released today?

**Comment by trivikr** [comment] 2021-03-26 15:53
> could someone confirm please if it'll be released today?

Yes. The fix will be released today with `v3.10.0`

**Comment by VitaliiShpital** [comment] 2021-03-29 08:02
@trivikr thank you!
