### ISSUE TITLE
Commands change since rc5 breaks typescript compilationn

### ISSUE THREAD

**Issue by roderik** [aws/aws-sdk-js-v3#1687] opened 2020-11-14 08:31 UTC
**Describe the bug**

Since rc5 and rc6 a lot of types are messed up around the commands, one example, but all commands we use are broken this way.

```
src/deployments/adapters/eks-adapter.ts(192,32): error TS2345: Argument of type 'DeleteTargetGroupCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
```

Code snippet

```
import {
  DeleteTargetGroupCommand,
  ElasticLoadBalancingV2Client,
} from '@aws-sdk/client-elastic-load-balancing-v2';

const elbv2Client = new ElasticLoadBalancingV2Client({
  credentials: {
    accessKeyId: this.credentials.accessKeyId,
    secretAccessKey: this.credentials.secretAccessKey,
  },
  region,
});
await elbv2Client.send(new DeleteTargetGroupCommand({ TargetGroupArn: emptyTargetGroup }));

```

**SDK version number**

Up to rc4 works
rc5 and 6 do not

**Is the issue in the browser/Node.js/ReactNative?**

Node.js / Typescript

**Details of the browser/Node.js/ReactNative version**

Node v14.15.0
Typescript v4.0.5

**Comment by ajredniwja** [comment] 2020-12-03 23:21
Hey @roderik thanks for opening this, I was not able to reproduce this using  `@aws-sdk/client-elastic-load-balancing-v2@1.0.0-rc.7`, can you try using `@1.0.0-rc.7`

**Comment by roderik** [comment] 2020-12-04 15:08
Nope, 7 also does not work

```
src/deployments/adapters/eks-adapter.ts(66,43): error TS2345: Argument of type 'ListClustersCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
  Property 'model' is missing in type 'ListClustersCommand' but required in type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
src/deployments/adapters/eks-adapter.ts(68,22): error TS2339: Property 'clusters' does not exist on type 'ServiceOutputTypes'.
  Property 'clusters' does not exist on type 'CreateClusterCommandOutput'.
src/deployments/adapters/eks-adapter.ts(79,43): error TS2345: Argument of type 'ListNodegroupsCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
  Property 'model' is missing in type 'ListNodegroupsCommand' but required in type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
src/deployments/adapters/eks-adapter.ts(81,22): error TS2339: Property 'nodegroups' does not exist on type 'ServiceOutputTypes'.
  Property 'nodegroups' does not exist on type 'CreateClusterCommandOutput'.
src/deployments/adapters/eks-adapter.ts(93,44): error TS2345: Argument of type 'DescribeVolumesCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
  Property 'model' is missing in type 'DescribeVolumesCommand' but required in type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
src/deployments/adapters/eks-adapter.ts(95,20): error TS2339: Property 'Volumes' does not exist on type 'ServiceOutputTypes'.
  Property 'Volumes' does not exist on type 'MetadataBearer'.
src/deployments/adapters/eks-adapter.ts(96,42): error TS2339: Property 'Volumes' does not exist on type 'ServiceOutputTypes'.
  Property 'Volumes' does not exist on type 'MetadataBearer'.
src/deployments/adapters/eks-adapter.ts(96,58): error TS7006: Parameter 'volume' implicitly has an 'any' type.
src/deployments/adapters/eks-adapter.ts(98,32): error TS2345: Argument of type 'DeleteVolumeCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
  Property 'model' is missing in type 'DeleteVolumeCommand' but required in type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
src/deployments/adapters/eks-adapter.ts(145,15): error TS2339: Property 'TargetGroups' does not exist on type 'ServiceOutputTypes'.
src/deployments/adapters/eks-adapter.ts(145,69): error TS2345: Argument of type 'DescribeTargetGroupsCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
  Property 'model' is missing in type 'DescribeTargetGroupsCommand' but required in type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
src/deployments/adapters/eks-adapter.ts(148,19): error TS2339: Property 'TargetHealthDescriptions' does not exist on type 'ServiceOutputTypes'.
src/deployments/adapters/eks-adapter.ts(149,13): error TS2345: Argument of type 'DescribeTargetHealthCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
  Property 'model' is missing in type 'DescribeTargetHealthCommand' but required in type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
src/deployments/adapters/eks-adapter.ts(162,15): error TS2339: Property 'LoadBalancers' does not exist on type 'ServiceOutputTypes'.
src/deployments/adapters/eks-adapter.ts(162,73): error TS2345: Argument of type 'DescribeLoadBalancersCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
  Property 'model' is missing in type 'DescribeLoadBalancersCommand' but required in type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
src/deployments/adapters/eks-adapter.ts(165,19): error TS2339: Property 'Listeners' does not exist on type 'ServiceOutputTypes'.
src/deployments/adapters/eks-adapter.ts(166,13): error TS2345: Argument of type 'DescribeListenersCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
  Property 'model' is missing in type 'DescribeListenersCommand' but required in type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
src/deployments/adapters/eks-adapter.ts(174,44): error TS2345: Argument of type 'DeleteListenerCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
  Property 'model' is missing in type 'DeleteListenerCommand' but required in type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
src/deployments/adapters/eks-adapter.ts(180,19): error TS2339: Property 'Listeners' does not exist on type 'ServiceOutputTypes'.
src/deployments/adapters/eks-adapter.ts(181,13): error TS2345: Argument of type 'DescribeListenersCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
src/deployments/adapters/eks-adapter.ts(185,15): error TS2345: Argument of type 'DeleteLoadBalancerCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
  Property 'model' is missing in type 'DeleteLoadBalancerCommand' but required in type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
src/deployments/adapters/eks-adapter.ts(192,32): error TS2345: Argument of type 'DeleteTargetGroupCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
  Property 'model' is missing in type 'DeleteTargetGroupCommand' but required in type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
src/deployments/adapters/eks-adapter.ts(221,28): error TS2345: Argument of type 'DeleteNodegroupCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
  Property 'model' is missing in type 'DeleteNodegroupCommand' but required in type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
src/deployments/adapters/eks-adapter.ts(230,28): error TS2345: Argument of type 'DeleteClusterCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
  Property 'model' is missing in type 'DeleteClusterCommand' but required in type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
src/deployments/adapters/eks-adapter.ts(258,7): error TS2345: Argument of type 'DescribeClusterCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
  Property 'model' is missing in type 'DescribeClusterCommand' but required in type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
src/deployments/adapters/eks-adapter.ts(264,26): error TS2339: Property 'cluster' does not exist on type 'ServiceOutputTypes'.
  Property 'cluster' does not exist on type 'CreateFargateProfileCommandOutput'.
src/deployments/adapters/eks-adapter.ts(266,52): error TS2339: Property 'cluster' does not exist on type 'ServiceOutputTypes'.
  Property 'cluster' does not exist on type 'CreateFargateProfileCommandOutput'.
src/deployments/adapters/eks-adapter.ts(267,30): error TS2339: Property 'cluster' does not exist on type 'ServiceOutputTypes'.
  Property 'cluster' does not exist on type 'CreateFargateProfileCommandOutput'.
src/deployments/adapters/eks-adapter.ts(273,26): error TS2339: Property 'cluster' does not exist on type 'ServiceOutputTypes'.
  Property 'cluster' does not exist on type 'CreateFargateProfileCommandOutput'.
src/deployments/adapters/eks-adapter.ts(275,28): error TS2339: Property 'cluster' does not exist on type 'ServiceOutputTypes'.
  Property 'cluster' does not exist on type 'CreateFargateProfileCommandOutput'.
src/deployments/adapters/eks-adapter.ts(279,46): error TS2339: Property 'cluster' does not exist on type 'ServiceOutputTypes'.
  Property 'cluster' does not exist on type 'CreateFargateProfileCommandOutput'.
src/deployments/adapters/eks-adapter.ts(366,28): error TS2345: Argument of type 'CreateClusterCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
  Property 'model' is missing in type 'CreateClusterCommand' but required in type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
src/deployments/adapters/eks-adapter.ts(399,28): error TS2345: Argument of type 'CreateNodegroupCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
  Property 'model' is missing in type 'CreateNodegroupCommand' but required in type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
src/deployments/adapters/eks-adapter.ts(484,9): error TS2345: Argument of type 'DescribeClusterCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
src/deployments/adapters/eks-adapter.ts(488,29): error TS2339: Property 'cluster' does not exist on type 'ServiceOutputTypes'.
  Property 'cluster' does not exist on type 'CreateFargateProfileCommandOutput'.
src/deployments/adapters/eks-adapter.ts(513,9): error TS2345: Argument of type 'DescribeNodegroupCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
  Property 'model' is missing in type 'DescribeNodegroupCommand' but required in type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
src/deployments/adapters/eks-adapter.ts(518,29): error TS2339: Property 'nodegroup' does not exist on type 'ServiceOutputTypes'.
  Property 'nodegroup' does not exist on type 'CreateClusterCommandOutput'.
```

**Comment by roderik** [comment] 2020-12-08 08:21
RC8 has the same issue

```
src/deployments/adapters/eks-adapter.ts:513:9 - error TS2345: Argument of type 'DescribeNodegroupCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.
  Property 'model' is missing in type 'DescribeNodegroupCommand' but required in type 'Command<ServiceInputTypes, ServiceInputTypes, ServiceOutputTypes, ServiceOutputTypes, SmithyResolvedConfiguration<HttpHandlerOptions>, Uint8Array>'.

513         new DescribeNodegroupCommand({
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
514           clusterName: getClusterName(deployment, consortium),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
515           nodegroupName: getClusterName(deployment, consortium),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
516         })
    ~~~~~~~~~~
```

**Comment by alexforsyth** [comment] 2020-12-15 17:58
@roderik can you provide a bit more sample code to help us diagnose this issue a bit better?

Running this off `"@aws-sdk/client-elastic-load-balancing-v2": "^1.0.0-rc.10",`
```
node: 14.15.0
typescript: "~4.1.2", // same version the js sdk uses
```
// also tested with `ts-node: 9.0.0`
```
import {
    DeleteTargetGroupCommand,
    ElasticLoadBalancingV2Client,
  } from '@aws-sdk/client-elastic-load-balancing-v2';
  
(async () => {
  
    const client = new ElasticLoadBalancingV2Client({})
    const result =  await client.send(new DeleteTargetGroupCommand({ TargetGroupArn: "" }));
    console.log(result);
})();
```
Looks to work just as expected. It correctly makes the request and I get a result value back.

This particular code snippet will throw since its an empty arn:
```
ValidationError: An ARN must be specified
    at deserializeAws_queryDeleteTargetGroupCommandError (.....)
(node:7729) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:7729) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mungojam** [comment] 2020-12-23 07:30
Still to fix please

**Comment by roderik** [comment] 2020-12-23 07:51
I will retest with the newly released v3 tag today

**Comment by roderik** [comment] 2020-12-23 10:09
Ok, figured it out. We had a piece of code that was still using "@aws-sdk/client-elastic-load-balancing-node": "0.1.0-preview.2". This pulls in an old version of @aws-sdk/types which messed up the entire type resolution. (new packages do not seem to depend on it any more, if they would depend on 3.0.0 it would prevent this)

**Comment by trivikr** [comment] 2020-12-24 04:59
Closing as the issue was usage of preview versions of `@aws-sdk/client-elastic-load-balancing-node`

**Closed by trivikr** 2020-12-24 04:59 UTC
Labels: investigating
