### ISSUE TITLE
Lambda embedded SDK doesn't work alongside bundled node modules

### ISSUE THREAD

**Issue by paul-uz** [aws/aws-sdk-js-v3#4225] opened 2022-11-24 14:14 UTC
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

SDK v3 is embedded in the Node 18 Lambda image. But it does not work if you have a function with a package file and node_modules folder eg your function uses embedded AWS SDK for a database query, and uses a third party library like MomentJS.

### SDK version number

latest

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Node 18

### Reproduction Steps

Create simple function, using a v3 SDK eg lib-dynamodb. Add a single 3rd party module eg MomentJS.

The function won't be able to load lib-dynamodb.

Remove the MomemtJS usage and just have the Js file in the function, it should now be able to use lib-dynamodb successfully.

### Observed Behavior

Canot use the embedded v3 SDK when also using 3rd party modules.

### Expected Behavior

Should be able to use embedded SDK and additional modules

**Comment by jtuliani** [comment] 2022-11-25 18:21
@paul-uz Please can you provide more details to allow us to reproduce what you are seeing?

From our testing (function zip file includes node_modules with moment in it), ESM works:
```
import { S3Client } from "@aws-sdk/client-s3";
import * as moment from 'moment';

export const handler = async (e, c) => {
    console.log('S3Client', S3Client);
    console.log('moment', moment.default(new Date()).format());
}
2022-11-25T11:18:40.219Z	c5296dcf-d8b3-414b-92c8-6d9c8bb3345c	INFO	S3Client [class S3Client extends Client]
2022-11-25T11:18:40.270Z	c5296dcf-d8b3-414b-92c8-6d9c8bb3345c	INFO	moment 2022-11-25T11:18:40+00:00
```
And CJS works:
```
const { S3Client } = require("@aws-sdk/client-s3");
const moment = require('moment');

module.exports.handler = async (e, c) => {
    console.log('S3Client', S3Client);
    console.log('moment', moment().format());
}
2022-11-25T11:22:55.379Z	44a976db-3c49-40df-9e9b-31580b525a58	INFO	S3Client [class S3Client extends Client]
2022-11-25T11:22:55.439Z	44a976db-3c49-40df-9e9b-31580b525a58	INFO	moment 2022-11-25T11:22:55+00:00
```

**Comment by paul-uz** [comment] 2022-11-25 18:55
> @paul-uz Please can you provide more details to allow us to reproduce what you are seeing?
> 
> From our testing (function zip file includes node_modules with moment in it), ESM works:
> ```
> import { S3Client } from "@aws-sdk/client-s3";
> import * as moment from 'moment';
> 
> export const handler = async (e, c) => {
>     console.log('S3Client', S3Client);
>     console.log('moment', moment.default(new Date()).format());
> }
> 2022-11-25T11:18:40.219Z	c5296dcf-d8b3-414b-92c8-6d9c8bb3345c	INFO	S3Client [class S3Client extends Client]
> 2022-11-25T11:18:40.270Z	c5296dcf-d8b3-414b-92c8-6d9c8bb3345c	INFO	moment 2022-11-25T11:18:40+00:00
> ```
> And CJS works:
> ```
> const { S3Client } = require("@aws-sdk/client-s3");
> const moment = require('moment');
> 
> module.exports.handler = async (e, c) => {
>     console.log('S3Client', S3Client);
>     console.log('moment', moment().format());
> }
> 2022-11-25T11:22:55.379Z	44a976db-3c49-40df-9e9b-31580b525a58	INFO	S3Client [class S3Client extends Client]
> 2022-11-25T11:22:55.439Z	44a976db-3c49-40df-9e9b-31580b525a58	INFO	moment 2022-11-25T11:22:55+00:00
> ```

It's not about ESM or CommonJD, it's about having the local package file and node modules folder.

Try running a function that just uses the AWS SDK and nothing else, using the embedded SDK in the lambda. It will work. Now add in moment, and add the package.json (containing only momentjs) and node modules folder to the function. The call using the AWS SDK won't work.

**Comment by yenfryherrerafeliz** [comment] 2023-10-26 16:47
Hi @paul-uz, this seems to be fixed on lambda side. I just did a test and it worked just fine for me. In any case I feel that this issue was related to lambda itself and not with the SDK.

I will resolve this issue for now, but please feel free of opening a new issue if is there anything else that we can help with.

Thanks!

**Closed by yenfryherrerafeliz** 2023-10-26 16:47 UTC
Labels: bug, p2
