### ISSUE TITLE
CredentialsProviderError: Region is missing

### ISSUE THREAD

**Issue by JonWallsten** [aws/aws-sdk-js-v3#5743] opened 2024-01-30 07:20 UTC
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

After updating from 3.501.0 to 3.502.0 I can no longer use AWS SDK with SSO. Even though region is configured in the SSO profile, the SSO session and when creating the Route53 client I still get `CredentialsProviderError: Region is missing` error message.

### SDK version number

3.502.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.10.0

### Reproduction Steps

```js
function createRoute53Client() {
    return new Route53({
        region: 'eu-west-1',
        credentials: fromSSO({ profile: 'MyProfile' })
    });
}

async function getHostedZoneIdByName(
    hostedZoneName,
) {
    const route53Client = createRoute53Client();
    try {
        const response = await route53Client.send(new ListHostedZonesByNameCommand({ DNSName: hostedZoneName }));
        const hostedZone = response.HostedZones?.find((zone) => zone.Name === hostedZoneName + '.');
        if (hostedZone) {
            return hostedZone.Id;
        }
    } catch (error) {
        console.error('Error:', error);
    }
}

const hostedZone = await getHostedZoneIdByName('input');
```

### Observed Behavior

```
Error: CredentialsProviderError: Region is missing
    at Function.from (C:\Users\me\repo\aws-cdk\node_modules\@smithy\property-provider\dist-cjs\index.js:41:26)
    at resolveSSOCredentials (C:\Users\me\repo\aws-cdk\node_modules\@aws-sdk\credential-provider-sso\dist-cjs\index.js:107:61)
    at async coalesceProvider (C:\Users\me\repo\aws-cdk\node_modules\@smithy\core\dist-cjs\index.js:288:18)
    at async C:\Users\me\repo\aws-cdk\node_modules\@smithy\core\dist-cjs\index.js:306:18
    at async C:\Users\me\repo\aws-cdk\node_modules\@smithy\core\dist-cjs\index.js:82:17
    at async C:\Users\me\repo\aws-cdk\node_modules\@aws-sdk\middleware-logger\dist-cjs\index.js:33:22
    at async getHostedZoneIdByName (C:\Users\me\repo\aws-cdk\tools\common\common-helpers.ts:349:26)
    at async diffLocal (C:\Users\me\repo\aws-cdk\tools\common\diff-local.ts:92:26) 
```

### Expected Behavior

Call should work and not display error.

### Additional Information/Context

I tried to debug this, but there's several packages, many exports and promises involved so it's had to understand exactly where it goes wrong. But I think `resolveRegionConfig` is as far as I got when the error was thrown.

Error is eventually thrown here:
https://github.com/smithy-lang/smithy-typescript/blob/280ef3a90205bfaa208fe9ddfc088a80341c5032/packages/config-resolver/src/regionConfig/config.ts#L19

```
[sso-session DefaultSession]
sso_start_url = https://my_company.awsapps.com/start#
sso_region = eu-west-1
sso_registration_scopes = sso:account:access

[profile MyProfile]
sso_session = DefaultSession
sso_account_id = 11111111111
sso_role_name = Administrator
region = eu-west-1
output = json
```

**Comment by RanVaknin** [comment] 2024-01-30 18:51
HI @JonWallsten ,

Thank you for reporting this. We are looking into this with priority.

All the best,
Ran~

**Comment by kuhe** [comment] 2024-01-30 21:00
We are working on releasing a fix for this today. 
The bug is caused by the inner SSOClient within the `fromSSO` credential provider not reading the region correctly.

I recommend temporarily downgrading the SDK to your previous working version, or if it is safe to do so, set the region with `process.env.AWS_REGION = ...`. The latter will affect all SDK clients initialized without a region.

**Comment by kuhe** [comment] 2024-01-31 00:44
A fix for this was released in https://www.npmjs.com/package/@aws-sdk/client-route-53/v/3.503.1

And other clients with the same version number.

**Comment by JonWallsten** [comment] 2024-01-31 06:36
I can confirm that it works for me now! Thanks!

**Comment by RanVaknin** [comment] 2024-01-31 20:36
Great to hear that this worked out. If anything else comes up please open a new issue.

All the best,
Ran~

**Closed by RanVaknin** 2024-01-31 20:36 UTC
Labels: closing-soon, bug, p1
