### ISSUE TITLE
Number typings on `marshall` remain narrow

### ISSUE THREAD

**Issue by SimplyKnownAsG** [aws/aws-sdk-js-v3#5419] opened 2023-10-26 00:45 UTC
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

* Cannot marshal floating point numbers between MAX_SAFE_INTEGER and DynamoDB MAX.
* Cannot use marshal to save any number between 1e38 and DynamoDB MAX.
* The above are true for negatives as well.

This issue was previously reported in #1647.

### SDK version number

@aws-sdk/util-dynamodb@current

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

*

### Reproduction Steps

You can [view the implementation of marshall](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/util-dynamodb/src/convertToAttr.ts#L151-L164).

It fails if the number is not an integer.

```
import {marshall} from "@aws-sdk/util-dynamodb"

marshall({num: Number.MAX_SAFE_INTEGER * 1.1})

# Number 9907919180215090 is greater than Number.MAX_SAFE_INTEGER. Use BigInt.

marshall({num: 1.1e16})

# Number 11000000000000000 is greater than Number.MAX_SAFE_INTEGER. Use BigInt.
```

The second problem is an extension of this implementation. DynamoDB is limited to [38 digits of precision](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html).

```
import {marshall} from "@aws-sdk/util-dynamodb"
import {DynamoDB} from "@aws-sdk/client-dynamodb"

// not a minimal working example. sorry
const client = new DyanmoDB({})
const updateCommand = new UpdateItemCommand({
    TableName: "TABLE",
    Key: {key:{"S":"key"}},
    UpdateExpression: "set val = :val1",
    ExpressionAttributeValues: marshal({val1: BigInt(1e39)}),
    ReturnValues: "ALL_NEW",
})
const updateResult = await this.ddbClient.send(updateCommand)

# throws
# ValidationException: ExpressionAttributeValues contains invalid value:
#     DynamoDB only supports precision up to 38 digits for key :val1
```

### Observed Behavior

errors as documented above.

### Expected Behavior

I expect to be able to use marshall to save valid DynamoDB floating point numbers.

### Possible Solution

* Add a option flag into `marshall` that bypasses the Number constraint check. Such an option could be called `allowFloats`.
* Use `num.toExponential()` when the number is outside the MAX_SAFE_INTEGER bounds.

**Comment by kuhe** [comment] 2023-10-27 17:47
closing as duplicate of https://github.com/aws/aws-sdk-js-v3/issues/5363

we'll provide a general fix for using large numbers, float or int, in lib-dynamodb

**Closed by kuhe** 2023-10-27 17:47 UTC
Labels: bug, needs-triage
