### ISSUE TITLE
Amazon Connect client fails to parse error body when Connect API returns a non-JSON formatted string as the body.

### ISSUE THREAD

**Issue by PritamSangani** [aws/aws-sdk-js-v3#4256] opened 2022-12-05 18:47 UTC
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When Amazon Connect API returns a non-JSON string as the body of a non-200 status code response, the client fails to parse the body as it is not a json-parseable string. 

The line of code that does this is in a generated file here: https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-connect/src/protocols/Aws_restJson1.ts#L17699. This ends up throwing an error something like: `Unexpected token I in JSON at position 0` thus making it difficult to debug any errors that have been returned as non-JSON strings from the API.

### SDK version number

@aws-sdk/connect@3.223.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node v16.15.1 

### Reproduction Steps

By debugging the code, we could see that this particular code returns `InvalidRequestException: Invalid reference passed, check input reference` as the error body because the CreatedDate reference was not an epoch timestamp.

```js
const client = new ConnectClient({});
const commandInput = {
    InstanceId: "[instance-id]",
    ContactFlowId: "[contact-flow-id]",
    Name: "Test",
    Description: "description",
    References: {
      CreatedDate: {
         Value: "2017-05-20T09:34:44.000Z",
         Type: "DATE"
      }
    }
  }
 await client.send(new StartTaskContactCommand(commandInput))

```
This returns `Unexpected token I in JSON at position 0` as the error.

### Observed Behavior

Details in reproduction section above.

### Expected Behavior

The client should return the error string returned from the api instead of failing to parse the body as json.

**Comment by yenfryherrerafeliz** [comment] 2023-01-05 22:32
Hi @PritamSangani, thanks for opening this issue. I can confirm this is a bug. I will mark this issue to be reviewed so we can address it further.

- Steps to reproduce:
```js
import {ConnectClient, StartTaskContactCommand} from "@aws-sdk/client-connect";
const client = new ConnectClient({
    region: 'us-east-1'
});
const commandInput = {
    InstanceId: "INSTANCE-ID",
    ContactFlowId: "[contact-flow-id]",
    Name: "Test",
    Description: "description",
    References: {
        CreatedDate: {
            Value: "2017-05-20T09:34:44.000Z",
            Type: "DATE"
        }
    }
}
await client.send(new StartTaskContactCommand(commandInput))

```
Thanks!

**Comment by yenfryherrerafeliz** [comment] 2023-01-06 02:54
Hi @PritamSangani, seems like the issue is coming from the service api response. Basically, the response gotten from the service API is in a format that is unexpected by the SDK. I have opened a ticket with the correspondent team and I will inform you since I get more updates regarding.

Thanks!

**Comment by kuhe** [comment] 2023-01-06 22:37
Response using AWS CLIv2

```
> aws connect start-task-contact --instance-id "xx" --name "xx"
```

```
An error occurred (InvalidRequestException) when calling the StartTaskContact operation: InvalidRequestException: Contact flow missing
```

Response using AWS SDK JSv3

```
{
  statusCode: 400,
  headers: {
    date: 'Fri, 06 Jan 2023 22:36:45 GMT',
    'content-type': 'application/json',
    'content-length': '72',
    connection: 'keep-alive',
    'x-amzn-requestid': 'df9bf784-1138-4b47-b6e7-83697b0f0c86',
    'access-control-allow-origin': '*',
    'x-amzn-errortype': 'InvalidRequestException',
    'x-amz-apigw-id': 'eV5TpFbooAMFqEQ=',
    'x-amzn-trace-id': 'Root=1-63b8a27d-54e98a5e1b88dbbf2fcc813f'
  },
  body: 'InvalidRequestException: Invalid reference passed, check input reference'
}
```

**Comment by trivikr** [comment] 2023-02-13 21:29
A solution discussed was to attempt parsing response as per the format, i.e. JSON/XML etc.
But if it fails, fallback to surfacing the data as string to the user.

**Comment by trivikr** [comment] 2023-02-13 21:35
> But if it fails, fallback to surfacing the data as string to the user.

This suggestion needs to be discussed with @aws/smithy before implementing in JS SDK v3.

**Comment by kuhe** [comment] 2023-03-30 20:25
Check if there might be a `$response` field hidden on the error object. Possibly related: https://github.com/aws/aws-sdk-js-v3/pull/4592

**Comment by Solomon-m** [comment] 2023-09-05 08:34
Hello @yenfryherrerafeliz 
Good day. We are also facing this issue on startTaskcommand. 
Is there any update or suggestion to fix this issue would be great.

**Comment by trivikr** [comment] 2023-10-11 16:21
> I have opened a ticket with the correspondent team and I will inform you since I get more updates regarding.

The issue was fixed by service team on 09/20.

It's no longer reproducible, as the service returns a JSON response which is parsed correctly by the SDK.

Test code:
```js
import {
  ConnectClient,
  StartTaskContactCommand,
} from "@aws-sdk/client-connect";

const client = new ConnectClient({
  region: "us-east-1",
});
const commandInput = {
  InstanceId: "i-0e51819944eb11515",
  ContactFlowId: "[contact-flow-id]",
  Name: "Test",
  Description: "description",
  References: {
    CreatedDate: {
      Value: "2017-05-20T09:34:44.000Z",
      Type: "DATE",
    },
  },
};

try {
  await client.send(new StartTaskContactCommand(commandInput));
} catch (error) {
  console.error({ error });
}
```

Response:
```console
{
  error: InvalidRequestException: Invalid reference passed, check input reference
      at de_InvalidRequestExceptionRes (/Users/trivikr/workspace/test/node_modules/@aws-sdk/client-connect/dist-cjs/protocols/Aws_restJson1.js:14709:23)
      at de_StartTaskContactCommandError (/Users/trivikr/workspace/test/node_modules/@aws-sdk/client-connect/dist-cjs/protocols/Aws_restJson1.js:12336:25)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /Users/trivikr/workspace/test/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
      at async /Users/trivikr/workspace/test/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
      at async /Users/trivikr/workspace/test/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
      at async /Users/trivikr/workspace/test/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
      at async file:///Users/trivikr/workspace/test/index.mjs:23:3 {
    '$fault': 'client',
    '$metadata': {
      httpStatusCode: 400,
      requestId: '7f2faf00-12e8-4e75-a314-663faca08ce4',
      extendedRequestId: undefined,
      cfId: undefined,
      attempts: 1,
      totalRetryDelay: 0
    }
  }
}
```

**Closed by trivikr** 2023-10-11 16:21 UTC
Labels: service-api, bug, needs-review, p1
