### ISSUE TITLE
PutBucketLifecycleConfigurationCommand generates XML inconsistent with v2 API

### ISSUE THREAD

**Issue by turneand** [aws/aws-sdk-js-v3#2064] opened 2021-02-22 12:57 UTC
## Describe the bug
Unable to add Lifecycle configuration to a bucket using the v3 API, which works with the v2 API.  Where the difference is in the XML generated from the library.

## Your environment
EMC ECS 3.3 Environment

#### SDK version number
`@aws-sdk/client-s3@3.6.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`
$ node -v
v14.15.1

## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.

```
import { CreateBucketCommand, PutBucketLifecycleConfigurationCommand, S3 } from "@aws-sdk/client-s3";

const s3 = new S3({
  credentials: {
    accessKeyId: "...",
    secretAccessKey: "...",
  },
  endpoint: "...",
  forcePathStyle: true,
  region: "us-east-1"
});

const run = async() => {
  try {
    //await s3.send(new CreateBucketCommand({ "andy-tst1" }));
    await s3.send(new PutBucketLifecycleConfigurationCommand({
      Bucket: "andy-tst1",
      LifecycleConfiguration: {
        Rules: [
          {
            Expiration: {
              Days: 7,
            },
            Filter: {
              Prefix: "",
            },
            Status: "Enabled",
          }
        ]
      }
    }));
  } catch (err) {
    console.log(err);
  }
};
run();
```

#### Observed behavior
When adding the lifecycle configuration we get presented with the error:
```
MalformedXML: This happens when the user sends a malformed xml (xml that doesn't conform to the published xsd) for the configuration. The error message is, "The XML you provided was not well-formed or did not validate against our published schema."
```

Debugging the application locally, by putting break points in `Aws_restXml#serializeAws_restXmlPutBucketLifecycleConfigurationCommand`, we can see the XML sent over the wire is:
```
<?xml version="1.0" encoding="UTF-8"?><BucketLifecycleConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Rule><Expiration><Days>7</Days></Expiration><Filter><Prefix></Prefix></Filter><Status>Enabled</Status></Rule></BucketLifecycleConfiguration>
```

#### Expected behavior
We expect the lifecycle configuration to be added successfuly without throwing an error.

With the XML consistent with that generated in the V2 API (base node is `LifecycleConfiguration`) and as per the examples on https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-configuration-examples.html and the API https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketLifecycleConfiguration.html

## Additional context
Originally raised as PR #1999, but I understand this was done in the wrong location, and was asked to create a bug issue for it.
(separate note, I have raised a PR to fix some documentation links, but wondered if it's possible to put a disclaimer in the top of the generated code)

Patching the application locally as per #1999 resolves the issue, where the base node is corrected.

Switching back to the aws sdk v2 library also resolves the issue.

We do use EMC ECS 3.3 rather than AWS, but as far as I understand the APIs are mostly compatible, particularly for these basic calls.

**Comment by ajredniwja** [comment] 2021-05-28 01:40
Duplicate of https://github.com/aws/aws-sdk-js-v3/issues/2140, will close this issue, will track with https://github.com/aws/aws-sdk-js-v3/issues/2140.

**Closed by ajredniwja** 2021-05-28 01:40 UTC
Labels: bug, needs-triage
