### ISSUE TITLE
Error: Cannot find module '@aws-sdk/client-s3'

### ISSUE THREAD

**Issue by Edweis** [aws/aws-sdk-js-v3#2063] opened 2021-02-22 03:53 UTC
## Describe the bug
When running code in a lambda **without** having the library `@aws-sdk/client-s3` bundled, the code cannot find `@aws-sdk/client-s3`

## Your environment
Lambda NodeJs 12.xx

#### SDK version number
`@aws-sdk/client-s3@3.4.1`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
NodeJs 12.xx

## Steps to reproduce
Push any code in a lambda that imports `@aws-sdk/client-s3`, without adding the library

#### Observed behavior
Code crashes

#### Expected behavior
According to [doc](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html), the lambda should be shipped with AWS libraries. It works well for [aws-sdk v2](https://www.npmjs.com/package/aws-sdk), it does not for this v3.

**Comment by alexforsyth** [comment] 2021-02-22 15:03
This document is the [lambda runtimes](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html). Not the SDK support. For the present, lambda doesn't ship with JS SDK v3. Please bundle it.

The lambda team is working on including it by defautl, we're also working on a better experience around this internally. I don't have anything to share yet though!

Closing this as it should already be mentioned in our documentation and this is not a bug.

**Closed by alexforsyth** 2021-02-22 15:03 UTC
Labels: bug, needs-triage
