### ISSUE TITLE
TypeError when creating new CognitoIdentityClient

### ISSUE THREAD

**Issue by jzybert** [aws/aws-sdk-js-v3#2582] opened 2021-07-14 16:46 UTC
## Describe the bug
I am trying to create an S3Client object in my NodeJS service that will use credentials from my Cognito Identity Pool. I've followed the tutorial here: https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/loading-browser-credentials-cognito.html. However, when I run that code, I see `TypeError: Object(...) is not a function`.

It comes from the `new CognitoIdentityClient({region: REGION})` line.

The stack trace:
```
TypeError: Object(...) is not a function
    at defaultProvider (...)
    at Object.credentialDefaultProvider (...)
    at resolveAwsAuthConfig (...)
    at new CognitoIdentityClient (...)
```

## Your environment
macOS Catalina v10.15.7, MacBook Pro (16-inch, 2019)

Running this inside the WebStorm IDE from JetBrains.

#### SDK version number
```
"@aws-sdk/client-cognito-identity": "^3.20.0",
"@aws-sdk/client-s3": "^3.20.0",
"@aws-sdk/credential-provider-cognito-identity": "^3.20.0",
````

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`
```
node -v
v12.19.1
```

## Steps to reproduce
```
const {S3Client} = require("@aws-sdk/client-s3");
const {CognitoIdentityClient} = require("@aws-sdk/client-cognito-identity");
const {fromCognitoIdentityPool} = require("@aws-sdk/credential-provider-cognito-identity");

// AWS Constants
const REGION = 'us-east-1';
const IDENTITY_POOL_ID = 'IDENTITY_POOL_ID'; // removing actual ID
const USER_POOL_ID = 'USER_POOL_ID'; //removing actual ID
const COGNITO_ID = `cognito-idp.${REGION}.amazonaws.com/${USER_POOL_ID}`;

export async function listS3Files(token) {
    try {
        const loginData = {
            [COGNITO_ID]: token
        };
        const s3Client = new S3Client({
            region: REGION,
            credentials: fromCognitoIdentityPool({
                client: new CognitoIdentityClient({region: REGION}),
                identityPoolId: IDENTITY_POOL_ID,
                logins: {
                    ...loginData
                }
            })
        });
    } catch (error) {
        console.log(error);
        throw error;
    }
}

```

#### Observed behavior
Trying to create an S3Client using the v3 tutorial results in a TypeError being thrown when the CognitoIdentityClient is created.

#### Expected behavior
No TypeError should be thrown. I should be able to create the S3Client with no issues.

**Comment by AllanZhengYP** [comment] 2021-07-16 21:08
Hi @jzybert 

I cannot reproduce the issue, can you point out which line in source code is throwing the error? It'll be the helpful for us if you can create a reproduction repo so we can reproduce the issue from clean slate.

**Comment by AllanZhengYP** [comment] 2021-07-19 16:58
Per offline discussion, this issue is dupilcated to https://github.com/aws/aws-sdk-js-v3/issues/2587. I will close this report and track the issue on the other ticket.

**Closed by AllanZhengYP** 2021-07-19 16:58 UTC
Labels: bug, needs-triage
