### ISSUE TITLE
Issue with CloudWatch MetricDatum Unit types

### ISSUE THREAD

**Issue by EHadoux** [aws/aws-sdk-js-v3#2877] opened 2021-10-06 22:18 UTC
## Describe the bug
When using `PutMetricDataCommand` the field `MetricData` expects a `MetricDatum[]`. The `Unit` field of `MetricDatum` has in theory the type `StandardUnit | string`. It looks like it gets coerced to string only because `StardardUnit` is a union of string. We lose the autocompletion of the possible values for the unit. See https://github.com/aws/aws-sdk-js-v3/blob/e0025cddbba244a41ddf1fd1adb761142e15c22d/clients/client-cloudwatch/src/models/models_0.ts#L3502

#### SDK version number
`@aws-sdk/client-cloudwatch@3.35.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v16.9.1

## Steps to reproduce
```typescript
import { PutMetricDataCommand } from '@aws-sdk/client-cloudwatch';

const cmd = new PutMetricDataCommand({
  MetricData: [{
    Unit: 'Count' // of type string so no autocompletion
  }]
});
```

#### Observed behavior
The `Unit` field is of type string, preventing autocompletion.

#### Expected behavior
The `Unit` field should be of type `StandardUnit` to allow for autocompletion.

#### Screenshots
![image](https://user-images.githubusercontent.com/1655646/136291204-fcbadc7d-db50-408d-b7e4-a915540c8f29.png)

## Additional context
Using Typescript v4.4.3

**Comment by vudh1** [comment] 2021-11-30 18:37
Hi @EHadoux, I am not able to reproduce this with the code you gave above. Can you send a reproducible code/log so we can investigate more?

**Comment by EHadoux** [comment] 2021-12-01 09:41
Hi @vudh1, by not being able to reproduce, do you mean you can get some autocompletion on the ```Unit``` field? 
The easiest way to reproduce doesn't even use external code. With this lib installed, go to `node_modules/@aws-sdk/client-cloudwatch/dist-types/models/model_0.d.ts` (which seems to be what's loaded up to get the types from), and hover over the `Unit` field (with VSCode for instance) in the `MetricDatum` interface. Despite being of type `StandardUnit | string`; the former is a string union as well, so the whole field gets coerced to string, removing any autocompletion for the field later down the line.
It is located here https://github.com/aws/aws-sdk-js-v3/blob/f510f818b0c7eb1b3004f305cc5c042dba63a9a6/clients/client-cloudwatch/src/models/models_0.ts#L3764

So the two questions are: 
1. can you get the right type + the autocompletion on your end for this field? (if yes then it's a VSCode bug and I'll report it there)
2. Can the `Unit` field be of a different value than a `StandardUnit`? (if no then it might be better to define it as just `StandardUnit` and not `StandardUnit | string`

It looks like this type union is being used in different places (DataPoint, MetricAlarm, etc.) so if it needs to be fixed, it should be in all these places as well.

**Comment by kuhe** [comment] 2023-10-18 14:50
enums were closed in https://github.com/aws/aws-sdk-js-v3/pull/5356

**Closed by kuhe** 2023-10-18 14:50 UTC
Labels: bug, p3
