### ISSUE TITLE
AWS SDK JS v3 Preinstalled on Lambda

### ISSUE THREAD

**Issue by fishcharlie** [aws/aws-sdk-js-v3#3179] opened 2022-01-11 20:01 UTC
I'm curious what the AWS teams thoughts are on preinstalling AWS SDK JS v3 on AWS Lambda. Is this something that will ever happen?

**Comment by willfarrell** [comment] 2022-01-16 19:16
Duplicate of https://github.com/aws/aws-sdk-js-v3/issues/2149

**Closed** 2022-04-29 16:59 UTC
Labels: duplicate, feature-request
