### ISSUE TITLE
Having problem with client-transcribe-streaming

### ISSUE THREAD

**Issue by shihiancheng** [aws/aws-sdk-js-v3#1763] opened 2020-12-11 00:06 UTC
**Describe the bug**
By following the read me and build a test code. But I got the following error:
```console
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Object
```

I guess it something to do with the line:
```js
yield { AudioEvent: { AudioChunk: chunk } };
```

Could anyone help check what's wrong with my code?

**SDK version number**
```
    "@aws-sdk/client-transcribe-streaming": "^1.0.0-rc.8",
    "aws-sdk": "^2.808.0",
```

**Is the issue in the browser/Node.js/ReactNative?**
Node.js

**Details of the browser/Node.js/ReactNative version**
`v15.4.0`

**To Reproduce (observed behavior)**
```javascript
const { TranscribeStreamingClient, StartStreamTranscriptionCommand } = require("@aws-sdk/client-transcribe-streaming");
const { PassThrough } = require("stream");
const { Readable } = require("stream");
var fs= require("fs");
var audioSource = fs.createReadStream("./speech.raw",{ highWaterMark: 512 });
var writeStream = fs.createWriteStream('./output.txt');
if(!audioSource){
    console.log("fail to open audioSource");
}
const client = new TranscribeStreamingClient();

const audioStream = async function* () {
  for await (const chunk of audioSource) {
     yield { AudioEvent: { AudioChunk: chunk } };
  }
};


const command = new StartStreamTranscriptionCommand({
  // The language code for the input audio. Valid values are en-GB, en-US, es-US, fr-CA, and fr-FR
  LanguageCode: "en-US",
  // The encoding used for the input audio. The only valid value is pcm.
  MediaEncoding: "pcm",
  // The sample rate of the input audio in Hertz. We suggest that you use 8000 Hz for low-quality audio and 16000 Hz for
  // high-quality audio. The sample rate must match the sample rate in the audio file.
  MediaSampleRateHertz: 16000,
  AudioStream: audioStream(),
});

async function go()
{
    try {
      const response = await client.send(command);
      //  await handleResponse(response);
      const transcriptsStream = Readable.from(response.TranscriptResultStream);
      transcriptsStream.pipe(writeStream);

    } catch (e) {
        console.log("e=%j",e);
      if (e.name === "InternalFailureException") {
        /* handle InternalFailureException */
      } else if (e.name === "ConflictException") {
        /* handle ConflictException */
      }
    } finally {
      /* clean resources like input stream */
    }
}

go();
```

**Expected behavior**
Return the transcribe result.

**Screenshots**
none

**Additional context**

**Comment by loretoparisi** [comment] 2021-02-24 11:08
@shihiancheng did you solved your issue? I'm getting a similar error from your code.

**Comment by Y2KForever** [comment] 2021-03-01 14:23
Changing the `MediaSampleRateHertz ` to 8000 from 16000 removes the error for me. But the stream is still empty for some reason.

**Comment by ajredniwja** [comment] 2021-03-29 23:14
@loretoparisi Can you check if this is still a persisting issue with the latest version of the SDK? 
I can investigate further if it is.

**Comment by Y2KForever** [comment] 2021-03-30 13:12
@ajredniwja I tested the sample code above with both a 16000 hz and a 8000 hz file, and I'm still getting the same typerror.

**Comment by ajredniwja** [comment] 2021-03-30 23:27
@Y2KForever can you try doing:

```JavaScript
async function* audioSource() {
    const chunkSize = 10 * 1000;
    const fileBuf = fs.readFileSync('path/to/audio/source');
    let index = 0;
    let i = 0;
    while(index < fileBuf.length) {
        const chunk = fileBuf.slice(index, Math.min(index + chunkSize, fileBuf.byteLength));
        await wait(300);
        yield chunk;
        index += chunkSize;
    }
}
```

and then: 
```
 async function * audioStream() {
        for await(const chunk of audioSource()) {
            yield {AudioEvent: {AudioChunk: chunk}}
        }
    }
```

**Comment by Y2KForever** [comment] 2021-04-07 12:19
> 
> 
> @Y2KForever can you try doing:
> 
> ```js
> function wait(time) {
>     return new Promise(resolve => {
>         setTimeout(resolve, time);
>     })
> }
> 
> 
> async function* audioSource() {
>     const chunkSize = 10 * 1000;
>     const fileBuf = fs.readFileSync('path/to/audio/source');
>     let index = 0;
>     let i = 0;
>     while(index < fileBuf.length) {
>         const chunk = fileBuf.slice(index, Math.min(index + chunkSize, fileBuf.byteLength));
>         await wait(300);
>         yield chunk;
>         index += chunkSize;
>     }
> }
> ```
> 
> and then:
> 
> ```
>  async function * audioStream() {
>         for await(const chunk of audioSource()) {
>             yield {AudioEvent: {AudioChunk: chunk}}
>         }
>     }
> ```

Sorry for a late reply, but I did try your approach with the former mentioned code like this:

```js
const {
  TranscribeStreamingClient,
  StartStreamTranscriptionCommand,
} = require("@aws-sdk/client-transcribe-streaming");

const { PassThrough } = require("stream");
const { Readable } = require("stream");
var fs = require("fs");
var writeStream = fs.createWriteStream("./output.txt");

function wait(time) {
  return new Promise((resolve) => {
    setTimeout(resolve, time);
  });
}

async function* audioSource() {
  const chunkSize = 10 * 1000;
  const fileBuf = fs.readFileSync("sourcefile.raw");
  let index = 0;
  let i = 0;
  while (index < fileBuf.length) {
    const chunk = fileBuf.slice(
      index,
      Math.min(index + chunkSize, fileBuf.byteLength)
    );
    await wait(300);
    yield chunk;
    index += chunkSize;
  }
}


if (!audioSource) {
  console.log("fail to open audioSource");
}

const client = new TranscribeStreamingClient();

async function* audioStream() {
  for await (const chunk of audioSource()) {
    yield { AudioEvent: { AudioChunk: chunk } };
  }
}

const command = new StartStreamTranscriptionCommand({
  LanguageCode: "en-US",
  MediaEncoding: "pcm",
  MediaSampleRateHertz: 16000,
  AudioStream: audioStream(),
});

async function go() {
  try {
    const response = await client.send(command);
    //  await handleResponse(response);
    const transcriptsStream = Readable.from(response.TranscriptResultStream);
    transcriptsStream.pipe(writeStream);
  } catch (e) {
    console.log("e=%j", e);
    if (e.name === "InternalFailureException") {
    } else if (e.name === "ConflictException") {
    }
  } finally {
  }
}

go();
``` 

And I would still get the same error.
I tried using raw, mp3, and wav files but the error never changed. Same for converting the audiofile(s) to 16khz to 8khz.

**Comment by ajredniwja** [comment] 2021-04-08 23:04
@Y2KForever were you able to use the latest versions? Because I was not able to reproduce the error when I used the latest version.

**Comment by Y2KForever** [comment] 2021-04-09 09:03
@ajredniwja I did try with 3.11 and still got the same error.

Could the issue be the sound-file perhaps?
Are you able to share the file you tested with?

**Comment by ajredniwja** [comment] 2021-04-09 19:06
> @ajredniwja I did try with 3.11 and still got the same error.
> 
> Could the issue be the sound-file perhaps?
> Are you able to share the file you tested with?

I doubt if that might be the reason. 
Is it possible for you to set up a repo with all you configuration and code?

**Comment by VAL-MH97** [comment] 2021-04-12 12:48
I´m having the same Issue. Can Anybody provide a link to a working example in general? Cant seem to find anything :(

**Comment by ajredniwja** [comment] 2021-06-02 23:04
@VAL-MH97 @Y2KForever 

<details>
<summary> I used this code again: </summary>

```JavaScript
const fs = require('fs');
const { TranscribeStreamingClient, StartMedicalStreamTranscriptionCommand, StartStreamTranscriptionCommand, Specialty, Type } = require('@aws-sdk/client-transcribe-streaming');

function wait(time) {
    return new Promise(resolve => {
        setTimeout(resolve, time);
    })
}

async function* audioSource() {
    const chunkSize = 10 * 1000;
    const fileBuf = fs.readFileSync('./testFile.wav');
    let index = 0;
    let i = 0;
    while(index < fileBuf.length) {
    // while(index < chunkSize * 60) {
        const chunk = fileBuf.slice(index, Math.min(index + chunkSize, fileBuf.byteLength));
        await wait(300);
        yield chunk;
        index += chunkSize;
    }
}

(async () => {
    console.log(`***start: [${new Date()}]`);
    async function * audioStream() {
        for await(const chunk of audioSource()) {
            yield {AudioEvent: {AudioChunk: chunk}}
        }
    }
    const client = new TranscribeStreamingClient({region: "us-west-2"});

    const command = new StartStreamTranscriptionCommand({
        LanguageCode: 'en-US',
        MediaSampleRateHertz: 16000,
        MediaEncoding: 'pcm',
        AudioStream: audioStream(),
        // Specialty: Specialty.CARDIOLOGY,
        // Type: Type.CONVERSATION
    });
    try {
        const data = await client.send(command, {sessionTimeout: 2000});
        // console.log(data.TranscriptResultStream)
        for await (const event of data.TranscriptResultStream) {
            if(event.TranscriptEvent) {
                const results = event.TranscriptEvent.Transcript.Results;
                results.map(result => {
                    (result.Alternatives || []).map(alternative => {
                        const str = alternative.Items.map(item => item.Content).join(' ');
                        console.log(str)
                    })
                })
            }
        }
        console.log('DONE', data);
        client.destroy();
    } catch(e) {
        console.log('ERROR: ', e);
        process.exit(1);
    }
})()
```
</details>

I can also share the sample wav file, if it doesnt work.

**Comment by ajredniwja** [comment] 2021-06-02 23:06
Have the sample file here https://github.com/ajredniwja/transcribe-example

**Comment by Y2KForever** [comment] 2021-06-04 09:38
> 
> 
> @VAL-MH97 @Y2KForever
> I used this code again:
> 
> I can also share the sample wav file, if it doesnt work.

Tested, thank you for a working example! :)

**Comment by ajredniwja** [comment] 2021-06-10 23:55
Also officially here a complete app. 

https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/javascriptv3/example_code/cross-services/transcribe-streaming-app

Closing this issue now, please reach out if you have any other questions.

**Closed by ajredniwja** 2021-06-10 23:55 UTC
Labels: documentation

**Comment by loretoparisi** [comment] 2021-06-11 06:08
If it can help, this is my solution, that makes use of hints suggested here

https://github.com/loretoparisi/aws-transcribe-streaming-node-example
