### ISSUE TITLE
cloudwatch-logs is not aware of `ThrottlingException`

### ISSUE THREAD

**Issue by mrgrain** [aws/aws-sdk-js-v3#5140] opened 2023-08-24 10:52 UTC
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

According to the code and docs, commands in the `cloudwatch-logs` package do not throw a `ThrottlingException`.
<img width="814" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/379814/bed3f88b-0ee2-4ee0-a285-3ea0d6eddea0">
Evidence 1: Other packages list `ThrottlingException` here.

<img width="574" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/379814/ba693160-0c1c-4727-bdd0-6cc66d2c1594">
Evidence 2: Other packages include a `ThrottlingException` class.

However in reality `cloudwatch-logs` commands can throw a `ThrottlingException`:

<img width="1188" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/379814/a3c17ef9-5d0a-4b11-bbec-d7c309704be6">
Evidence 3: The `createLogGroupSafe` function is a thin wrapper around `CreateLogGroupCommand`.

This is an issue because I cannot catch a `ThrottlingException` from this package in the recommended way `if (error instanceof Logs.ThrottlingException) { /* ... */ }` because the package does not export the exception type.

### SDK version number

@aws-sdk/client-cloudwatch-logs@3.398.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

Lambda Runtime nodejs18.x 

### Reproduction Steps

```ts
import { CloudWatchLogsClient, CreateLogGroupCommand } from "@aws-sdk/client-cloudwatch-logs";

const numberOfLogGroups = 200;
const random = (Math.random() + 1).toString(36).substring(7);
const logGroupNames = [...Array(numberOfLogGroups).keys()].map(i => `/reproduction/${random}/${i}`);

const client = new CloudWatchLogsClient({
    maxAttempts: 1 // makes it more likely to hit the error
});

logGroupNames.forEach(async (logGroupName) => {
    try {
        const params = { logGroupName };
        const command = new CreateLogGroupCommand(params);
        await client.send(command);
    } catch (error: any) {
        if (error instanceof ThrottlingException) { // ThrottlingException class does not exist
        // if (error.name === 'ThrottlingException') { // This does work
            console.log("CAUGHT a wild ThrottlingException")
            return;
        }

        throw error;
    }
});
```

### Observed Behavior

There is no class/type to use with `instanceof`

### Expected Behavior

There is a class/type to use with `instanceof`
JSDocs and Doc website state that a ThrottlingException might be thrown

**Comment by RanVaknin** [comment] 2023-08-24 22:07
Hi @mrgrain ,

Thanks for opening this thread. 
What you are witnessing is a discrepancy between Server behavior and API model definition.

You can take a look at the [internal model](https://github.com/aws/aws-sdk-js-v3/blob/main/codegen/sdk-codegen/aws-models/cloudwatch-logs.json#L330-L348) and witness that a `ThrottlingException` is in fact not modeled. 

If you didn't know, all the AWS SDKs are code generated from the internal models defined by service teams. So simply put, if a service doesn't specify a certain error in their API model, it wouldn't exist in the SDKs. 

Since `ThrottlingException` is sometimes considered a base exception and not every service explicitly models it, it does exist in the smithy-typscript package. So I think you can actually import it like so:

```js
import { CloudWatchLogsClient, CreateLogGroupCommand } from "@aws-sdk/client-cloudwatch-logs";
import { ThrottlingException } from '@smithy/service-error-classification';

const numberOfLogGroups = 200;
const random = (Math.random() + 1).toString(36).substring(7);
const logGroupNames = [...Array(numberOfLogGroups).keys()].map(i => `/reproduction/${random}/${i}`);

const client = new CloudWatchLogsClient({
    maxAttempts: 1 // makes it more likely to hit the error
});

logGroupNames.forEach(async (logGroupName) => {
    try {
        const params = { logGroupName };
        const command = new CreateLogGroupCommand(params);
        await client.send(command);
    } catch (error: any) {
        if (error instanceof ThrottlingException) { 
            console.log("CAUGHT a wild ThrottlingException")
            return;
        }

        throw error;
    }
});
```

At any rate, I think its safe to error handle this specific error with `.name` instance of `instanceof`. 
If you feel inclined, you can create an internal feature reqeust via the AWS console and ask to be routed to the cloudwatch-logs service team.

Thanks again,
Ran~

**Comment by rix0rrr** [comment] 2023-09-04 09:28
Hi @RanVaknin,

I believe that you have a reason for why you have defined the behavior as it currently is. The problem is that now there is a discrepancy between "modeled exception handling" and "unmodeled exception handling", that didn't need to be there. The SDK v2 didn't have a bimodal error handling pattern, but the SDK v3 is now [recommending this as a best practice](https://aws.amazon.com/blogs/developer/service-error-handling-modular-aws-sdk-js/).

I understand that your model is more pure, but it is putting a burden on your users that didn't need to be there. That can't be your intention, can it? 

Example:

## SDKv2

```ts
try {
  new Logs().createLogGroup({ ... });
} catch(e) {
  switch (e.code) {
    // Handling all exceptions looks exactly the same, regardless of what the service team did

    case 'ResourceAlreadyExistsException': 
      // Handle  ResourceAlreadyExistsException
      break;
    case 'ThrottlingException':
      // Handle  ResourceAlreadyExistsException
      break; 
    default: 
      // ...
      break;
  }
}
```

## SDKv3

```ts
try {
  new CloudWatchLogsClient().send(new CreateLogGroupCommand({ ... });
} catch(e) {
  // Handle some exceptions with instanceof, others with a name check

  if (e instanceof ResourceAlreadyExistsException) {
      // Handle  ResourceAlreadyExistsException
  } else if (e.name === 'ResourceAlreadyExistsException') {
      // Handle  ResourceAlreadyExistsException
  } else {
     // ...
  }
}
```

Where I used to be able to [just rely on the Errors section of the AWS API documentation](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_CreateLogGroup.html#API_CreateLogGroup_Errors) to get my code right, I now need to look both at the Errors section, as well as the service model to guess what code I need to write.

Would you not agree this is a more brittle situation? 

I think your response to this is: "the service team should do a better job of describing all their errors". But isn't a design in which you do NOT have to rely on the service team's effort a strictly better solution?

**Comment by albertodiazdorado** [comment] 2023-11-03 16:40
I think that @rix0rrr is right. I think that nothing will change in the SDK.

I have already installed `@smithy/service-error-classification` and I am using it, since I have no hope of any other solution.

Peace.

**Comment by RanVaknin** [comment] 2024-07-05 21:57
Hi there,

I understand the frustration here. The core issue is that certain services are returning un-modeled exception, therefore you cannot use `instanceof` on those. To circumvent that you can use `.name` which is not the recommended way, but it should safe. 

The SDK team cannot introduce new error types to the SDK client since the SDK is code generated from the model of that upstream AWS service the SDK interacts with. This is what ensures type safety. Unless the service team adds `ThrottlingException` to their API model, your only recourse in this case is to rely on the raw string.

Since this is not actionable by the SDK team, Im going to go ahead and close this.
Thanks,
Ran~

**Closed by RanVaknin** 2024-07-05 21:57 UTC
Labels: service-api, bug, workaround-available, p3
