### ISSUE TITLE
Urgent: InvalidIdentityTokenException with AWS SDK in Version 3.503.0 causes immediate failure (govcloud)

### ISSUE THREAD

**Issue by jonathon-mcnabb** [aws/aws-sdk-js-v3#5749] opened 2024-01-30 22:00 UTC
### Checkboxes for prior research

- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Urgent: Services cannot connect to AWS

InvalidIdentityTokenException with AWS SDK in Version 3.503.0

Environment:

    AWS SDK Version: 3.503.0
    Services we use that are affected: Amazon S3, Amazon DynamoDB (likely affects others)

Description:
After upgrading to @aws-sdk/client-s3 and @aws-sdk/client-dynamodb  version 3.503.0, we are encountering an InvalidIdentityTokenException when attempting to access S3 and DynamoDB services. The same issue is not observed in previous versions of the package. No changes were made to the source code other than updating the package version.

Reproduction Steps:

    Upgrade @aws-sdk/client-s3 to version 3.503.0.
    Upgrade @aws-sdk/client-dynamodb to version 3.503.0.
    Attempt to perform standard operations on S3 and DynamoDB.
    Observe the InvalidIdentityTokenException.

Expected Behavior:
Operations on S3 and DynamoDB should succeed without identity token issues, as they did in previous versions of the SDK.

Actual Behavior:
Received an error with the following details:

    Error Name: InvalidIdentityTokenException
    Fault: client
    HTTP Status Code: 400
    Request ID: [REDACTED]
    Error Type: Sender
    Error Code: InvalidIdentityToken
    Error Message: No OpenIDConnect provider found in your account for [REDACTED URL]

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.20.2

### Reproduction Steps

"dependencies": {
    "@aws-sdk/client-s3": "^3.501.0",
    "@aws-sdk/client-dynamodb": "^3.501.0",
  }

### Observed Behavior

When connecting to AWS services, the following error is seen.

Received an error with the following details:

    Error Name: InvalidIdentityTokenException
    Fault: client
    HTTP Status Code: 400
    Request ID: [REDACTED]
    Error Type: Sender
    Error Code: InvalidIdentityToken
    Error Message: No OpenIDConnect provider found in your account for [REDACTED URL]

### Expected Behavior

I expect to be able to utilize AWS SDKs to connect to S3 and DynamoDB.

**Comment by jonathon-mcnabb** [comment] 2024-01-30 23:37
Hey @RanVaknin,

Thanks for the quick response. It looks like with the new version this issue is still occurring. 

For more context, we are running an EKS cluster with an OIDC provider.

**Comment by kuhe** [comment] 2024-01-31 01:53
@jonathon-mcnabb could you provide an example of how to initialize the SDK client, including how you get credentials?

If you are relying on the default credential chain, please confirm that.

**Comment by jonathon-mcnabb** [comment] 2024-01-31 16:23
Hey @kuhe, here's an example of a client init:

`
import { S3Client } from '@aws-sdk/client-s3';
// Create an Amazon S3 service client object.
// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-call
const s3Client: S3Client = new S3Client({ region: process.env.AWS_REGION });
export { s3Client };
`


Out stack utilizes EKS with node microservices, using an ODIC provider. The following shows what env variables are defined on the node:

AWS_STS_REGIONAL_ENDPOINTS:   regional                                                                                                                                                                       
AWS_ROLE_ARN:                 arn:aws-us-gov:iam::[REDACTED_ACCOUNT]:role/[REDACTED_ROLE]                                                                                                     
AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token

I have confirmed that a token is present at the path. 

I am not sure if I am relying on the default credential change, though this may be occurring under the hood.

**Comment by kuhe** [comment] 2024-01-31 17:03
With this type of initialization, you are using the default Node.js credential provider chain. It looks in a few different places and then it finds and uses the `AWS_ROLE_ARN` and `AWS_WEB_IDENTITY_TOKEN_FILE` variables to read a token file and then make a request with `STS::assumeRoleWithWebIdentity` to get credentials to then make the subsequent S3 requests. 

Is the region the STS request is being sent to the one that you expect?

**Comment by kuhe** [comment] 2024-01-31 19:55
Do you have the IAM identity provider in your account with the same URL as the `iss` field in your token?

The only way I seem to get `No OpenIDConnect provider found in your account for [URL]` is if I set [URL] to a provider that doesn't exist in my account.

**Comment by gilesvessey** [comment] 2024-01-31 20:56
Not to muddy up the conversation happening here, but I am facing this issue with the following credential configuration

```ini
# .aws/config
[profile target]
region = us-gov-east-1
# .aws/credentials
[default]
source_profile = target
role_arn = [MASKED]
external_id = [MASKED]
region = us-gov-east-1
[target]
aws_access_key_id = [MASKED]
aws_secret_access_key = [MASKED]
```

Python works, CLI works, Node SDK 3.501.0 works. Node SDK 3.503.0 gives me `InvalidClientTokenId: The security token included in the request is invalid.`

**Comment by kuhe** [comment] 2024-01-31 21:03
@gilesvessey could you try 3.503.1?

**Comment by jonathon-mcnabb** [comment] 2024-01-31 21:06
@kuhe, looks like they are in alignment. 

Here's the token data and the corresponding error message.

  "aud": [
    "sts.amazonaws.com"
  ],
  "exp": 1706813606,
  "iat": 1706727206,
  "iss": "https://oidc.eks.us-gov-west-1.amazonaws.com/id/[REDACTED_32_CHAR_CODE]  "kubernetes.io": {
    "namespace": "REDACTED",
    "pod": {
      "name": "REDACTED ",
      "uid": "REDACTED "
    },
    "serviceaccount": {
      "name": " REDACTED ",
      "uid": "REDACTED "
    }
  },
  "nbf": REDACTED,
  "sub": "REDACTED "
}


"message":"No OpenIDConnect provider found in your account for https://oidc.eks.us-gov-west-1.amazonaws.com/id/[REDACTED_32_CHAR_CODE]


It also looks like both my org and [gilesvessey](https://github.com/gilesvessey) are both in gov-cloud regions. Perhaps this breaking change on affects gov-cloud?

**Comment by gilesvessey** [comment] 2024-01-31 21:31
I have a fair number of AWS imports in my package file, all of which found a 3.503.1 version EXCEPT sts. So, here are some scenarios and their outcome

Test code

```js
const S3Client = require('@aws-sdk/client-s3').S3
const s3 = new S3Client({})

function test() {
  return s3.listBuckets({})
    .then(res => {
      console.log(res)
      return res
    })
}

test()
```

Latest STS package, all else pinned to 3.503.1
```json
    "@aws-sdk/client-s3": "3.503.1",
    "@aws-sdk/lib-dynamodb": "3.503.1",
    "@aws-sdk/client-dynamodb": "3.503.1",
    "@aws-sdk/util-dynamodb": "3.503.1",
    "@aws-sdk/client-sts": "^3.0.0", 
    "@aws-sdk/client-ec2": "3.503.1",
    "@aws-sdk/client-auto-scaling": "3.503.1",
    "@aws-sdk/client-ecr": "3.503.1",
    "@aws-sdk/client-ecr-public": "3.503.1",
    "@aws-sdk/client-lambda": "3.503.1",
    "@aws-sdk/client-codecommit": "3.503.1",
    "@aws-sdk/client-cloudwatch-events": "3.503.1",
    "@aws-sdk/client-cloudwatch-logs": "3.503.1",
    "@aws-sdk/credential-providers": "3.503.1",
    "@aws-sdk/client-rds": "3.503.1",
    "@aws-sdk/client-iam": "3.503.1",
    "@aws-sdk/client-codebuild": "3.503.1",
    "@aws-sdk/client-efs": "3.503.1",
    "@aws-sdk/client-elastic-load-balancing": "3.503.1",
    "@aws-sdk/client-elastic-load-balancing-v2": "3.503.1",
    "@aws-sdk/client-organizations": "3.503.1",
    "@aws-sdk/client-pricing": "3.503.1",
    "@aws-sdk/client-opensearch": "3.503.1",
    "@aws-sdk/client-ecs": "3.503.1",
    "@aws-sdk/client-sqs": "3.503.1",
    "@aws-sdk/client-ssm": "3.503.1",
    "@aws-sdk/client-cloudwatch": "3.503.1",
    "@aws-sdk/client-inspector2": "3.503.1",
```

Result 

```
node s3-test.js 
/Users/gvessey/src/giles-509/tools/node_modules/@smithy/smithy-client/dist-cjs/index.js:838
  const response = new exceptionCtor({
                   ^

InvalidClientTokenId: The security token included in the request is invalid.
    at throwDefaultError (/Users/gvessey/src/giles-509/tools/node_modules/@smithy/smithy-client/dist-cjs/index.js:838:20)
    at /Users/gvessey/src/giles-509/tools/node_modules/@smithy/smithy-client/dist-cjs/index.js:847:5
    at de_AssumeRoleCommandError (/Users/gvessey/src/giles-509/tools/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/client-sts/dist-cjs/index.js:375:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/gvessey/src/giles-509/tools/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /Users/gvessey/src/giles-509/tools/node_modules/@smithy/core/dist-cjs/index.js:165:18
    at async /Users/gvessey/src/giles-509/tools/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /Users/gvessey/src/giles-509/tools/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22
    at async Object.roleAssumer (/Users/gvessey/src/giles-509/tools/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/client-sts/dist-cjs/index.js:1516:43)
    at async /Users/gvessey/src/giles-509/tools/node_modules/@smithy/property-provider/dist-cjs/index.js:79:27 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 403,
    requestId: '56f68396-f357-48d3-aaf1-f45af4eca2f2',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Type: 'Sender',
  Code: 'InvalidClientTokenId'
}

Node.js v18.18.2
```

If I leave my package file the same, but set STS to 3.501.0, I get the same thing. If I set all of my packages to 3.501.0 however, we succeed

```
node s3-test.js 
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'MPT7SQX9XDENWSYW',
    extendedRequestId: '1l4lsiTdAMwyL0+FwrhaySPf0cjFeODCcaMWzUUGEqs+EQJ2CXMFGc3z6hVbUgIIK0/2fa8a+UE=',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Buckets: [
    { 
    .....
```

**Comment by kuhe** [comment] 2024-01-31 22:24
@gilesvessey I'm unable to reproduce this. Is the below similar to your setup? Trying to minimize it to the smallest example. I can't test in `us-gov-east-1`, but there should be no difference in this part of the AWS SDK.

my setup:

```
# config
[profile targets-default]
source_profile = default
role_arn = arn:aws:iam::...:role/AdminTestRole
```

```
# credentials
[default]
aws_access_key_id=...
aws_secret_access_key=...
aws_session_token=...
```

```js
import { STS } from "@aws-sdk/client-sts";

process.env.AWS_PROFILE = "targets-default";
process.env.AWS_REGION = "us-west-2";

const client = new STS({});
console.log(await client.getCallerIdentity({})); // httpStatusCode 200 OK, assumed-role/AdminTestRole
```

**Comment by kuhe** [comment] 2024-01-31 22:31
@jonathon-mcnabb Yes, the token's issuer will correspond to the error message. Rather, and I'm sorry if this is too obvious a question, but do you have this provider in your AWS account? It would be under 

**IAM > Identity Providers** and the name of the provider should be the same as the issuer from the token without the `https://` part if it is OIDC.

**Comment by kuhe** [comment] 2024-01-31 22:45
Did an EKS redeployment happen that would subtly change the ID value of the provider, that could cause a mismatch?

**Comment by jonathon-mcnabb** [comment] 2024-01-31 22:50
@kuhe Hmm, not that I am aware of.

I was able to test the below code in us-gov-west-1 and did not have any issues. Same result with 3.504.0. It looks like there isn't a version 3.503.* for @aws-sdk/client-sts?

import { STS } from "@aws-sdk/client-sts";

process.env.AWS_PROFILE = "test-profile";
process.env.AWS_REGION = "us-gov-west-1";

const client = new STS({});
console.log(await client.getCallerIdentity({})); // httpStatusCode 200 OK, assumed-role/AWSReservedSSO_AdministratorAccess_.......

**Comment by jonathon-mcnabb** [comment] 2024-01-31 22:52
Attempting a rebuild of our service code using version 3.504.0 of the SDK to see if that resolves anything. Will post results here soon.

**Comment by jonathon-mcnabb** [comment] 2024-01-31 22:55
@kuhe, it appears the same issue is still occurring on version 3.504.0

**Comment by kuhe** [comment] 2024-02-01 15:58
@gilesvessey let's move our discussion to https://github.com/aws/aws-sdk-js-v3/issues/5755, leave this one for updates to the original problem.

**Comment by jonathon-mcnabb** [comment] 2024-02-01 16:30
hey @kuhe,

Is there any other information I could provide that may be helpful? I would also be happy to jump on a call to dive into things a bit deeper.

let me know!

**Comment by kuhe** [comment] 2024-02-01 16:42
I would be ok with getting on a call, but I can't post any contact information in this public forum. Could you send an invite to some form of communication? If you don't want to post it here, contact the AWS SDK for JavaScript team via your AWS account manager.

**Comment by jonathon-mcnabb** [comment] 2024-02-01 18:58
@kuhe  Sounds good. I reached out to our account manager to set something up. 

In the meantime, I ran a debugger on our source code and I found a clue:

In the "/usr/src/app/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js" file, there is an "endpointParams" variable that is returned as part of the "resolveParams" function. 

When inspecting this value, it had a region set to "us-east-1". When I manually changed this value to my region "us-gov-west-1", we no longer got the "InvalidIdentityTokenException" error and the connection to AWS was successful. I have confirmed that the AWS_REGION env variable is set to us-gov-west-1.


```json
{
  UseGlobalEndpoint: false,
  UseFIPS: false,
  Endpoint: undefined,
  Region: "us-east-1",
  UseDualStack: false,
}
```

Whats interesting is that this only occurs when processing the "AssumeRoleWithWebIdenityCommand".


When we process the GetObjectCommand, this is the value of endpointParams:

```
{
  ForcePathStyle: false,
  UseArnRegion: false,
  DisableMultiRegionAccessPoints: false,
  Accelerate: false,
  DisableS3ExpressSessionAuth: false,
  UseGlobalEndpoint: false,
  UseFIPS: false,
  Endpoint: undefined,
  Region: "us-gov-west-1",
  UseDualStack: false,
  Bucket: "[REDACTED]",
  Key: "[REDACTED]",
}
```

**Comment by jonathon-mcnabb** [comment] 2024-02-01 19:04
I believe this is the source code:

https://github.com/smithy-lang/smithy-typescript/blob/280ef3a90205bfaa208fe9ddfc088a80341c5032/packages/middleware-endpoint/src/adaptors/getEndpointFromInstructions.ts#L61

**Comment by kuhe** [comment] 2024-02-01 20:02
Part of the reason for this input redundancy is that our credential providers `fromXYZ({ clientConfig: ... })` return a standalone function that can be used to retrieve credentials. It is not aware of what client it is being fed to.

For SDK initialization that isn't in the default commercial regions, I think you end up needing to configure the region in two places.

**Comment by jonathon-mcnabb** [comment] 2024-02-01 22:19
hmm, ok. It will be challenging for us to update in all of the locations this may need to occur. 

Wouldn't it be expected that the AWS_REGION env variable is sourced for both the outer client AND the inner client?

**Comment by kuhe** [comment] 2024-02-02 03:06
There is pre-existing logic in place to default the inner STS clients to us-east-1 instead of the environment region, I believe because that serves as the global commercial region.

I will investigate whether I can change this to more logically handle other partitions.

**Comment by kuhe** [comment] 2024-02-12 16:46
This should be fixed as of this release: https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.511.0

When initializing a client with no credentials (and therefore using the defaultCredentialProvider) like this:

```ts
new Client({
  region: "govcloud-region"
});
If there is an STS assume role command involved, this inner STS client's region will default to the outer client's resolved region if the region is not in the AWS default partition.

**Comment by Grmiade** [comment] 2024-02-15 11:57
This issue seems to be strangely closed to https://github.com/aws/aws-sdk-js-v3/issues/5799

**Closed** 2024-02-23 19:17 UTC
Labels: bug, p1
